### ISSUE TITLE
agent2 image has no access to docker host sock

### ISSUE THREAD

**Issue by netpages** [zabbix/zabbix-docker#1043]
##### SUMMARY
If agent2 docker image used to monitor docker host agent2 has no access to /var/run/docker.sock

##### OS / ENVIRONMENT / Used docker-compose files
agent2 deploed with:

```
version: '3.8'
services:
  zabbix-agent-2:
    image: zabbix/zabbix-agent2:6.0.12-alpine
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

##### ACTUAL RESULTS

```
cannot fetch data: Get http://1.28/info: dial unix /var/run/docker.sock: connect: permission denied
```

in zabbix agent2 container add a group "docker" with docker group id from host and add zabbix user to this new group solves the problem
```
addgroup -g <DockerGroupIDFromHost> docker
usermod -aG docker zabbix
```

Suggestion add an ENV variable with Docker Group ID from Host if this ENV variable is set add group an add zabbix user to this group
