### ISSUE TITLE
agent2 ipv6 connection rejected - source address doesn't match due to brackets

### ISSUE THREAD

**Issue by KSCK-iCOR** [zabbix/zabbix-docker#1044]
##### SUMMARY
It currently seems impossible to operate an agent2 container with ipv6 using the provided environment parameters.
Either a parser error is thrown because no square brackets were given or if square brackets were given the source address apperantly doesn't match.

The only configuration that works, although (depending on DNS) not guaranteed to use ipv6 for agent initiated connections is ZBX_SERVER_HOST = FQDN and ZBX_ACTIVESERVERS = ipv6

##### OS / ENVIRONMENT / Used docker-compose files
```
version: '2.2'
services:
  zabbix_agent:
    image: zabbix/zabbix-agent2:alpine-6.2-latest
    container_name: zabbix_agent
    user: "1997:1997"
    privileged: true
    environment:
      - ZBX_HOSTNAME=agent.example.com
      - ZBX_SERVER_HOST=server.example.com
      - ZBX_ACTIVE_ALLOW=True
      - ZBX_PASSIVE_ALLOW=True
      - ZBX_ACTIVESERVERS=2001:db8::1
      - ZBX_BUFFERSEND=10
      - ZBX_BUFFERSIZE=200
      - ZBX_REFRESHACTIVECHECKS=300
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode:
      host
```

##### STEPS TO REPRODUCE

```
ZBX_SERVER_HOST=[2001:db8::1]
ZBX_ACTIVESERVERS= *parameter not given
```

=> failed to accept an incoming connection: connection from "2001:db8::1" rejected, allowed hosts: "[2001:db8::1]"

-- 

```
ZBX_SERVER_HOST=2001:db8::1
ZBX_ACTIVESERVERS= *parameter not given
ZBX_PASSIVESERVERS= *parameter not given
```

=> ERROR: cannot parse the "ServerActive" parameter: address "2001:db8::1:10051": address 2001:db8::1:10051: too many colons in address

--

```
ZBX_SERVER_HOST=[2001:db8::1]
ZBX_ACTIVESERVERS=2001:db8::1
ZBX_PASSIVESERVERS= *parameter not given
```

=> ERROR: cannot parse the "ServerActive" parameter: address "[2001:db8::1]:10051" specified more than once

--

```
ZBX_SERVER_HOST= *parameter not given
ZBX_ACTIVESERVERS=2001:db8::1
ZBX_PASSIVESERVERS=2001:db8::1
```

=> cannot connect to [zabbix-server:10051]: dial tcp: lookup zabbix-server on [2001:4860:4860::8888]:53: no such host
=> active check configuration update from host [agent.example.com] started to fail

##### EXPECTED RESULTS
Incomming ipv6 connections should match the ipv6 adresses passed to ZBX_SERVER_HOST regardless of brackets
