### ISSUE TITLE
Failed to startup zabbix-server-mysql:alpine-6.2-latest

### ISSUE THREAD

**Issue by Rubens-Gasparotto** [zabbix/zabbix-docker#1047]
Im trying to compose up the zabbix `zabbix-server-mysql:alpine-6.2-latest` image version, but its giving me this error: 
`6:20230125:181613.701 cannot use database "zabbix": its "users" table is empty (is this the Zabbix proxy database?)`

My docker-compose.yml
```yml
version: '2.4'

services:
  zabbix-db:
    image: mysql:8.0
    container_name: zabbix-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./zabbix-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.2-latest
    container_name: zabbix-server
    restart: always
    ports:
      - 10051:10051
    volumes:
      - ./zabbix-modules:/var/lib/zabbix/modules
    depends_on:
      - zabbix-db
    environment:
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.2-latest
    container_name: zabbix-frontend
    restart: always
    ports:
      - 8080:8080
      - 443:8443
    depends_on:
      - zabbix-db
      - zabbix-server
    environment:
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
```

And the database table was created successfully
![image](https://user-images.githubusercontent.com/54379903/214649952-0ba14d26-5f38-4c18-b70d-022af0805b1c.png)

And users table doesnt really have any entry
![image](https://user-images.githubusercontent.com/54379903/214650164-9c3a7f57-2ba2-4975-b078-36421b326c4b.png)

**Comment by Rubens-Gasparotto** [comment]
I've changed my docker-compose.yml to this and worked

```yml
version: '2.4'

services:
  zabbix-db:
    image: mysql:8.0
    container_name: zabbix-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./zabbix-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.2-latest
    container_name: zabbix-server
    restart: always
    ports:
      - 10051:10051
    volumes:
      - ./zabbix-modules:/var/lib/zabbix/modules
    depends_on:
      - zabbix-db
    environment:
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_ROOT_PASSWORD=zabbix

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.2-latest
    container_name: zabbix-frontend
    restart: always
    ports:
      - 8080:8080
      - 443:8443
    depends_on:
      - zabbix-db
      - zabbix-server
    environment:
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
```
