### ISSUE TITLE
zabbix agent2 cannot register plugins container fails to start

### ISSUE THREAD

**Issue by cybermcm** [zabbix/zabbix-docker#1056]
##### SUMMARY
Official Zabbix Agent 2 image (tag latest) not starting anymore

##### OS / ENVIRONMENT / Used docker-compose files
using official docker image `zabbix/zabbix-agent2:alpine-latest` (sha256:ebf4cbc26ecae9726055b3376942a5fb0ea0250f72086bee44d9ea444737e3cb)
happens on amd64 and arm platform

##### CONFIGURATION
```
zabbix-agent:
  container_name: zabbix-agent
  depends_on:
   sql:
    condition: service_healthy
  environment:
   - ZBX_HOSTNAME=${zabbix_agent_ZBX_HOSTNAME}
   - ZBX_SERVER_HOST=172.18.1.4
   - ZBX_TIMEOUT=20
  hostname: zabbix-agent
  image: zabbix/zabbix-agent2:alpine-latest
  labels:
   - ${WATCHTOWER_TRUE}
  network_mode: "host"
  privileged: true
  restart: unless-stopped
  user: "0:0"
  volumes:
   - ${TIMEZONE}
   - ${LOCALTIME}
   - /dev:/dev
   - /var/run/docker.sock:/var/run/docker.sock:ro
```

##### STEPS TO REPRODUCE
start container -> fails

##### EXPECTED RESULTS
clean startup

##### ACTUAL RESULTS
even with debug level 5 there is only one error message
```
zabbix_agent2 [7]: ERROR: cannot register plugins: plugin cannot be loaded by agent using protocol version 6.2.7, the supported version is 6.4.0
```
