### ISSUE TITLE
nodata on server

### ISSUE THREAD

**Issue by startips** [zabbix/zabbix-docker#1060]
When I configure a ping monitoring on the server, no data is displayed. Data is displayed only when I restart the proxy.
The log does not show any exception:

server:
```version: "3.5"
services:
  mysql-server:
    image: mysql:8.0
    hostname: mysql-server
    container_name: mysql-server
    privileged: true
    expose:
      - 3306
    command:
      --character-set-server=utf8
      --collation-server=utf8_bin
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zbxpasswd
      - MYSQL_ROOT_PASSWORD=zbxpasswd
    volumes:
      - /etc/localtime:/etc/localtime -t
      - /home/docker/mysql/conf:/etc/mysql/conf.d
      - /home/docker/mysql/data/mysql:/var/lib/mysql
    networks:
      zabbix:
        ipv4_address: 192.168.88.9
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:latest
    container_name: zabbix-java-gateway
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime -t
    networks:
      zabbix:
        ipv4_address: 192.168.88.10
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server-mysql
    hostname: zabbix-server
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime -t
      - /home/docker/data/zabbix:/usr/lib/zabbix
      - /home/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /home/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zbxpasswd
      - MYSQL_ROOT_PASSWORD=zbxpasswd
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
      - ZBX_STARTPOLLERS=30
      - ZBX_IPMIPOLLERS=5
      - ZBX_STARTPREPROCESSORS=30
      - ZBX_STARTPOLLERSUNREACHABLE=30
      - ZBX_STARTTRAPPERS=30
      - ZBX_STARTPINGERS=200
      - ZBX_STARTDISCOVERERS=20
      - ZBX_STARTHTTPPOLLERS=20
      - ZBX_STARTTIMERS=20
      - ZBX_STARTESCALATORS=30
      - ZBX_STARTALERTERS=20
    ports:
      - 10051:10051
    depends_on:
      - mysql-server
      - zabbix-java-gateway
    networks:
      zabbix:
        ipv4_address: 192.168.88.11
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web-nginx-mysql
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime -t
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zbxpasswd
      - MYSQL_ROOT_PASSWORD=zbxpasswd
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - mysql-server
      - zabbix-java-gateway
    networks:
      zabbix:
        ipv4_address: 192.168.88.12

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: always
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_SERVER_HOST=192.168.88.11
      - ZBX_SERVER_PORT=10051
    volumes:
      - /etc/localtime:/etc/localtime -t
      - /home/zabbix/agent/zabbix_agentd.d/:/etc/zabbix/zabbix_agentd.d/
      - /home/zabbix/agent/scripts/:/etc/zabbix/scripts/
    networks:
      zabbix:
        ipv4_address: 192.168.88.13
networks:
  zabbix:
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24
```
proxy:
```
version: '3'
services:
  mysql-server:
    image: mysql:8.0
    hostname: mysql-server
    container_name: mysql-server
    privileged: true
    expose:
      - 3306
    command:
      --character-set-server=utf8
      --collation-server=utf8_bin
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=zabbix_proxy
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix.proxy
      - MYSQL_ROOT_PASSWORD=zbxpasswd
    volumes:
      - /etc/localtime:/etc/localtime -t
      - /home/docker/mysql/conf:/etc/mysql/conf.d
      - /home/docker/mysql/data/mysql:/var/lib/mysql
    networks:
      zabbix:
        ipv4_address: 192.168.88.9


  zabbix-proxy:
    image: zabbix/zabbix-proxy-mysql
    container_name: zabbix-proxy
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      zabbix:
        ipv4_address: 192.168.88.10
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix_proxy
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix.proxy
      - ZBX_HOSTNAME=zbx-proxy-002 #需要修改
      - ZBX_SERVER_HOST=10.72.254.40
      - ZBX_STARTPINGERS=100
      - ZBX_ENABLEREMOTECOMMANDS=1
      - ZBX_CONFIGFREQUENCY=60
    depends_on:
      - mysql-server

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent-002
    restart: always
    environment:
      - ZBX_HOSTNAME=zabbix-agent-002 #需要修改
      - ZBX_SERVER_HOST=10.72.254.40
      - ZBX_SERVER_PORT=10051
    ports:
      - 10060:10050
    volumes:
      - /etc/localtime:/etc/localtime -t
      - /home/zabbix/agent/zabbix_agentd.d/:/etc/zabbix/zabbix_agentd.d/
      - /home/zabbix/agent/scripts/:/etc/zabbix/scripts/
    networks:
      zabbix:
        ipv4_address: 192.168.88.13
networks:
  zabbix:
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24
```
