### ISSUE TITLE
Zabbix PostgresSQL schema creation slow

### ISSUE THREAD

**Issue by enricobenedos** [zabbix/zabbix-docker#1066]
##### SUMMARY
Postgres schema creation process takes 7 minutes to finish. 

##### OS / ENVIRONMENT / Used docker-compose files

Docker Engine: `v20.10.23`
Windows 11: `22H2`

```yml
version: '3.8'

services:
  zabbix-db:
    image: postgres:15.2-alpine
    networks:
      - zabbix-net
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix345
      POSTGRES_DB: zabbix

  zabbix-server:
    depends_on:
      - zabbix-db
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    networks:
      - zabbix-net
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: 192.168.28.27
      DB_SERVER_PORT: 5434
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix345
  
  zabbix-frontend:
    depends_on:
      - zabbix-server
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    networks:
      - zabbix-net
    ports:
      - "83:8080"
    environment:
      DB_SERVER_HOST: 192.168.28.27
      DB_SERVER_PORT: 5434
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix345
      ZBX_SERVER_HOST: 192.168.28.27
      PHP_TZ: it

networks:
  zabbix-net:
```

##### STEPS TO REPRODUCE

Simply start the containers using docker compose.

```yaml
docker compose up -d
```

##### EXPECTED RESULTS

I expect that schema creation will take less time.
