### ISSUE TITLE
NGINX-MYSQL: Accessing webpage error: Database connect via null

### ISSUE THREAD

**Issue by RedTwinkies** [zabbix/zabbix-docker#1080]
##### SUMMARY
When enabling SSL certs for DB Communication, the frontend NGINX container is giving me an error before I am even able to login.
"Database error: (trying to connect via (null))"
I was able to get into the web frontend container and use the mysql command to connect to the docker networked IP of the mysql-server using the credentials from the .MYSQL_* files.
The zabbix-server was able to connect to the mysql database and do everything it needs.
I looked around as much as I could in the containers but I am not sure what is making the Database become a null value.

Virtual Machine - Ubuntu 22.04.2 LTS

> 4 CPU - 8 GB RAM - 80 GB Storage

Docker Engine - Community Version:  23.0.5
Docker Compose version v2.17.3
Template: docker-compose_v3_ubuntu_mysql_latest.yaml

##### CONFIGURATION
Cert Creation:
```
openssl req -x509 -noenc -sha256 -days 3650 -subj "Redacted>" \
	-newkey rsa:2048 -keyout ./env_vars/.ZBX_DB_CA_KEY -out ./env_vars/.ZBX_DB_CA_FILE
openssl req -noenc -subj "<Redacted>" \
	-newkey rsa:2048 -keyout ./env_vars/.DB_KEY_FILE -out ./env_vars/.DB_CSR_FILE
openssl req -noenc -subj "Redacted>" \
	-newkey rsa:2048 -keyout ./env_vars/.ZBX_DB_KEY_FILE -out ./env_vars/.ZBX_DB_CSR_FILE
openssl x509 -req -CA ./env_vars/.ZBX_DB_CA_FILE -CAkey ./env_vars/.ZBX_DB_CA_KEY \
	-in ./env_vars/.DB_CSR_FILE -out ./env_vars/.DB_CERT_FILE -days 3650
openssl x509 -req -CA ./env_vars/.ZBX_DB_CA_FILE -CAkey ./env_vars/.ZBX_DB_CA_KEY \
	-in ./env_vars/.ZBX_DB_CSR_FILE -out ./env_vars/.ZBX_DB_CERT_FILE -days 3650
sudo chmod 444 ./env_vars/.ZBX_DB_CA_FILE
sudo chmod 444 ./env_vars/.DB_CERT_FILE
sudo chmod 444 ./env_vars/.DB_KEY_FILE
sudo chmod 444 ./env_vars/.ZBX_DB_CERT_FILE
sudo chmod 444 ./env_vars/.ZBX_DB_KEY_FILE
```

Modified .env_srv:
```
ZBX_DBTLSCONNECT=required
ZBX_DBTLSCAFILE=/run/secrets/root-ca.pem
ZBX_DBTLSCERTFILE=/run/secrets/client-cert.pem
ZBX_DBTLSKEYFILE=/run/secrets/client-key.pem
ZBX_ENABLE_SNMP_TRAPS=true
```

Modified .env_db_mysql:
```
DB_SERVER_HOST=mysql-server
DB_SERVER_PORT=3306
MYSQL_USER_FILE=/run/secrets/MYSQL_USER
MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
MYSQL_ALLOW_EMPTY_PASSWORD=false
MYSQL_DATABASE=zabbix
```

Modified .env_web:
```
ZBX_SERVER_HOST=zabbix-server
ZBX_SERVER_NAME=zabbix-websrv
ZBX_DB_ENCRYPTION=true
ZBX_DB_KEY_FILE=/run/secrets/client-key.pem
ZBX_DB_CERT_FILE=/run/secrets/client-cert.pem
ZBX_DB_CA_FILE=/run/secrets/root-ca.pem
ZBX_DB_VERIFY_HOST=false
PHP_TZ=America/Chicago
```

env_vars files:
```
-rw-rw-r-- 1 shadmin shadmin 28411 May  2 19:21 chrome_dp.json
-r--r--r-- 1 shadmin shadmin  1241 May 15 19:30 .DB_CERT_FILE
-rw-rw-r-- 1 shadmin shadmin  1017 May 15 19:30 .DB_CSR_FILE
-r--r--r-- 1 shadmin shadmin  1704 May 15 19:30 .DB_KEY_FILE
-rw-rw-r-- 1 shadmin shadmin  1014 May 10 21:05 .env_agent
-rw-rw-r-- 1 shadmin shadmin   362 May 15 20:08 .env_db_mysql
-rw-rw-r-- 1 shadmin shadmin  3012 May 15 20:12 .env_srv
-rw-rw-r-- 1 shadmin shadmin  1729 May 15 21:42 .env_web
-rw-rw-r-- 1 shadmin shadmin   212 May 10 21:05 .env_web_service
-rw-rw-r-- 1 shadmin shadmin    14 May  2 19:27 .MYSQL_PASSWORD
-rw-rw-r-- 1 shadmin shadmin    14 May  2 19:27 .MYSQL_ROOT_PASSWORD
-rw-rw-r-- 1 shadmin shadmin     4 May 10 17:27 .MYSQL_ROOT_USER
-rw-rw-r-- 1 shadmin shadmin     6 May 10 17:27 .MYSQL_USER
-r--r--r-- 1 shadmin shadmin  1363 May 15 19:30 .ZBX_DB_CA_FILE
-rw------- 1 shadmin shadmin  1704 May 15 19:30 .ZBX_DB_CA_KEY
-r--r--r-- 1 shadmin shadmin  1237 May 15 19:30 .ZBX_DB_CERT_FILE
-rw-rw-r-- 1 shadmin shadmin  1013 May 15 19:30 .ZBX_DB_CSR_FILE
-r--r--r-- 1 shadmin shadmin  1704 May 15 19:30 .ZBX_DB_KEY_FILE
```

Modified docker-compose.yml:
```
version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:ubuntu-6.4-latest
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
#   - dbsocket:/var/run/mysqld/
   - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
   - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  env_file:
   - ./env_vars/.env_db_mysql
   - ./env_vars/.env_srv
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_USER
   - MYSQL_ROOT_PASSWORD
   - client-key.pem
   - client-cert.pem
   - root-ca.pem
  depends_on:
   - mysql-server
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-mysql
      - zabbix-server-ubuntu-mysql
      - zabbix-server-mysql-ubuntu
   zbx_net_frontend:
#  devices:
#   - "/dev/ttyUSB0:/dev/ttyUSB0"
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "ubuntu"

 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:ubuntu-6.4-latest
  ports:
   - "80:8080"
   - "443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
#   - dbsocket:/var/run/mysqld/
   - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
   - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  env_file:
   - ./env_vars/.env_db_mysql
   - ./env_vars/.env_web
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - client-key.pem
   - client-cert.pem
   - root-ca.pem
  depends_on:
   - mysql-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-nginx-mysql
     - zabbix-web-nginx-ubuntu-mysql
     - zabbix-web-nginx-mysql-ubuntu
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "ubuntu"

 zabbix-agent:
  image: zabbix/zabbix-agent:ubuntu-6.4-latest
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  env_file:
   - ./env_vars/.env_agent
  privileged: true
  pid: "host"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-ubuntu
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "ubuntu"

 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:ubuntu-6.4-latest
  ports:
   - "162:1162/udp"
  volumes:
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  networks:
   zbx_net_frontend:
    aliases:
     - zabbix-snmptraps
   zbx_net_backend:
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "ubuntu"

 zabbix-web-service:
  image: zabbix/zabbix-web-service:ubuntu-6.4-latest
  ports:
   - "10053:10053"
  volumes:
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
  security_opt:
   - seccomp:./env_vars/chrome_dp.json
  env_file:
   - ./env_vars/.env_web_service
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-service
     - zabbix-web-service-ubuntu
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix web service"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "web-service"
   com.zabbix.os: "ubuntu"

 mysql-server:
  image: mysql:8.0-oracle
  command:
   - mysqld
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_bin
   - --default-authentication-plugin=mysql_native_password
   - --require-secure-transport
   - --ssl-ca=/run/secrets/root-ca.pem
   - --ssl-cert=/run/secrets/server-cert.pem
   - --ssl-key=/run/secrets/server-key.pem
  volumes:
   - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
#   - dbsocket:/var/run/mysqld/
  env_file:
   - ./env_vars/.env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
   - server-key.pem
   - server-cert.pem
   - root-ca.pem
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - mysql-server
     - zabbix-database
     - mysql-database

 db_data_mysql:
  image: busybox
  volumes:
   - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  snmptraps:
#  dbsocket:

secrets:
  MYSQL_USER:
    file: ./env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./env_vars/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: ./env_vars/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: ./env_vars/.MYSQL_ROOT_PASSWORD
  client-key.pem:
    file: ./env_vars/.ZBX_DB_KEY_FILE
  client-cert.pem:
    file: ./env_vars/.ZBX_DB_CERT_FILE
  root-ca.pem:
    file: ./env_vars/.ZBX_DB_CA_FILE
  server-cert.pem:
    file: ./env_vars/.DB_CERT_FILE
  server-key.pem:
    file: ./env_vars/.DB_KEY_FILE
```

##### STEPS TO REPRODUCE
Pulled down the docker compose template and the created the certificates for SSL as above, then adjusted the environmental variables and tried to run the compose file. Everything appears to spin up correctly, no errors in the output of "docker compose up".
I am able to connect to the website "http://<RedactedIPAddress>/" but I get the error as stated above immediately.
I expected to be presented with the login page to be able to login.

**Comment by dotneft** [comment]
I do not see DB_SERVER_HOST for web container.

**Comment by RedTwinkies** [comment]
It is stored in the  .env_db_mysql file. When i run docker compose it shows the correct info for the server/port/database.

```
Modified .env_db_mysql:

DB_SERVER_HOST=mysql-server
DB_SERVER_PORT=3306
MYSQL_USER_FILE=/run/secrets/MYSQL_USER
MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
MYSQL_ALLOW_EMPTY_PASSWORD=false
MYSQL_DATABASE=zabbix

Modified .env_web:

ZBX_SERVER_HOST=zabbix-server
ZBX_SERVER_NAME=zabbix-websrv
ZBX_DB_ENCRYPTION=true
ZBX_DB_KEY_FILE=/run/secrets/client-key.pem
ZBX_DB_CERT_FILE=/run/secrets/client-cert.pem
ZBX_DB_CA_FILE=/run/secrets/root-ca.pem
ZBX_DB_VERIFY_HOST=false
PHP_TZ=America/Chicago
```




```
zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:ubuntu-6.4-latest
...
  env_file:
   - ./env_vars/.env_db_mysql
   - ./env_vars/.env_web
...
```
