### ISSUE TITLE
Snmptrap docker image can't find host if "Connect to" is set to DNS in Zabbix

### ISSUE THREAD

**Issue by nerdalertdk** [zabbix/zabbix-docker#1100]
##### SUMMARY

Snmptrap docker image can't find host if "Connect to" is set to DNS in Zabbix

![Skærmbillede 2023-09-29 kl  12 42 34](https://github.com/zabbix/zabbix-docker/assets/3426495/9d4518d6-213d-4a9b-80b7-cbf617dd1a88)

When set to IP, it works

##### OS / ENVIRONMENT / Used docker-compose files

Host: Debian 11
docker: Docker version 20.10.21
Zabbix: 6.2

Snmptrap log
```
2023-09-29 10:45:42 UDP: [XXX.XXX.XXX.XXX]:33902->[172.16.238.3]:1162 [UDP: [XXX.XXX.XXX.XXX]:33902->[172.16.238.3]:1162]:
DISMAN-EVENT-MIB::sysUpTimeInstance = 914421649	SNMPv2-MIB::snmpTrapOID.0 = OID: DEVICE DATA
```

##### CONFIGURATION

```yaml
zabbix-snmptraps:
    container_name: zabbix-snmptraps
    hostname: zabbix-snmptraps
    image: zabbix/zabbix-snmptraps:ubuntu-6.2-latest
    restart: unless-stopped
    ports:
     - "162:1162/udp"
    volumes:
     - /data/docker/zabbix-srv/snmptraps:/var/lib/zabbix/snmptraps:rw
     - /data/docker/zabbix-srv/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
    networks:
      zbx_net_frontend:
       aliases:
        - zabbix-snmptraps
      zbx_net_backend:
    stop_grace_period: 5s
```

```yaml
zabbix-server:
    container_name: zabbix-server
    hostname: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-6.2-latest
    restart: unless-stopped
    ports:
     - "10051:10051"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /data/docker/zabbix-srv/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
     - /data/docker/zabbix-srv/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
     - /data/docker/zabbix-srv/var/lib/zabbix/export:/var/lib/zabbix/export:rw
     - /data/docker/zabbix-srv/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
     - /data/docker/zabbix-srv/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
     - /data/docker/zabbix-srv/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
     - /data/docker/zabbix-srv/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
     - /data/docker/zabbix-srv/snmptraps:/var/lib/zabbix/snmptraps:rw
    env_file:
     - /data/docker/zabbix-cfg/.env_db_mysql
     - /data/docker/zabbix-cfg/.env_srv
    depends_on:
     - zabbix-db
    networks:
     zbx_net_backend:
     zbx_net_frontend:

    stop_grace_period: 30s
    sysctls:
     - net.ipv4.ip_local_port_range=1024 65000
     - net.ipv4.conf.all.accept_redirects=0
     - net.ipv4.conf.all.secure_redirects=0
     - net.ipv4.conf.all.send_redirects=0

```

.env_srv
```
# Core
ZBX_ENABLE_SNMP_TRAPS=true

# Cache
ZBX_CACHESIZE=8G
ZBX_HISTORYCACHESIZE=2G
ZBX_HISTORYINDEXCACHESIZE=2G
ZBX_VALUECACHESIZE=4G
ZBX_TRENDCACHESIZE=1G

# Pollers and Other
ZBX_STARTJAVAPOLLERS=5
ZBX_STARTPOLLERS=100
ZBX_STARTPOLLERSUNREACHABLE=50
ZBX_STARTTRAPPERS=10
ZBX_STARTPINGERS=50
ZBX_STARTDISCOVERERS=10
ZBX_STARTPREPROCESSORS=15
ZBX_STARTHTTPPOLLERS=5
ZBX_STARTTIMERS=2
ZBX_STARTESCALATORS=2
ZBX_STARTALERTERS=5
ZBX_TIMEOUT=10
```

```yaml
networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24

  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
```
