### ISSUE TITLE
PostgreSQL server is not available. Waiting 5 seconds...

### ISSUE THREAD

**Issue by pfernandez-veconinter** [zabbix/zabbix-docker#1106]
##### SUMMARY

I have a problem with PostgreSQL. 

Postgresql in the container is online

`zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.684 UTC [1] LOG:  database system is ready to accept connections`

but I have: 

`zabbix-docker-zabbix-server-1           | **** PostgreSQL server is not available. Waiting 5 seconds...`
`zabbix-docker-zabbix-web-nginx-pgsql-1  | **** PostgreSQL server is not available. Waiting 5 seconds...`

##### OS / ENVIRONMENT / Used docker-compose files

OS: Rocky Linux 9
Enviroment: Docker. 

DOcker compose:

```
version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
   - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
#   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
#   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
#   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
  env_file:
   - ./env_vars/.env_db_pgsql
   - ./env_vars/.env_srv
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  depends_on:
   - postgres-server
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-pgsql
      - zabbix-server-alpine-pgsql
      - zabbix-server-pgsql-alpine
   zbx_net_frontend:
#  devices:
#   - "/dev/ttyUSB0:/dev/ttyUSB0"
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 64999
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with PostgreSQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

 zabbix-proxy-sqlite3:
  image: zabbix/zabbix-proxy-sqlite3:alpine-6.4-latest
  profiles:
   - all
  ports:
   - "10061:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.3'
      memory: 256M
  env_file:
   - ./env_vars/.env_prx
   - ./env_vars/.env_prx_sqlite3
  depends_on:
   - zabbix-java-gateway
   - zabbix-snmptraps
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-proxy-sqlite3
     - zabbix-proxy-alpine-sqlite3
     - zabbix-proxy-sqlite3-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix proxy with SQLite3 database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-proxy"
   com.zabbix.dbtype: "sqlite3"
   com.zabbix.os: "alpine"

 zabbix-proxy-mysql:
  image: zabbix/zabbix-proxy-mysql:alpine-6.4-latest
  profiles:
   - all
  ports:
   - "10071:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.3'
      memory: 256M
  env_file:
   - ./env_vars/.env_db_mysql_proxy
   - ./env_vars/.env_prx
   - ./env_vars/.env_prx_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_USER
   - MYSQL_ROOT_PASSWORD
  depends_on:
   - mysql-server
   - zabbix-java-gateway
   - zabbix-snmptraps
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-proxy-mysql
     - zabbix-proxy-alpine-mysql
     - zabbix-proxy-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix proxy with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-proxy"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-web-apache-pgsql:
  image: zabbix/zabbix-web-apache-pgsql:alpine-6.4-latest
  profiles:
   - all
  ports:
   - "8081:8080"
   - "8443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
   - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
#   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
#   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
#   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  env_file:
   - ./env_vars/.env_db_pgsql
   - ./env_vars/.env_web
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  depends_on:
   - postgres-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-apache-pgsql
     - zabbix-web-apache-alpine-pgsql
     - zabbix-web-apache-pgsql-alpine
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Apache web-server with PostgreSQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "apache2"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

 zabbix-web-nginx-pgsql:
  image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
  ports:
   - "80:8080"
   - "443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
   - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
#   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
#   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
#   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  env_file:
   - ./env_vars/.env_db_pgsql
   - ./env_vars/.env_web
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  depends_on:
   - postgres-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-nginx-pgsql
     - zabbix-web-nginx-alpine-pgsql
     - zabbix-web-nginx-pgsql-alpine
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-6.4-latest
  profiles:
   - full
   - all
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  deploy:
   resources:
    limits:
      cpus: '0.2'
      memory: 128M
    reservations:
      cpus: '0.1'
      memory: 64M
   mode: global
  env_file:
   - ./env_vars/.env_agent
  privileged: true
  pid: "host"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-alpine
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "alpine"

 zabbix-java-gateway:
  image: zabbix/zabbix-java-gateway:alpine-6.4-latest
  profiles:
   - full
   - all
  ports:
   - "10052:10052"
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 512M
    reservations:
      cpus: '0.25'
      memory: 256M
  env_file:
   - ./env_vars/.env_java
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-java-gateway
     - zabbix-java-gateway-alpine
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix Java Gateway"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "java-gateway"
   com.zabbix.os: "alpine"

 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:alpine-6.4-latest
# Override snmptrapd command arguments to receive SNMP traps by DNS
# It must be done with ZBX_SNMP_TRAP_USE_DNS=true environment variable
#  command: /usr/sbin/snmptrapd -C -c /etc/snmp/snmptrapd.conf -Lo -A
  profiles:
   - full
   - all
  ports:
   - "162:1162/udp"
  volumes:
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 256M
    reservations:
      cpus: '0.25'
      memory: 128M
  env_file:
   - ./env_vars/.env_snmptraps
  networks:
   zbx_net_frontend:
    aliases:
     - zabbix-snmptraps
   zbx_net_backend:
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "alpine"

 zabbix-web-service:
  image: zabbix/zabbix-web-service:alpine-6.4-latest
  profiles:
   - full
   - all
  ports:
   - "10053:10053"
  volumes:
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
  security_opt:
   - seccomp:./env_vars/chrome_dp.json
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 512M
    reservations:
      cpus: '0.25'
      memory: 256M
  env_file:
   - ./env_vars/.env_web_service
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-service
     - zabbix-web-service-alpine
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix web service"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "web-service"
   com.zabbix.os: "alpine"

 mysql-server:
  image: mysql:8.0-oracle
  profiles:
   - all
  command:
   - mysqld
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_bin
# Only during upgrade from versions prior 6.4
#   - --log_bin_trust_function_creators=1
  volumes:
   - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
  env_file:
   - ./env_vars/.env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - mysql-server
     - zabbix-database
     - mysql-database

 postgres-server:
  image: postgres:15-alpine
#  command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
  volumes:
   - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
  env_file:
   - ./env_vars/.env_db_pgsql
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - postgres-server
     - pgsql-server
     - pgsql-database

 db_data_mysql:
  image: busybox
  profiles:
   - all
  volumes:
   - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw

 db_data_pgsql:
  image: busybox
  volumes:
   - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw

# elasticsearch:
#  image: elasticsearch
#  profiles:
#   - full
#   - all
#  environment:
#   - transport.host=0.0.0.0
#   - discovery.zen.minimum_master_nodes=1
#  networks:
#   zbx_net_backend:
#    aliases:
#     - elasticsearch

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  snmptraps:

secrets:
  MYSQL_USER:
    file: ./env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./env_vars/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: ./env_vars/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: ./env_vars/.MYSQL_ROOT_PASSWORD
  POSTGRES_USER:
    file: ./env_vars/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./env_vars/.POSTGRES_PASSWORD`

```
##### CONFIGURATION

The same in the docker. 

##### STEPS TO REPRODUCE

`docker compose up -f ./docker-compose_v3_alpine_pgsql_latest.yaml up`

```yaml

```

##### EXPECTED RESULTS

Zabbix running

##### ACTUAL RESULTS

Total reclaimed space: 1.87kB                                                                                 
[root@localhost zabbix-docker]# docker compose -f ./docker-compose_v3_alpine_pgsql_latest.yaml up --build     
[+] Running 7/5                                                                                               
 ✔ Network zabbix-docker_zbx_net_backend             Created                                                  
 ✔ Network zabbix-docker_zbx_net_frontend            Created                                                  
 ✔ Network zabbix-docker_default                     Created                                                  
 ✔ Container zabbix-docker-db_data_pgsql-1           Created                                                  
 ✔ Container zabbix-docker-postgres-server-1         Created                                                  
 ✔ Container zabbix-docker-zabbix-server-1           Created                                                  
 ✔ Container zabbix-docker-zabbix-web-nginx-pgsql-1  Crea...                                                  
Attaching to zabbix-docker-db_data_pgsql-1, zabbix-docker-postgres-server-1, zabbix-docker-zabbix-server-1, za
zabbix-docker-postgres-server-1         |                                                                     
zabbix-docker-postgres-server-1         | PostgreSQL Database directory appears to contain a database; Skippin
zabbix-docker-postgres-server-1         |                                                                     
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.525 UTC [1] LOG:  starting PostgreSQL 15.5 on x8
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.525 UTC [1] LOG:  listening on IPv4 address "0.0
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.526 UTC [1] LOG:  listening on IPv6 address "::"
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.528 UTC [1] LOG:  listening on Unix socket "/var
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.531 UTC [24] LOG:  database system was interrupt
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.666 UTC [24] LOG:  database system was not prope
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.668 UTC [24] LOG:  invalid record length at 0/19
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.669 UTC [24] LOG:  redo is not required         
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.673 UTC [22] LOG:  checkpoint starting: end-of-r
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.677 UTC [22] LOG:  checkpoint complete: wrote 3 
002 s, average=0.001 s; distance=0 kB, estimate=0 kB                                                          
zabbix-docker-postgres-server-1         | 2023-11-17 19:12:09.684 UTC [1] LOG:  database system is ready to ac
zabbix-docker-db_data_pgsql-1 exited with code 0                                                              
zabbix-docker-zabbix-server-1           | ** Preparing Zabbix server                                          
zabbix-docker-zabbix-server-1           | ** Preparing database                                               
zabbix-docker-zabbix-server-1           | ** Using POSTGRES_USER variable from secret file                    
zabbix-docker-zabbix-server-1           | ** Using POSTGRES_PASSWORD variable from secret file                
zabbix-docker-zabbix-server-1           | ********************                                                
zabbix-docker-zabbix-server-1           | * DB_SERVER_HOST: postgres-server                                   
zabbix-docker-zabbix-server-1           | * DB_SERVER_PORT: 5432                                              
zabbix-docker-zabbix-server-1           | * DB_SERVER_DBNAME: zabbix                                          
zabbix-docker-zabbix-server-1           | * DB_SERVER_SCHEMA: public                                          
zabbix-docker-zabbix-server-1           | ********************                                                
zabbix-docker-zabbix-server-1           | **** PostgreSQL server is not available. Waiting 5 seconds...       
zabbix-docker-zabbix-web-nginx-pgsql-1  | ** Deploying Zabbix web-interface (Nginx) with PostgreSQL database  
zabbix-docker-zabbix-web-nginx-pgsql-1  | ** Using POSTGRES_USER variable from secret file                    
zabbix-docker-zabbix-web-nginx-pgsql-1  | ** Using POSTGRES_PASSWORD variable from secret file                
zabbix-docker-zabbix-web-nginx-pgsql-1  | ********************                                                
zabbix-docker-zabbix-web-nginx-pgsql-1  | * DB_SERVER_HOST: postgres-server                                   
zabbix-docker-zabbix-web-nginx-pgsql-1  | * DB_SERVER_PORT: 5432                                              
zabbix-docker-zabbix-web-nginx-pgsql-1  | * DB_SERVER_DBNAME: zabbix                                          
zabbix-docker-zabbix-web-nginx-pgsql-1  | * DB_SERVER_SCHEMA: public                                          
zabbix-docker-zabbix-web-nginx-pgsql-1  | ********************                                                
zabbix-docker-zabbix-web-nginx-pgsql-1  | **** PostgreSQL server is not available. Waiting 5 seconds...       
zabbix-docker-zabbix-server-1           | **** PostgreSQL server is not available. Waiting 5 seconds...       
zabbix-docker-zabbix-web-nginx-pgsql-1  | **** PostgreSQL server is not available. Waiting 5 seconds...       
zabbix-docker-zabbix-server-1           | **** PostgreSQL server is not available. Waiting 5 seconds...       
zabbix-docker-zabbix-web-nginx-pgsql-1  | **** PostgreSQL server is not available. Waiting 5 seconds...       
zabbix-docker-zabbix-server-1           | **** PostgreSQL server is not available. Waiting 5 seconds...       
zabbix-docker-zabbix-web-nginx-pgsql-1  | **** PostgreSQL server is not available. Waiting 5 seconds...       
zabbix-docker-zabbix-server-1           | **** PostgreSQL server is not available. Waiting 5 seconds...       
zabbix-docker-zabbix-web-nginx-pgsql-1  | **** PostgreSQL server is not available. Waiting 5 seconds...       

```paste below

```
