### ISSUE TITLE
Proxy image 6.0-alpine-latest does not use environment variable ZBX_SERVER_PORT

### ISSUE THREAD

**Issue by pizzidellamaremma** [zabbix/zabbix-docker#1123]
Proxy image 6.0-alpine-latest does not use environment `ZBX_SERVER_PORT`.

Trying to upgrade proxies after server upgrade, I'm using the image `zabbix-proxy-sqlite3:6.0-alpine-latest`, same docker-compose.yaml file as before but from container logs I see it's trying to use the default port instead of the custom one:
`169:20240116:160100.064 Unable to connect to {myserverdnsname}:10051 [cannot connect to [{myserverdnsname}:10051]: [4] Interrupted system call]`

My docker-compose file:
```
version: '3'
services:
  zabbix-proxy:
    container_name: zabbix-proxy
    image: zabbix/zabbix-proxy-sqlite3:6.0-alpine-latest
    restart: always
    ports:
      - 10051:10051
    volumes:
      - ./zabbix/enc:/var/lib/zabbix/enc
    environment:
      - ZBX_PROXYMODE=0
      - ZBX_HOSTNAME=ILS2-ZPX
      - ZBX_SERVER_HOST={myserverdnsname}
      - ZBX_SERVER_PORT=10151
      - ZBX_TLSCONNECT=psk
      - ZBX_TLSPSKIDENTITY={tlsidentity}
      - ZBX_TLSPSKFILE=.psk
```

It probably happens with `zabbix-proxy-sqlite3:alpine-trunk` too but I do not have the possibility to check for sure right now. Tried the same update and the proxy never logged into the server.
