### ISSUE TITLE
Some environment variables are not working

### ISSUE THREAD

**Issue by ISnotes** [zabbix/zabbix-docker#1260]
##### SUMMARY
I use the EXPOSE_WEB_SERVER_INFO=off variable to hide the PHP version, but nothing happens as a result

##### CONFIGURATION
```
    zabbix-web-apache-mysql:
        container_name: zabbix-web-apache-mysql
        image: zabbix/zabbix-web-apache-mysql:alpine-6.4.11
        networks:
            - zabbix-net
        ports:
            - 80:8080
            - 443:8443
        environment:
            - PHP_TZ=Europe/Moscow
            - DB_SERVER_HOST=mariadb
            - MYSQL_USER_FILE=/run/secrets/MYSQL_USER
            - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
            - EXPOSE_WEB_SERVER_INFO=off
            - ZBX_SERVER_HOST=zabbix-server-mysql
            - ZBX_SERVER_NAME=Docker
        secrets:
            - MYSQL_USER
            - MYSQL_PASSWORD
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./apache2/ssl:/etc/ssl/apache2:ro
            - ./apache2/apache_ssl.conf:/etc/zabbix/apache_ssl.conf:ro
            - ./apache2/httpd.conf:/etc/apache2/httpd.conf:ro
        depends_on:
            - zabbix-server-mysql
        restart: always
```

##### STEPS TO REPRODUCE
Run docker container and check headers

##### EXPECTED RESULTS
PHP version hidden

##### ACTUAL RESULTS
PHP version is shown in headers
![image](https://github.com/zabbix/zabbix-docker/assets/12543500/b8d4c2a0-a80f-4c01-9658-cd7243d900a5)
