### ISSUE TITLE
No documentation for linking server with a postgres running in a container

### ISSUE THREAD

**Issue by GreggJensen** [zabbix/zabbix-docker#129]
I am trying to set up a prototype environment to get an understanding of zabbix. I'm following the documentation for the server-pgsql and the web-nginx-pgsql and see a command line to link the web server to the database but not the server.  Is this an oversight or is this not going to work, and the database has to be running on a host (i.e., not a container)?

**Comment by ronnicek** [comment]
Database can run localy or in container, but then you have to change configuration of Zabbix. Best is use docker-compose, where database is included in services and it will start all together :)

**Comment by Landver** [comment]
Example of my docker-compose configuration, that use posgresql (just don't forget to create zabbix database in db container):
```
version: '3'

services:
  db: # database server
    image: postgres
    volumes:
      - ../postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    zabbix-server:  # The server performs the polling and trapping of data, it calculates triggers, sends notifications to users
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    volumes:
      - ../zabbix-server/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps
      - ../zabbix-server/var/lib/zabbix/mibs:/var/lib/zabbix/mibs
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=kkk
    depends_on:
      - db
  zabbix-web-apache-pgsql:  # Zabbix frontend based on Apache web-server with PostgreSQL database support
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-latest
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=kkk
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Jerusalem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - zabbix-server
```
