### ISSUE TITLE
Docker Image Ubuntu and Alpine zabbix/zabbix-web-nginx-pgsql 6.4.13 show 6.4.12 on Web Interface

### ISSUE THREAD

**Issue by azcorptech** [zabbix/zabbix-docker#1324]
##### SUMMARY

Docker images Alpine and Ubuntu image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4.13 show 6.4.12 in Zabbix Front End.

##### STEPS TO REPRODUCE

thiagomz@Laptop-T14-TMZ:~/docker-compose/zabbix-6.4$ sudo docker compose -f zabbix-stack.yml --env-file zabbix-stack.env up -d
[sudo] password for thiagomz:
[+] Running 5/6
 ⠏ Network zabbix-64_default    Created                                                                  2.9s
 ✔ Container postgresql-server  Started                                                                  1.3s
 ✔ Container nginx-prx-mgr      Started                                                                  1.3s
 ✔ Container zabbix-server      Started                                                                  1.7s
 ✔ Container zabbix-web         Started                                                                  2.5s
 ✔ Container zabbix-agent       Started                                                                  2.5s
thiagomz@Laptop-T14-TMZ:~/docker-compose/zabbix-6.4$ grep image zabbix-stack.yml
    image: 'jc21/nginx-proxy-manager:latest'
    image: postgres:latest
    image: zabbix/zabbix-server-pgsql:alpine-6.4.13
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4.13
    image: zabbix/zabbix-agent:alpine-6.4.13

thiagomz@Laptop-T14-TMZ:~/docker-compose/zabbix-6.4$ sudo docker exec -it zabbix-web /bin/bash

a5be4456029e:/usr/share/zabbix$ grep -iR 6.4.13 *
a5be4456029e:/usr/share/zabbix$

a5be4456029e:/usr/share/zabbix$ grep -iR 6.4.12 *
include/defines.inc.php:define('ZABBIX_VERSION',                '6.4.12');
include/defines.inc.php:define('ZABBIX_API_VERSION',    '6.4.12');

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by dotneft** [comment]
I can not confirm that.  Everything is fine:
```
REPOSITORY                      TAG                IMAGE ID       CREATED         SIZE
zabbix/zabbix-web-nginx-pgsql   alpine-6.4.13      16d07236657e   32 hours ago    224MB

```

**Comment by azcorptech** [comment]
Ok, let's try again : 

IMAGES
-----


```
root@Laptop-T14-TMZ:~# docker images
REPOSITORY                      TAG             IMAGE ID       CREATED        SIZE
zabbix/zabbix-web-nginx-pgsql   ubuntu-6.4.13   161efaa0d336   35 hours ago   415MB
zabbix/zabbix-server-pgsql      ubuntu-6.4.13   651ed9ef8890   35 hours ago   246MB
zabbix/zabbix-web-nginx-pgsql   alpine-6.4.13   3f8dfa3ff43d   35 hours ago   215MB
zabbix/zabbix-server-pgsql      alpine-6.4.13   03436618473d   35 hours ago   60.1MB
zabbix/zabbix-agent             alpine-6.4.13   5afac44ea2c8   35 hours ago   19MB
zabbix/zabbix-agent             ubuntu-6.4.13   8aef8fa8c621   35 hours ago   91.5MB
jc21/nginx-proxy-manager        latest          6219c2184f19   3 weeks ago    1.04GB
postgres                        latest          b9390dd1ea18   5 weeks ago    431MB
```

My Compose file : 

```
version: '3.7'

services:

  postgresql-server:
    image: postgres:latest
    container_name: postgresql-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4.13
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgresql-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4.13
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - postgresql-server
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ}
    ports:
      - "${ZABBIX_FRONTEND_PORT}:8080"
      - "${ZABBIX_FRONTEND_SSL_PORT}:8443"
    volumes:
      - zabbix-web-data:/usr/share/zabbix

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4.13
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-agent"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: zabbix-server
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
    privileged: true

volumes:
  postgresql-data:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data:
```

My ENV File :  

```
POSTGRES_USER=zabbix
POSTGRES_PASSWORD=zabbix
POSTGRES_DB=zabbix
PHP_TZ=America/Sao_Paulo
ZABBIX_FRONTEND_PORT=8080
ZABBIX_FRONTEND_SSL_PORT=8443
```
My access to front end : 

<img width="758" alt="image" src="https://github.com/zabbix/zabbix-docker/assets/161829704/b016056c-97d2-4795-8037-01fb2de72ce4">
