### ISSUE TITLE
Frontend version not updated when using image zabbix/zabbix-web-nginx-pgsql:7.0.2-alpine

### ISSUE THREAD

**Issue by Ermiar** [zabbix/zabbix-docker#1488]
##### SUMMARY

When updating my docker compose file to use Zabbix version 7.0.2 with alpine image (from version 7.0.0), zabbix server is marked as up to date but not the zabbix frontend. I am using the following image tag: `zabbix/zabbix-web-nginx-pgsql:7.0.2-alpine`.

##### OS / ENVIRONMENT / Used docker-compose files

Here is the used docker compose file (with sensitives informations removed). The docker compose file is launched using Portainer on a Ubuntu server. 
```
version: '3.7'

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.0.2-alpine
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: *****
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: *******
      POSTGRES_DB: zabbix
      ZBX_SOURCEIP: 0.0.0.0
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:7.0.2-alpine
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: *****
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: ****
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ}
    ports:
      - "${ZABBIX_FRONTEND_PORT}:8080"
    volumes:
      - zabbix-web-data:/usr/share/zabbix

  zabbix-agent:
    image: zabbix/zabbix-agent:7.0.2-alpine
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-server"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: zabbix-server
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
    privileged: true

volumes:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data:
``` 

##### STEPS TO REPRODUCE

Updating the docker compose to use the 7.0.2 tag on images.

##### EXPECTED RESULTS

The zabbix frontend should display the 7.0.2 version in the footer and in the system information page.
Inspecting the frontedn container environment variables also show that ZBX_VERSION is 7.0.2.

##### ACTUAL RESULTS

The displayed version is 7.0.0 and the frontend version is not marked as up to date as shown below.
![image](https://github.com/user-attachments/assets/fda0392f-fbc3-4750-ab36-60d72eb77bc1)
