### ISSUE TITLE
MIBs issue after installation of zabbix-server-pgsql:ubuntu-latest container

### ISSUE THREAD

**Issue by Landver** [zabbix/zabbix-docker#151]
My docker-compose configuration
```
version: '3'
services:
  db: # database server
    image: postgres
    volumes:
      - ../postgres/var/lib/postgresql/data:/var/lib/postgresql/data
  zabbix-server:  # The server performs the polling and trapping of data, it calculates triggers, sends notifications to users
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    volumes:
      - ../zabbix-server/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps
      - ../zabbix-server/var/lib/zabbix/mibs:/var/lib/zabbix/mibs
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=kkk
    depends_on:
      - db
  zabbix-web-apache-pgsql:  # Zabbix frontend based on Apache web-server with PostgreSQL database support
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-latest
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=kkk
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Jerusalem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - zabbix-server

```
Example of error, I get in container logs during initial creation:
```
.....
zabbix-server_1            | Cannot adopt OID in UCD-SNMP-MIB: dskTable ::= { ucdavis 9 }
zabbix-server_1            | Cannot adopt OID in UCD-SNMP-MIB: laTable ::= { ucdavis 10 }
zabbix-server_1            | Cannot adopt OID in UCD-SNMP-MIB: version ::= { ucdavis 100 }
zabbix-server_1            | Cannot adopt OID in UCD-SNMP-MIB: snmperrs ::= { ucdavis 101 }
zabbix-server_1            | Cannot adopt OID in UCD-SNMP-MIB: mrTable ::= { ucdavis 102 }
...
```
Hundreds of lines with almost the same error about 'Cannot adopt OID'

When I try to solve that problem (I took solution from here https://www.zabbix.com/forum/showthread.php?t=54295), by manually installing snmp in ubuntu container, I get error:
```
root@e8164986c3c2:/var/lib/zabbix# apt-get install snmp
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package snmp is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libsnmp30

E: Package 'snmp' has no installation candidate
```
Or another solution (I took from here https://serverfault.com/questions/440285/why-does-snmp-fail-to-use-its-own-mibs), that also doesn't work, error I get:
```
root@e8164986c3c2:/var/lib/zabbix# apt-get install snmp-mibs-downloader
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package snmp-mibs-downloader is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'snmp-mibs-downloader' has no installation candidate
```
