### ISSUE TITLE
zabbix user for zabbix-server-psql does not have CREATE role on schema "public"

### ISSUE THREAD

**Issue by wrangel** [zabbix/zabbix-docker#1525]
##### SUMMARY

No matter what I do, zabbix user for zabbix-server-psql does not have CREATE role on schema "public"

##### OS / ENVIRONMENT / Used docker-compose files
Azure Pipelines, deploying docker containers through kubernetes manifest from ACR to AKS by means of sh files.

##### STEPS TO REPRODUCE

I am using a) Azure Database for PostgreSQL - Flexible Server Version 16 b) zabbix-server-pgsql docker image as part of a kubernetes manifest, which I created from the docker-compose.yml via kompose. On my postgres server, I am having my server admin user create a specific zabbix user: 
```
CREATE USER zabbix_user WITH PASSWORD *** CREATEDB;
GRANT ALL PRIVILEGES ON SCHEMA public TO zabbix_user;
```

The relevant portion of the k8s manifest reads:
```
    spec:
      containers:
        - env:
            - name: DB_SERVER_HOST
              value: <myFqdn>
            - name: POSTGRES_DB
              value: zabbix
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: <mySecretName>
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              value: zabbix_user
```
The container is pulled and connection to Postgres Flex Server is established.

Since I did not create a db, the db confirmedly is created during the container deployment.
(it doesn't actually matter if I have user zabbix create database zabbix and even schema zabbix and users beforehand on the pgsql flex server, as stated [here](https://www.zabbix.com/documentation/current/en/manual/installation/best_practices/access_control/postgresql), the problem remains exactly the same).

##### EXPECTED RESULTS

zabbix user is allowed to create all necessary items on pgsql to run the zabbix-server-pgsql container. Container is running and in ready state.

##### ACTUAL RESULTS

```
kubectl logs -n <myNamespace> pod <my-zabbix-server-psql-pod>
```
gives me (relevant portion):
```
** Preparing Zabbix server 
** Preparing database 
** Using POSTGRES_USER variable from ENV 
** Using POSTGRES_PASSWORD variable from ENV 
******************** 
* DB_SERVER_HOST: [<myFqdn>.postgres.database.azure.com/)
* DB_SERVER_PORT: 5432 
* DB_SERVER_DBNAME: zabbix 
* DB_SERVER_SCHEMA: public 
******************** 
** Creating 'zabbix' schema in PostgreSQL 
ERROR:  permission denied for schema public 
LINE 1: CREATE TABLE role ( 
                    ^ 
ERROR:  relation "role" does not exist
```
I am not sure which "public" schema is meant here (postgres or zabbix schemas), I tried to give the zabbix user CREATE on both, to no avail
