### ISSUE TITLE
item "<hostname>:icmppingsec" became not supported: Cannot send ICMP ping packets to this host.

### ISSUE THREAD

**Issue by gianlucavagnuzzi** [zabbix/zabbix-docker#1540]
My hosts in Zabbix server are ALL mapped with FQDN.
I have 422 host.
This day i have disconnected some hosts from the network but Zabbix has not reported any problems.
This error in logs of one of those hosts:
```
  210:20241015:121708.719 item "it-ar-cam08:icmppingloss" became not supported: Cannot send ICMP ping packets to this host.
   210:20241015:121708.719 item "it-ar-cam08:icmpping" became not supported: Cannot send ICMP ping packets to this host.
   210:20241015:121708.719 item "it-ar-cam08:icmppingsec" became not supported: Cannot send ICMP ping packets to this host.
```

##### OS / ENVIRONMENT / Used docker-compose files
```
services:
  zabbix-server:
    # IMAGE: https://hub.docker.com/r/zabbix/zabbix-server-mysql/tags
    # ENV: https://github.com/zabbix/zabbix-docker/blob/7.0/env_vars/.env_srv
    image: zabbix/zabbix-server-mysql:7.0.4-alpine
    container_name: zabbix-server
    environment:
    - DB_SERVER_HOST=it-ar-mon01.graziellaluxury.local
    - MYSQL_PASSWORD=Magma.23
    - MYSQL_ROOT_PASSWORD=Magma.23
    - ZBX_CACHESIZE=256M
    - ZBX_VALUECACHESIZE=256M
    - ZBX_STARTPINGERS=32
    - /etc/timezone:/etc/timezone:ro
    volumes:
    - ./data/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
    - ./data/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
    - ./data/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
    - ./data/var/lib/zabbix/export:/var/lib/zabbix/export:rw
    - ./data/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
    - ./data/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
    - ./data/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    - ./data/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
    - ./data/snmptraps:/var/lib/zabbix/snmptraps:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - 10051:10051
    restart: unless-stopped
  nginx:
    # IMAGE: https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql/tags
    # ENV: https://github.com/zabbix/zabbix-docker/blob/7.0/env_vars/.env_db_mysql
    image: zabbix/zabbix-web-nginx-mysql:7.0.4-alpine
    container_name: nginx
    environment:
    - ZBX_SERVER_HOST=zabbix-server
    - DB_SERVER_HOST=it-ar-mon01.graziellaluxury.local
    - MYSQL_PASSWORD=Magma.23
    - MYSQL_ROOT_PASSWORD=Magma.23
    - /etc/timezone:/etc/timezone:ro
    volumes:
    - ./data/etc/ssl/nginx:/etc/ssl/nginx:ro
    - ./data/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    ports:
    - 80:8080
    - 443:8443
    restart: unless-stopped
    depends_on:
    - zabbix-server

```
