### ISSUE TITLE
Zabbix Web Interface Action List Error

### ISSUE THREAD

**Issue by alemsas** [zabbix/zabbix-docker#1565]
### Environment
- Zabbix version: 7.0.5
- Installation type: Docker (zabbix/zabbix-web-nginx-mysql:ubuntu-7.0.5)
- Database: MySQL
- Operating System: Ubuntu (Docker container)

### Problem Description
When accessing the Actions list page (`action.list`), the Zabbix web interface throws PHP errors related to undefined array keys in `actions.inc.php`. The error occurs consistently when trying to view the trigger actions page (`eventsource=0`).

### Error Messages
```
[17-Nov-2024 13:38:45 Asia/...] PHP Warning:  Undefined array key "conditiontype" in /usr/share/zabbix/include/actions.inc.php on line 119
[17-Nov-2024 13:38:45 Asia/...] PHP Warning:  Undefined array key "value" in /usr/share/zabbix/include/actions.inc.php on line 121
[17-Nov-2024 13:38:45 Asia/...] PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, false given in /usr/share/zabbix/include/actions.inc.php:277
```

### Docker Configuration
```yaml
version: "3.9"
services:
  zabbix-web:
    image: 'zabbix/zabbix-web-nginx-mysql:ubuntu-7.0.5'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./web/ssl:/etc/ssl/nginx:ro
      - ./web/modules/:/usr/share/zabbix/modules/:ro
    environment:
      - DB_SERVER_HOST=172.31.0.154
      - DB_SERVER_PORT=3306
      - ZBX_SERVER_NAME=zabbix-web-1
    env_file:
      - ./envs/.env_web
    ports:
      - "8080:8080"
    container_name: zabbix-web-1
    hostname: zbxWeb-1
    restart: unless-stopped
```

### Database Status
The actions table contains 24 configured actions, all with `eventsource=0` and `status=1`. The error occurs when trying to view any of these actions.

### Steps to Reproduce
1. Log into Zabbix web interface
2. Navigate to Configuration → Actions
3. Try to view the trigger actions list
4. Error appears and page fails to load

### What I've Tried
1. Restarting the Zabbix web container
2. Verifying database connectivity
3. Checking action configurations in the database

### Questions
1. Is this a known issue with Zabbix 7.0.5?
2. Could this be related to a database schema mismatch?
3. Are there any workarounds available while maintaining existing action configurations?

### Additional Information
The system was working correctly for whole pages insted of actions page, and the error started appearing recently. No recent configuration changes were made to the actions.
