### ISSUE TITLE
`EXPOSE_WEB_SERVER_INFO` is not correctly processed in Ubuntu image

### ISSUE THREAD

**Issue by davidwalensabfs** [zabbix/zabbix-docker#1585]
##### SUMMARY

Hello, the `EXPOSE_WEB_SERVER_INFO=off` variable is not fully working in `/zabbix/zabbix-web-apache-mysql:ubuntu-7.0.6`.

##### OS / ENVIRONMENT / Used docker-compose files

- Docker Compose version v2.29.7
- Docker version 27.3.1, build ce12230
- Debian GNU/Linux 12 (bookworm)

`docker-compose.yml` part:
```
  zabbix-web-apache-1:
    image: hid/zabbix/zabbix-web-apache-mysql:$TAG_ZABBIX
    env_file:
      - .env_zbx_dbconn
      - .env_zbxweb
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - /var/hid/zabbix-server/ssl/apache2:/etc/ssl/apache2:ro
    tmpfs: /tmp
    networks:
      - net-zabbix
    sysctls:
      - net.core.somaxconn=65535
    depends_on:
      zabbix-server-1:
        condition: service_started

```
`.env_zbxweb` part:
```
TZ=Europe/Berlin
# ZBX_SERVER_HOST=zabbix-server-1
# ZBX_SERVER_PORT=10051
ZBX_SERVER_NAME=Zabbix
# ZBX_DB_ENCRYPTION=true # Available since 5.0.0
# ZBX_DB_KEY_FILE=/run/secrets/client-key.pem # Available since 5.0.0
# ZBX_DB_CERT_FILE=/run/secrets/client-cert.pem # Available since 5.0.0
# ZBX_DB_CA_FILE=/run/secrets/root-ca.pem # Available since 5.0.0
# ZBX_DB_VERIFY_HOST=false # Available since 5.0.0
# ZBX_DB_CIPHER_LIST= # Available since 5.0.0
# ZBX_VAULT= # Available since 6.2.0
# ZBX_VAULTDBPATH=
# ZBX_VAULTURL=https://127.0.0.1:8200
# VAULT_TOKEN=
# ZBX_VAULTCERTFILE= # Available since 6.2.0
# ZBX_VAULTKEYFILE= # Available since 6.2.0
# ZBX_VAULTCACHE=false # Available since 6.2.0
# ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200/ # Available since 3.4.5
# ZBX_HISTORYSTORAGETYPES=['uint', 'dbl', 'str', 'text', 'log'] # Available since 3.4.5
# ZBX_SSO_SETTINGS=[] # Available since 5.0.0
# ZBX_ALLOW_HTTP_AUTH=true # Available since 7.0.0
ENABLE_WEB_ACCESS_LOG=true
# ZBX_MAXEXECUTIONTIME=600
# ZBX_MEMORYLIMIT=128M
# ZBX_POSTMAXSIZE=16M
# ZBX_UPLOADMAXFILESIZE=2M
# ZBX_MAXINPUTTIME=300
# ZBX_SESSION_NAME=zbx_sessionid
# Timezone one of: http://php.net/manual/en/timezones.php
PHP_TZ=Europe/Berlin
# ZBX_DENY_GUI_ACCESS=false
# ZBX_GUI_ACCESS_IP_RANGE=['127.0.0.1']
# ZBX_GUI_WARNING_MSG=Zabbix is under maintenance.
# HTTP_INDEX_FILE=index.php
EXPOSE_WEB_SERVER_INFO=off

# PHP_FPM_PM=dynamic
# PHP_FPM_PM_MAX_CHILDREN=50
# PHP_FPM_PM_START_SERVERS=5
# PHP_FPM_PM_MIN_SPARE_SERVERS=5
# PHP_FPM_PM_MAX_SPARE_SERVERS=35
# PHP_FPM_PM_MAX_REQUESTS=0
```

##### STEPS TO REPRODUCE

Set `EXPOSE_WEB_SERVER_INFO` to `off`

##### EXPECTED RESULTS

Version information should be hidden in response headers.

##### ACTUAL RESULTS

Only PHP information are held back. Apache is still talking about his version:
![image](https://github.com/user-attachments/assets/4beac5f8-6919-4f62-80c5-da7c428ec061)

Seems like the the wrong config file
https://github.com/zabbix/zabbix-docker/blob/1fd73dce189c95da9fa05b568ccb0106ac8e6bc6/Dockerfiles/web-apache-mysql/ubuntu/docker-entrypoint.sh#L27

is used for the following commands
https://github.com/zabbix/zabbix-docker/blob/1fd73dce189c95da9fa05b568ccb0106ac8e6bc6/Dockerfiles/web-apache-mysql/ubuntu/docker-entrypoint.sh#L242-L254

Correct configuration file would be `/etc/apache2/conf-enabled/security.conf` as `ServerSignature` and `ServerTokens` directives are  not a part of `apache2.conf`.
I have not checked other images, but assume it will be the same for all apache-ubuntu images.
Can also create a PR to include the `security.conf` if you want.

Thanks!
