### ISSUE TITLE
The proxy component deployed using docker in the zabbix proxy group exists and the host is not found.

### ISSUE THREAD

**Issue by xukai885** [zabbix/zabbix-docker#1587]
##### OS / ENVIRONMENT / Used docker-compose files

Zabbix Server: 146.56.193.211:10051
Zabbix Proxy:   
    192.168.2.61:10051(ZBX_HOSTNAME: zabbix-proxy-61)  
    192.168.2.62:10051(ZBX_HOSTNAME: zabbix-proxy-62)
Zabbix Agent:   
    192.168.2.63:10050(Hostname=zabbix-test-30)

### zabbix server

```bash
zabbix_server (Zabbix) 7.0.6
os: debian 12 
```
zabbix server config
```bash
root@VM-0-16-debian:~# cat /etc/zabbix/zabbix_server.conf 
LogFile=/var/log/zabbix/zabbix_server.log
LogFileSize=0
PidFile=/run/zabbix/zabbix_server.pid
SocketDir=/run/zabbix
DBHost=10.206.0.12
DBPort=5432
DBName=zabbix
DBUser=zabbix
DBPassword=xxxx
SNMPTrapperFile=/var/log/snmptrap/snmptrap.log
Timeout=4
FpingLocation=/usr/bin/fping
Fping6Location=/usr/bin/fping6
LogSlowQueries=3000
StatsAllowedIP=127.0.0.1
EnableGlobalScripts=0
```

#### zabbix-proxy-61
docker version:
```bash
[root@localhost data]# docker version
Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.44 (downgraded from 1.45)
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:32:04 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.5
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       e63daec
  Built:            Tue Mar 19 15:07:09 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

docker-compose.yml
```yaml
[root@localhost data]# cat docker-compose.yml 
```yaml
[root@localhost data]# cat docker-compose.yml 
version: '3'

services:
  zabbix-proxy-mysql:
    image: mysql:8.0.30
    restart: always
    environment:
      - MYSQL_DATABASE=zabbix_proxy
      - MYSQL_USER=zabbix-proxy
      - MYSQL_PASSWORD=xxx
      - MYSQL_ROOT_PASSWORD=xxx
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_bin
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/zabbix/zabbix-proxy/zabbix-mysql/db:/var/lib/mysql
    ports:
        - 3306:3306
  zabbix-proxy-mysql-server:
    image: zabbix/zabbix-proxy-mysql:ubuntu-7.0.6
    container_name: zabbix-proxy-mysql
    environment:
      DB_SERVER_HOST: "192.168.2.61"
      MYSQL_DATABASE: "zabbix_proxy"
      MYSQL_USER: "zabbix-proxy"
      MYSQL_PASSWORD: "xxx"
      ZBX_HOSTNAME: "zabbix-proxy-61"
      ZBX_SERVER_HOST: 146.56.193.211
      ZBX_TIMEOUT: "30"
      ZBX_CONFIGFREQUENCY: "300"
      ZBX_DATASENDERFREQUENCY: "3"
      ZBX_DEBUGLEVEL: 3
    depends_on:
      - zabbix-proxy-mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 10051:10051
    restart: always
```
#### zabbix-proxy-62
docker-compose.yml
```yaml
[root@localhost data]# cat docker-compose.yml 
version: '3'

services:
  zabbix-proxy-mysql:
    image: mysql:8.0.30
    restart: always
    environment:
      - MYSQL_DATABASE=zabbix_proxy
      - MYSQL_USER=zabbix-proxy
      - MYSQL_PASSWORD=xx
      - MYSQL_ROOT_PASSWORD=xxx
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_bin
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/zabbix/zabbix-proxy/zabbix-mysql/db:/var/lib/mysql
    ports:
        - 3306:3306
  zabbix-proxy-mysql-server:
    image: zabbix/zabbix-proxy-mysql:ubuntu-7.0.6
    container_name: zabbix-proxy-mysql
    environment:
      DB_SERVER_HOST: "192.168.2.62"
      MYSQL_DATABASE: "zabbix_proxy"
      MYSQL_USER: "zabbix-proxy"
      MYSQL_PASSWORD: "xxx"
      ZBX_HOSTNAME: "zabbix-proxy-62"
      ZBX_SERVER_HOST: 146.56.193.211
      ZBX_TIMEOUT: "30"
      ZBX_CONFIGFREQUENCY: "300"
      ZBX_DATASENDERFREQUENCY: "3"
      ZBX_DEBUGLEVEL: 3
    depends_on:
      - zabbix-proxy-mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 10051:10051
    restart: always
```

### zabbix agent
zabbix agent conf:
```bash
cat /etc/zabbix/zabbix_agent2.conf 
PidFile=/run/zabbix/zabbix_agent2.pid
LogFile=/var/log/zabbix/zabbix_agent2.log
LogFileSize=0
Server=::/0
ServerActive=192.168.2.61;192.168.2.62  # proxy addr
Hostname=zabbix-test-30
Include=/etc/zabbix/zabbix_agent2.d/*.conf
PluginSocket=/run/zabbix/agent.plugin.sock
ControlSocket=/run/zabbix/agent.sock
Include=/etc/zabbix/zabbix_agent2.d/plugins.d/*.conf
HostMetadata=agent
```
zabbix version
```bash
[root@localhost ~]# zabbix_agent2 -V
zabbix_agent2 (Zabbix) 7.0.6
```

##### EXPECTED RESULTS

After the host joins the group composed of proxy, the node status is normal.

##  ACTUAL RESULTS

First, connect the zabbix-proxy-61 and zabbix-proxy-62 nodes to the test-docker group in the zabbix web interface.
Then start the agent2 node and observe that the agent2 log has been printing the following content：
```bash
2024/12/08 04:16:58.477695 Plugin communication protocol version is 6.4.0
2024/12/08 04:16:58.477710 Zabbix Agent2 hostname: [zabbix-test-30]
2024/12/08 04:17:00.063956 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-30] not found
2024/12/08 04:17:05.079521 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-30] not found
2024/12/08 04:17:10.001655 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-30] not found
2024/12/08 04:17:15.002096 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-30] not found
2024/12/08 04:17:20.001797 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-30] not found
....
2024/12/08 04:19:55.001860 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-30] not found
2024/12/08 04:20:00.001615 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-30] not found
2024/12/08 04:20:05.001580 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-30] not found
2024/12/08 04:20:10.001717 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-30] not found
```

This is the log of zabbix-proxy-61
```bash
   193:20241208:041700.053 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   217:20241208:041701.175 enabling Zabbix agent checks on host "zabbix-test-25": interface became available
   192:20241208:041709.991 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   189:20241208:041710.821 received configuration data from server at "146.56.193.211", datalen 445
   193:20241208:041719.991 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   189:20241208:041720.961 received configuration data from server at "146.56.193.211", datalen 13315
   192:20241208:041729.991 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   190:20241208:041739.991 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   193:20241208:041749.992 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   191:20241208:041759.991 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
....
   194:20241208:042019.992 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   193:20241208:042029.992 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   191:20241208:042039.993 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
```
This is the log of zabbix-proxy-62
```bash
207:20241208:041705.077 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   207:20241208:041714.999 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   204:20241208:041715.638 received configuration data from server at "146.56.193.211", datalen 445
   207:20241208:041725.000 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   207:20241208:041735.001 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   207:20241208:041744.999 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   207:20241208:041754.999 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   207:20241208:041804.999 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   207:20241208:041815.000 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   206:20241208:041825.000 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
....
   205:20241208:042055.000 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   209:20241208:042105.000 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   207:20241208:042115.001 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   208:20241208:042125.063 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   208:20241208:042135.000 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
```
This is the log of zabbix server
```bash
 14800:20241208:171710.823 sending configuration data to proxy "zabbix-proxy-61" at "124.112.158.4", datalen 445, bytes 239 with compression ratio 1.9
 14801:20241208:171715.632 sending configuration data to proxy "zabbix-proxy-62" at "124.112.158.4", datalen 445, bytes 239 with compression ratio 1.9
 14801:20241208:171720.962 sending configuration data to proxy "zabbix-proxy-61" at "124.112.158.4", datalen 13315, bytes 3040 with compression ratio 4.
```

After waiting for more than ten minutes, I checked that the host status of agent zabbix-test-30 on zabbix web is Unknown.

Status after adding host
<img width="1737" alt="截屏2024-12-08 17 26 30" src="https://github.com/user-attachments/assets/90c569a5-69c4-4aaf-8086-b3648626e67c">

zabbix proxy status is OK
<img width="791" alt="截屏2024-12-08 17 26 52" src="https://github.com/user-attachments/assets/32f09ce3-e873-4b69-8e49-d3a69ff58846">

zabbix-proxy-61 configuration
<img width="1744" alt="截屏2024-12-08 17 26 46" src="https://github.com/user-attachments/assets/aa843ca1-99f2-4915-8fd1-5b9ba4b8e86c">

**Comment by dotneft** [comment]
Please share abnormal proxy logs.

**Comment by dotneft** [comment]
do you use different DB for both proxies?

**Comment by xukai885** [comment]
1.The two proxy nodes use different mysql database nodes and dbname

#### Now I configured the host node name as "zabbix-test-25"
2.The logs of the proxy-1 proxy nodes are as follows: 
```bash
[root@localhost data]# docker logs -f --tail 20 2b
  206:20241208:031319.994 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   202:20241208:031322.157 received configuration data from server at "146.56.193.211", datalen 13315
   203:20241208:031329.994 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   204:20241208:031339.994 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   207:20241208:031349.994 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   205:20241208:031359.994 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   206:20241208:031409.993 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   203:20241208:031419.994 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   204:20241208:031429.993 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
```
proxy-02 logs:
```bash
[root@localhost data]# docker logs -f --tail 20 dd
   189:20241208:031311.861 received configuration data from server at "146.56.193.211", datalen 445
   193:20241208:031315.002 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   191:20241208:031325.003 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   192:20241208:031335.002 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   193:20241208:031345.002 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   194:20241208:031355.002 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   191:20241208:031405.001 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   192:20241208:031415.001 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
   193:20241208:031425.001 cannot send list of active checks to "192.168.2.63": host [zabbix-test-25] not found
```
3. After waiting for about ten minutes, the agent status on zabbix web is Unknown..
<img width="1730" alt="截屏2024-12-08 16 20 57" src="https://github.com/user-attachments/assets/287fa20c-ecca-44d6-9439-d08099bbebc3">

4.When I choose to restart the proxy node
```bash
[root@localhost data]# docker-compose restart 
WARN[0000] /data/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Restarting 2/2
 ✔ Container zabbix-proxy-mysql         Started                                                                                                    2.9s 
 ✔ Container data-zabbix-proxy-mysql-1  Started   
```
5.Another proxy node log information
```bash
2024/12/08 03:21:15.002043 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-25] not found
2024/12/08 03:21:20.001656 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-25] not found
2024/12/08 03:21:25.002619 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-25] not found
2024/12/08 03:21:30.002284 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-25] not found
2024/12/08 03:21:35.002172 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-25] not found
2024/12/08 03:21:40.069208 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-25] not found
2024/12/08 03:21:45.053215 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-25] not found
2024/12/08 03:21:50.002294 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-25] not found
2024/12/08 03:21:55.002007 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-25] not found
2024/12/08 03:22:00.001644 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-25] not found
2024/12/08 03:22:05.002047 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-25] not found
2024/12/08 03:22:10.001709 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-25] not found
2024/12/08 03:22:15.002093 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-25] not found
2024/12/08 03:22:20.233094 [101] cannot receive data from [192.168.2.61:10051]: Cannot read message: 'read tcp 192.168.2.63:44515->192.168.2.61:10051: read: connection reset by peer'
2024/12/08 03:22:20.233131 [101] connection closed
2024/12/08 03:22:20.233143 [101] active check configuration update from host [zabbix-test-25] started to fail
2024/12/08 03:22:25.002059 [101] active check configuration update from [192.168.2.62:10051] is working again
2024/12/08 03:22:25.002103 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-25] not found
```
6.At this time, the node Available is displayed on zabbix web.
<img width="1730" alt="截屏2024-12-08 16 25 43" src="https://github.com/user-attachments/assets/53019a06-0668-4126-9eb9-5493ffd3bf66">

**Comment by dotneft** [comment]
why IP is different each time for the same host:
```
2024/12/08 03:22:05.002047 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-25] not found
2024/12/08 03:22:10.001709 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-25] not found
2024/12/08 03:22:15.002093 [101] no active checks on server [192.168.2.62:10051]: host [zabbix-test-25] not found
```

**Comment by xukai885** [comment]
Sorry, this is the log on the agent. 😢

**Comment by xukai885** [comment]
This is the log information of the node after restarting proxy-1
```bash
   200:20241208:032228.057 thread started [discovery worker #5]
   200:20241208:032228.058 thread started [discovery worker #1]
   200:20241208:032228.058 thread started [discovery worker #2]
   200:20241208:032228.058 thread started [discovery worker #3]
   200:20241208:032228.058 thread started [discovery worker #4]
   217:20241208:032228.175 enabling Zabbix agent checks on host "zabbix-test-25": interface became available
   210:20241208:032232.165 forced reloading of the snmp cache on [poller #4]
   211:20241208:032232.167 forced reloading of the snmp cache on [poller #5]
   212:20241208:032232.167 forced reloading of the snmp cache on [unreachable poller #1]
   207:20241208:032232.192 forced reloading of the snmp cache on [poller #1]
   208:20241208:032232.196 forced reloading of the snmp cache on [poller #2]
   209:20241208:032232.205 forced reloading of the snmp cache on [poller #3]
```

**Comment by dotneft** [comment]
So please reproduce the issue, and clearly describe your steps (without restart) + specify all IP addresses of all components which communicate with each other (Zabbix server, Zabbix proxies, Zabbix agent)

**Comment by xukai885** [comment]
Yes, I have updated the detailed description

**Comment by dotneft** [comment]
Thank you! Do you have messages like:
```
received configuration data from server at
```
during such 10 minutes on proxies side? Looks like logs from proxy is not full.

**Comment by xukai885** [comment]
Yes, proxy outputs 
``` 189:20241208:031311.861 received configuration data from server at "146.56.193.211", datalen 445```
proxy the intermediate logs of the components all output something like 
```2024/12/08 04:20:00.001615 [101] no active checks on server [192.168.2.61:10051]: host [zabbix-test-30] not found```
So I omitted it here

**Comment by dotneft** [comment]
When you see that host is assigned to some proxy from proxy group, do you see that datalen is changed on proxy side logs after 1-2 minutes?

**Comment by dotneft** [comment]
Sorry, I can not reproduce that situation with agent2 7.0.6:
```
2024/12/09 14:08:26.849824 Starting Zabbix Agent 2 (7.0.6)
2024/12/09 14:08:26.851213 OpenSSL library (OpenSSL 3.3.2 3 Sep 2024) initialized
...
2024/12/09 14:09:24.007047 [101] no active checks on server [172.16.239.4:10051]: host [c321ad3d44f6] not found
2024/12/09 14:09:29.006942 [101] no active checks on server [172.16.239.4:10051]: host [c321ad3d44f6] not found
2024/12/09 14:09:34.134832 check 'system.sw.packages.get' is not supported: Cannot obtain package information.
```
```
$ cat /etc/zabbix/zabbix_agent2.conf | grep -E ^Server
ServerActive=172.16.239.4;172.16.239.5
```
Please check table "hosts" on both proxies. Do you see the host:
```
select * from hosts where host = 'zabbix-test-30';
```

**Comment by xukai885** [comment]
Yes, I checked that there is "zabbix-test-30" in the mysql table "hosts" on the proxy node.
```
mysql> select * from hosts;
*************************** 2. row ***************************
            hostid: 10667
           proxyid: NULL
              host: zabbix-test-30
            status: 0
     ipmi_authtype: -1
    ipmi_privilege: 2
     ipmi_username: 
     ipmi_password: 
     maintenanceid: NULL
maintenance_status: 0
  maintenance_type: 0
  maintenance_from: 0
              name: zabbix-test-30
             flags: 0
        templateid: NULL
       description: 
       tls_connect: 1
        tls_accept: 1
        tls_issuer: 
       tls_subject: 
  tls_psk_identity: 
           tls_psk: 
          discover: 0
 custom_interfaces: 0
              uuid: 
        name_upper: 
       vendor_name: 
    vendor_version: 
     proxy_groupid: NULL
      monitored_by: 0
```
20241209:205349.076  I added agent ，There are two pieces of datalen information at the back
```
   194:20241209:205349.076 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   194:20241209:205359.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   189:20241209:205405.083 received configuration data from server at "146.56.193.211", datalen 444
   194:20241209:205409.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   189:20241209:205415.319 received configuration data from server at "146.56.193.211", datalen 13314
   194:20241209:205419.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   192:20241209:205429.008 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   194:20241209:205439.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   192:20241209:205449.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   194:20241209:205459.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   193:20241209:205509.008 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   192:20241209:205519.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   194:20241209:205529.008 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   193:20241209:205539.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   191:20241209:205549.008 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   190:20241209:205559.076 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   190:20241209:205609.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   192:20241209:205619.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   194:20241209:205629.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   193:20241209:205639.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   191:20241209:205649.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   190:20241209:205659.008 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   192:20241209:205709.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   194:20241209:205719.008 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   193:20241209:205729.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   191:20241209:205739.008 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   190:20241209:205749.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
   192:20241209:205759.007 cannot send list of active checks to "192.168.2.63": host [zabbix-test-30] not found
```
