### ISSUE TITLE
Failed to accept an incoming zabbix-agent connection from same host as the zabbix-proxy container is running

### ISSUE THREAD

**Issue by pthoelken** [zabbix/zabbix-docker#1595]
Currently I'm runnning the zabbix proxy server as a container on a docker host. So far so good. All works fine, and all other hosts from the network can connect to the proxy server (and finally to the monitoring server). 

Except the docker-server himself. At the docker server (Debian latest release) is a native Zabbix Agent 7.2 installed. The Zabbix Proxy Container is still 7.0.2 (bc compability to the server). 

When I start the native agent on the docker server I've got the error message down below: 
`2024/12/26 09:21:15.078204 failed to accept an incoming connection: connection from "172.24.0.2" rejected, allowed hosts: "10.1.46.236"`

Then I connect the docker hosts native zabbix agend to the monitoring server directly, all is fine. 

Here is the docker-compose file from the zabbix-proxy
```
services:
  Zabbix-Proxy:
    container_name: zapr01
    restart: always
    image: zabbix/zabbix-proxy-sqlite3:7.0.7-alpine
    environment:
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKIDENTITY: psk-autoregister-id
      ZBX_HOSTNAME: zapr01
      ZBX_SERVER_HOST: xxx.xxx.com
      ZBX_TLSPSKFILE: /var/lib/zabbix/enc/zabbix_agentd.psk
      ZBX_SERVER_PORT: 10051
    volumes:
      - ./data/zabbix_agentd.psk:/var/lib/zabbix/enc/zabbix_agentd.psk
      - prxdatabase:/var/lib/zabbix/db_data
    ports:
      - 0.0.0.0:10051:10051

volumes:
  prxdatabase:
```

and here the config file from the docker host native agent ... nothing special as I think.

```
TLSConnect=psk
TLSAccept=psk
TLSPSKFile=/etc/zabbix/authentication.psk
TLSPSKIdentity=psk-autoregister-id
Server=10.1.46.236
ServerActive=10.1.46.236
Hostname=docker01
HostMetadata=AgentRegister
```

**Comment by dotneft** [comment]
It happens because different routes for all hosts outside of server (with Zabbix proxy running in docker) and inside of the server. Just change allowed host to 172.24.0.2.

**Comment by pthoelken** [comment]
> It happens because different routes for all hosts outside of server (with Zabbix proxy running in docker) and inside of the server. Just change allowed host to 172.24.0.2.

What is the right parameter for the docker compose and is the zabbix-agent.config correct with "10.1.46.236" or should I use 127.0.0.1?

**Comment by dotneft** [comment]
You should use interface IP address where from Zabbix server/proxy trying to connect to agent. Everything depends on your infrastructure. The simplest way to use 172.24.0.2 or expose Zabbix agent port to host and use host IP.

**Comment by pthoelken** [comment]
Thanks for the hint. This is my final compose file and it works like charm. 

```
services:
  Zabbix-Proxy:
    container_name: zapr01
    restart: always
    image: zabbix/zabbix-proxy-sqlite3:7.0.7-alpine
    environment:
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKIDENTITY: pskXXX
      ZBX_HOSTNAME: zapr01
      ZBX_SERVER_HOST: monitor.XXX.com
      ZBX_TLSPSKFILE: /var/lib/zabbix/enc/zabbix_agentd.psk
      ZBX_SERVER_PORT: 10051
      ZBX_PASSIVESERVERS: 10.1.46.0/24,172.24.0.0/24
      ZBX_ACTIVESERVERS: 10.1.46.0/24,172.24.0.0/24
    volumes:
      - ./data/zabbix_agentd.psk:/var/lib/zabbix/enc/zabbix_agentd.psk
      - prxdatabase:/var/lib/zabbix/db_data
    ports:
      - 0.0.0.0:10051:10051
    networks:
      static-network:
        ipv4_address: 172.20.128.2

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  prxdatabase:
```

and my agent config on the same host

```
TLSConnect=psk
TLSAccept=psk
TLSPSKFile=/etc/zabbix/authentication.psk
TLSPSKIdentity=pskXXX
Server=172.20.128.2
ServerActive=172.20.128.2
Hostname=docker01
HostMetadata=AgentRegister
```
