### ISSUE TITLE
Issue with socket setup on 7.2.2

### ISSUE THREAD

**Issue by paskal** [zabbix/zabbix-docker#1628]
Hello there!

Log from zabbix-server container:
```
zabbix-server  | ** Preparing Zabbix server
zabbix-server  | ** Preparing database
zabbix-server  | ** Using MYSQL_USER variable from ENV
zabbix-server  | ** Using MYSQL_PASSWORD variable from ENV
zabbix-server  | ** Using MYSQL_ROOT_PASSWORD variable from ENV
zabbix-server  | ********************
zabbix-server  | * DB_SERVER_SOCKET: /var/run/mysqld/mysqld.sock
zabbix-server  | * DB_SERVER_DBNAME: zabbix
zabbix-server  | ********************
zabbix-server  | ** Creating 'zabbix' user in MySQL database
zabbix-server  | ** Database 'zabbix' already exists. Please be careful with database COLLATE!
zabbix-server  | ** Table 'zabbix.dbversion' already exists.
zabbix-server  | zabbix_server [1]: wrong value of "DBPort" in config file "/etc/zabbix/zabbix_server_db.conf", line 66
```

docker-compose.yml:
```
  zabbix-server:
    image: ghcr.io/paskal/zabbix-server-mysql:latest
    restart: always

    # MYSQL_DATABASE, MYSQL_PASSWORD, MYSQL_USER
    env_file: private/environment/mysql.env
    volumes:
      - ./config/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      # MySQL socket to prevent transferring data through TCP
      - ./private/mysqld:/var/run/mysqld
    environment:
      - TZ=UTC
      - DB_SERVER_SOCKET=/var/run/mysqld/mysqld.sock
      - ZBX_TIMEOUT=30
    ports:
      - "10051:10051"
```

My Dockerfile:

```
FROM zabbix/zabbix-server-mysql:latest
# root to allow installation of the packages
USER 0
RUN apk add --update --no-cache sudo libxml2-utils openssl coreutils
# restore original user
USER 1997
```

`7.2.1-alpine` is the last tag which works with my config, so the problem was introduced somewhere here: https://github.com/zabbix/zabbix-docker/compare/7.2.1...7.2.2
