### ISSUE TITLE
Can not generate the schedule report in zabbix 7.2.2

### ISSUE THREAD

**Issue by jhramadhania** [zabbix/zabbix-docker#1647]
I always get error timeout in the schedule report test
```
Report generating test failed.
Cannot fetch data.: dashboard failed to get ready, url: 'http://domainname.com:10053/report//zabbix.php?action=dashboard.print&dashboardid=369&from=2025-02-24%2000%3A00%3A00&to=2025-02-25%2000%3A00%3A00': waiting for function failed: timeout.
```

my compose looks like this : 
```
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: on-failure
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: password
      ZBX_HOSTNAME: domainname.com
      ZBX_STARTREPORTWRITERS: "1"
      ZBX_WEBSERVICEURL: http://domainname.com:10053/report
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
    depends_on:
      - postgres
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    restart: on-failure
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: password
      PHP_TZ: Asia/Jakarta
      #ZBX_WEBSERVICE_URL: https://domainname.com:10053
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

  zabbix-web-service:
    image: zabbix/zabbix-web-service:latest
    container_name: zabbix-web-service
    restart: on-failure
    environment:
      ZBX_ALLOWEDIP: "0.0.0.0/0"
      ZBX_TIMEOUT: "30"
    ports:
      - "10053:10053"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

volumes:
  zabbix-db-data:
  zabbix-server-data:
  data:
  config:

networks:
  zabbix-network:
    driver: bridge
```

I wonder is there any other problem? is it related to https://support.zabbix.com/browse/ZBX-25152 ?

<img width="782" alt="Image" src="https://github.com/user-attachments/assets/16a22de7-6cae-4df9-8e59-aec8bd9b3138" />
