### ISSUE TITLE
Zabbix server problem - unable to select configuration

### ISSUE THREAD

**Issue by crocandr** [zabbix/zabbix-docker#168]
Hi!

I got a "Database error, Unable to select configuration" error message on the web page with zabbix-server-mysql container in docker.

I see an error on the `docker logs` output:
`INFO gave up: zabbix-server entered FATAL state, too many start retries too quickly`
and I see this in the zabbix-server container when I try to start the entrypoint script manually:
`cannot use database "zabbix": Zabbix server cannot work with a Zabbix proxy database`

The docker logs output:
```
docker logs b41
2017-11-02 13:26:23,206 INFO exited: zabbix-server (exit status 1; not expected)
2017-11-02 13:26:26,211 INFO spawned: 'zabbix-server' with pid 137
2017-11-02 13:26:26,211 INFO spawned: 'zabbix-server' with pid 137
Starting Zabbix Server. Zabbix 3.4.3 (revision 73588).
Press Ctrl+C to exit.

   137:20171102:132626.218 Starting Zabbix Server. Zabbix 3.4.3 (revision 73588).
   137:20171102:132626.218 ****** Enabled features ******
   137:20171102:132626.219 SNMP monitoring:           YES
   137:20171102:132626.219 IPMI monitoring:           YES
   137:20171102:132626.219 Web monitoring:            YES
   137:20171102:132626.219 VMware monitoring:         YES
   137:20171102:132626.219 SMTP authentication:       YES
   137:20171102:132626.219 Jabber notifications:      YES
   137:20171102:132626.219 Ez Texting notifications:  YES
   137:20171102:132626.219 ODBC:                      YES
   137:20171102:132626.219 SSH2 support:              YES
   137:20171102:132626.219 IPv6 support:              YES
   137:20171102:132626.219 TLS support:               YES
   137:20171102:132626.219 ******************************
   137:20171102:132626.219 using configuration file: /etc/zabbix/zabbix_server.conf
   137:20171102:132626.221 cannot use database "zabbix": Zabbix server cannot work with a Zabbix proxy database
2017-11-02 13:26:26,222 INFO exited: zabbix-server (exit status 1; not expected)
2017-11-02 13:26:26,222 INFO exited: zabbix-server (exit status 1; not expected)
2017-11-02 13:26:27,223 INFO gave up: zabbix-server entered FATAL state, too many start retries too quickly
2017-11-02 13:26:27,223 INFO gave up: zabbix-server entered FATAL state, too many start retries too quickly
```

The output when I try to start Zabbix run script manually:
```
zabbix@b410320eeb20:/var/lib/zabbix$ zabbix_server -c /etc/zabbix/zabbix_server.conf -f
Starting Zabbix Server. Zabbix 3.4.3 (revision 73588).
Press Ctrl+C to exit.

   141:20171102:131645.862 Starting Zabbix Server. Zabbix 3.4.3 (revision 73588).
   141:20171102:131645.862 ****** Enabled features ******
   141:20171102:131645.862 SNMP monitoring:           YES
   141:20171102:131645.862 IPMI monitoring:           YES
   141:20171102:131645.862 Web monitoring:            YES
   141:20171102:131645.862 VMware monitoring:         YES
   141:20171102:131645.862 SMTP authentication:       YES
   141:20171102:131645.862 Jabber notifications:      YES
   141:20171102:131645.862 Ez Texting notifications:  YES
   141:20171102:131645.862 ODBC:                      YES
   141:20171102:131645.862 SSH2 support:              YES
   141:20171102:131645.862 IPv6 support:              YES
   141:20171102:131645.862 TLS support:               YES
   141:20171102:131645.862 ******************************
   141:20171102:131645.862 using configuration file: /etc/zabbix/zabbix_server.conf
   141:20171102:131645.864 cannot use database "zabbix": Zabbix server cannot work with a Zabbix proxy database
```

My `docker-compose.yml` file:
```
version: '3'

services:
  zabbix-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Secret1"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
    volumes:
      - './db/:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
    restart: always
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-3.4-latest
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      ZBX_CACHESIZE: "128M"
      ZBX_VALUECACHESIZE: "128M"
    volumes:
      - './xtrafiles:/srv/xtrafiles'
      - './alertscripts:/usr/lib/zabbix/alertscripts'
      - '/etc/localtime:/etc/localtime:ro'
    depends_on:
      - zabbix-db
    ports:
      - '10051:10051'
    restart: always
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-latest
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      ZBX_SERVER_HOST: "zabbix-server"
      TZ: "Europe/Budapest"
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '80:80'
      - '443:443'
    restart: always
```

I think this is a bug.

Maybe the base data is not imported:
https://www.zabbix.com/forum/showthread.php?t=16778

```
root@b410320eeb20:/var/lib/zabbix# mysql -u $MYSQL_USER --password=$MYSQL_PASSWORD -h $DB_SERVER_HOST $MYSQL_DATABASE
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 125
Server version: 5.7.20 MySQL Community Server (GPL)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select * from users;
Empty set (0.00 sec)

mysql>
````

I think this is a bug in the new server container.

Can You fix it?

**Comment by dotneft** [comment]
try to drop db and execute compose file again, then attach full logs from zabbix server image.

**Comment by crocandr** [comment]
I tried to delete everything, but not works.
I've run this compose file on an empty folder.

I've found an another error when I tried import the data manually:
```
root@b410320eeb20:/var/lib/zabbix# mysql -u $MYSQL_USER --password=$MYSQL_PASSWORD -h $DB_SERVER_HOST $MYSQL_DATABASE < /usr/share/doc/zabbix-server-mysql/data.sql
ERROR 1366 (HY000) at line 1312: Incorrect string value: '\xD0\xA1' for column 'units' at row 1
root@b410320eeb20:/var/lib/zabbix# locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by dotneft** [comment]
Please check https://github.com/zabbix/zabbix-docker/issues/130#issuecomment-325371791

**Comment by crocandr** [comment]
Thank you very much for the quick reply!

Now works fine with this `docker-compose.yml`
```
version: '3'

services:
  zabbix-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Secret"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
    volumes:
      - './db/:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
    restart: always
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-3.4-latest
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      ZBX_CACHESIZE: "128M"
      ZBX_VALUECACHESIZE: "128M"
    volumes:
      - './xtrafiles:/srv/xtrafiles'
      - './alertscripts:/usr/lib/zabbix/alertscripts'
      - '/etc/localtime:/etc/localtime:ro'
    depends_on:
      - zabbix-db
    ports:
      - '10051:10051'
    restart: always
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-latest
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      ZBX_SERVER_HOST: "zabbix-server"
      TZ: "Europe/Budapest"
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '80:80'
      - '443:443'
    restart: always
```

The character set configuration of the MySQL helped for me! Thank you!
