### ISSUE TITLE
curl, wget with ssl support

### ISSUE THREAD

**Issue by Raivon** [zabbix/zabbix-docker#173]
Could you add curl or wget with ssl support in zabbix-server-mysql:alpine-3.4 "latest" and "local" images, please? I think many peoples use it to work with APIs in alert scripts.

**Comment by ronnicek** [comment]
See #149. Best solution is create your own Dockerfile.. something like this:

```
FROM zabbix-server-mysql:alpine-3.4-latest

RUN apk --update add curl openssl bc python-requests && rm -rf /var/cache/apk/*

CMD ["/run_zabbix_component.sh", "server", "mysql"]
```

Then just run `docker build -t mynick/myownamazingzabbix .`

But be also aware of this bug #141 (do not know if it´s already solved or not :))

**Comment by Raivon** [comment]
Thanks. I use another way. I modify original Dockerfile and build my own local image. But your solution is better.

**Comment by maximkrusina** [comment]
Hi ronnicek, please can You tell us a little bit about 3rd line, the CMD? I just spent a lot of time studying all the Zabbix Dockerfiles and Dockercompose files, but I really didn’t find out how to make it work. Generally, there must be specified which command to run iside the container, I understand that, but cannot make it run for me. Thanx for help! (and happy Easter :)

**Comment by ronnicek** [comment]
Hi @maximkrusina,

best way is look in actual [Dockerfile](https://github.com/zabbix/zabbix-docker/blob/3.4/server-mysql/alpine/Dockerfile) and just use last line instead of this which I have there. Looks like there were some changes and they are not using it like I was using it before (and actually, I am not using last line at all and it also works).

My working solution (it´s based on ubuntu image):
```
# we need this for telegram messages :)

FROM zabbix/zabbix-server-pgsql:ubuntu-3.4-latest

RUN apt update && apt install -y openssl bc python-requests && rm -rf /var/lib/apt/lists/*
```

Then in my docker-compose.yml I have following:
```
version: '2'
services:
 zabbix-server:
  container_name: zabbix-server
  # image: zabbix/zabbix-server-pgsql:ubuntu-3.4-latest
  build: /opt/images/zabbix/zabbix-server/
  image: ronnicek/zabbix-server-pgsql
  expose:
   - "10051"
```

Do not hesistate to ask anything more if you want / do not understand from my description. Happy Easter to you too! :)
