### ISSUE TITLE
zabbix-agent and host mode

### ISSUE THREAD

**Issue by mattberther** [zabbix/zabbix-docker#176]
I have an external zabbix server that I would like to get an agent container talking to. My docker-compose.yml is pretty simple:

``` yaml
version: '2'

services:
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-latest
    privileged: true
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=hostname
      - ZBX_SERVER_HOST=192.168.1.5
```

This ends up not working -- the error message in the log is this:

```
56:20171216:074446.024 failed to accept an incoming connection: connection from "172.18.0.1" rejected, allowed hosts: "192.168.1.5"
```

If I update the docker-compose to specify `network_mode: host`, then all works fine. However, I would prefer not to run in host mode. Do you know why the container seems to be getting the IP of the docker network, rather than the actual source IP of the server (which is 192.168.1.5)?

Thanks!
