### ISSUE TITLE
Does the Zabbix-Agentd Image support filesystem and proccesses monitoring?

### ISSUE THREAD

**Issue by gcavalcante8808** [zabbix/zabbix-docker#177]
Hello Folks,

Does the agentd image support fs and process monitoring? I tried to start mine agentd with the following configuration:

```
version: '2'
volumes:
  conf:
  scripts:
  modules:

services:
  agent:
    container_name: zabbix-agentd
    image: zabbix/zabbix-agent:ubuntu-3.4-latest
    environment:
     - ZBX_HOSTNAME=bla
     - ZBX_SERVER_HOST=server
     - ZBX_ACTIVESERVERS=server
    restart: always
    privileged: true
    volumes:
     - conf:/etc/zabbix/zabbix_agentd.d
     - modules:/var/lib/zabbix/modules:ro
     - scripts:/var/lib/zabbix/externalscripts:ro
```
When we try to check at vfs.fs.discovery with `docker exec -it zabbix-agentd zabbix-agentd -t vfs.fs.discovery`, the following result is returned:

```
[s|{"data":[{"{#FSNAME}":"/","{#FSTYPE}":"overlay"},{"{#FSNAME}":"/proc","{#FSTYPE}":"proc"},{"{#FSNAME}":"/dev","{#FSTYPE}":"tmpfs"},{"{#FSNAME}":"/dev/pts","{#FSTYPE}":"devpts"},{"{#FSNAME}":"/sys","{#FSTYPE}":"sysfs"},{"{#FSNAME}":"/sys/fs/cgroup","{#FSTYPE}":"tmpfs"},{"{#FSNAME}":"/sys/fs/cgroup/systemd","{#FSTYPE}":"cgroup"},{"{#FSNAME}":"/sys/fs/cgroup/net_cls,net_prio","{#FSTYPE}":"cgroup"},{"{#FSNAME}":"/sys/fs/cgroup/blkio","{#FSTYPE}":"cgroup"},{"{#FSNAME}":"/sys/fs/cgroup/cpu,cpuacct","{#FSTYPE}":"cgroup"},{"{#FSNAME}":"/sys/fs/cgroup/perf_event","{#FSTYPE}":"cgroup"},{"{#FSNAME}":"/sys/fs/cgroup/memory","{#FSTYPE}":"cgroup"},{"{#FSNAME}":"/sys/fs/cgroup/pids","{#FSTYPE}":"cgroup"},{"{#FSNAME}":"/sys/fs/cgroup/cpuset","{#FSTYPE}":"cgroup"},{"{#FSNAME}":"/sys/fs/cgroup/devices","{#FSTYPE}":"cgroup"},{"{#FSNAME}":"/sys/fs/cgroup/freezer","{#FSTYPE}":"cgroup"},{"{#FSNAME}":"/dev/mqueue","{#FSTYPE}":"mqueue"},{"{#FSNAME}":"/etc/hosts","{#FSTYPE}":"ext4"},{"{#FSNAME}":"/dev/shm","{#FSTYPE}":"tmpfs"},{"{#FSNAME}":"/etc/resolv.conf","{#FSTYPE}":"ext4"},{"{#FSNAME}":"/etc/hostname","{#FSTYPE}":"ext4"},{"{#FSNAME}":"/etc/zabbix/zabbix_agentd.d","{#FSTYPE}":"nfs4"},{"{#FSNAME}":"/var/lib/zabbix/scripts","{#FSTYPE}":"nfs4"},{"{#FSNAME}":"/var/lib/zabbix/enc","{#FSTYPE}":"ext4"},{"{#FSNAME}":"/var/lib/zabbix/modules","{#FSTYPE}":"nfs4"}]}]
```

Which doesn't correspond to the current host's fs ...

Thanks in Advance.

Just for note: We are in the proccess to migrate into the official zabbix image, and for now, we use the images available at https://github.com/gcavalcante8808/docker-zabbix; in that case, I just used proot to mount the container agentd into the host fs and everything worked.
