### ISSUE TITLE
Unable to start container with external database

### ISSUE THREAD

**Issue by liogate** [zabbix/zabbix-docker#359]
I'm trying to start the container in a specific network but the mysql or postgres instance is unreachable.
```
MySQL is not available. Waiting for 5 sec.
```
Even if I can ping the host in the container, zabbix can't establish the connection with the database. Do you have a solution without linking the host with a database container ?
I already had a look at this issue #350

**Comment by Rotox** [comment]
I am also having this same issue all of a sudden. Was working fine  until just recently. Before the looping MySQL error message I see this:

[Warning] Can't create test file /var/lib/mysql/zabbixserver.lower-test,
/usr/bin/mysqld: Can't change dir to '/var/lib/mysql/' (Errcode: 116 "Stale file handle")

**Comment by dotneft** [comment]
Where is such error do you see? MySQL docker image instance or ZABBIX appliance?

**Comment by liogate** [comment]
I'm not using a `docker-compose.yml`, but more like this:
```
docker run -d --name prod-zabbix -e MYSQL_DATABASE=db_name -e MYSQL_USER=my_user -e MYSQL_PASSWORD=my_password -e DB_SERVER_HOST=hostname_or_ip_of_the_mysql_container_inside_the_same_network --network="my_custom_network" zabbix/zabbix-web-nginx-mysql:latest
```
Ports are not published here because the service is used inside the network.

**Comment by dotneft** [comment]
I'm pretty sure that error like "Can't change dir to '/var/lib/mysql/'" impossible to see in zabbix/zabbix-web-nginx-mysql. Where do you see the error message?

**Comment by sebklaus** [comment]
I have the same problem.
Only the first container that comes up connects to the DB.

The other one comes up with `MySQL is not available. Waiting for 5 sec.`
MariaDB: 10.1 (latest)

'zabbix' database exists and this stack has been working fine until Docker CE (18.06.1) update and host restart today.

I'm using docker compose:
```
version: '2'
services:
  server:
    image: "zabbix/zabbix-server-mysql:latest"
    container_name: zabbix_server
    networks:
      macvlan:
        ipv4_address: [REMOVED]
      mariadb:
      zabbix:
    restart: always
    volumes:
      - zabbix_data:/usr/lib/zabbix
      - zabbix_data:/usr/lib/zabbix/alertscripts
      - zabbix_data:/usr/lib/zabbix/externalscripts
      - zabbix_config:/var/lib/zabbix
      - zabbix_config:/var/lib/zabbix/enc
      - zabbix_config:/var/lib/zabbix/mibs
      - zabbix_config:/var/lib/zabbix/modules
      - zabbix_config:/var/lib/zabbix/snmptraps
      - zabbix_config:/var/lib/zabbix/ssh_keys
      - zabbix_config:/var/lib/zabbix/ssl/keys
      - zabbix_config:/var/lib/zabbix/ssl/ssl_ca
      - zabbix_config:/var/lib/zabbix/ssl/certs
    environment:
      DB_SERVER_HOST: mariadb
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: [REMOVED]
      ZBX_CACHESIZE: "128M"
    ports:
      - "10050:10050"
  web:
    image: "zabbix/zabbix-web-nginx-mysql:latest"
    container_name: zabbix_web
    networks:
      - mariadb
      - zabbix
    restart: always
    volumes:
      - zabbix_web:/etc/ssl/nginx
    environment:
      DB_SERVER_HOST: mariadb
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: [REMOVED]
      ZBX_SERVER_HOST: zabbix_server
      PHP_TZ: "Australia/Perth"
    ports:
      - "10380:80"
networks:
  macvlan:
    external:
      name: macvlan
  mariadb:
    external:
      name: mariadb
  zabbix:
    external:
      name: zabbix
```
Any hints would be much appreciated.
