### ISSUE TITLE
Database error Unable to select configuration.

### ISSUE THREAD

**Issue by zhitnik-hiteklab** [zabbix/zabbix-docker#441]
День добрый!

Делаю простейшую установку zabbix на docker контейнерах. Имеем docker-compose.yml
```yml
version: '3.5'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-4.0-latest
    ports:
      - "10051:10051"
    volumes:
      #   - /etc/localtime:/etc/localtime:ro
      #   - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    links:
      - mysql-server:mysql-server
      - zabbix-java-gateway:zabbix-java-gateway
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    env_file:
      - .env_db_mysql
      - .env_srv
    user: root
    depends_on:
      - mysql-server
      - zabbix-java-gateway
      - zabbix-snmptraps
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-server
          - zabbix-server-mysql
          - zabbix-server-ubuntu-mysql
          - zabbix-server-mysql-ubuntu
      zbx_net_frontend:
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.company: "Zabbix SIA"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "ubuntu"

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-4.0-latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql-server:mysql-server
      - zabbix-server:zabbix-server
    volumes:
      #   - /etc/localtime:/etc/localtime:ro
      #   - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
    env_file:
      - .env_db_mysql
      - .env_web
    user: root
    depends_on:
      - mysql-server
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-web-nginx-mysql
          - zabbix-web-nginx-ubuntu-mysql
          - zabbix-web-nginx-mysql-ubuntu
      zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
      com.zabbix.company: "Zabbix SIA"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "ubuntu"

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:ubuntu-4.0-latest
    ports:
      - "10052:10052"
    env_file:
      - .env_java
    user: root
    networks:
      zbx_net_backend:
        aliases:
          - zabbix-java-gateway
          - zabbix-java-gateway-ubuntu
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix Java Gateway"
      com.zabbix.company: "Zabbix SIA"
      com.zabbix.component: "java-gateway"
      com.zabbix.os: "ubuntu"

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:ubuntu-4.0-latest
    ports:
      - "162:162/udp"
    volumes:
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    user: root
    networks:
      zbx_net_frontend:
        aliases:
          - zabbix-snmptraps
      zbx_net_backend:
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix snmptraps"
      com.zabbix.company: "Zabbix SIA"
      com.zabbix.component: "snmptraps"
      com.zabbix.os: "ubuntu"

  mysql-server:
    image: mysql:5.7
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
    volumes:
      - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
    env_file:
      - .env_db_mysql
    user: root
    stop_grace_period: 1m
    networks:
      zbx_net_backend:
        aliases:
          - mysql-server
          - zabbix-database
          - mysql-database

  db_data_mysql:
    image: busybox
    volumes:
      - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
```
Файлы переменных окружения взяты из репозитория и не менялись: 
.env_db_mysql
.env_java
.env_srv
.env_web

Контейнеры запускаются, но web морда отвечает: Database error Unable to select configuration.
Насколько понимаю не залились данные. В инструкции написано, залить schema.sql, images.sql и data.sql. Где их взять? Ткните носом. В zabbix репозитории встечал только images.sql...
