### ISSUE TITLE
Feature request - when ssl is enabled in the zabbix-web-nginx-* container, redirect from http

### ISSUE THREAD

**Issue by nneul** [zabbix/zabbix-docker#460]
It currently sends an HSTS header, but does not do any forced redirect on the http port if you haven't accessed the https port first.  

Side note - I would recommend removing "includeSubdomains" from the HSTS advertisement as that is really something that an admin should explicitly and consciously choose - to be aware of the side effects.

**Comment by dotneft** [comment]
It is impossible, because instance does not know which port you exposed for HTTPS.

**Comment by SpiderMattX** [comment]
Impossible is a word used by quitters...

There is no reason an environment variable couldn't be added to instruct the container which port or even which URL to force a redirect to. Now when considering the "typical user" of today's Internet, it's reasonable to say that relying on a user to consciously ensure they are using HTTPS is quite unwise. Considering that, it makes the SSL feature partially useless without being able to force the user to the desired protocol. This needs corrected and shouldn't take much time to implement.

**Comment by dotneft** [comment]
Docker container is just a way how you distribute service, way to make your life simple :-) Usually on top of docker image you have orchestration, like OpenShift. Feel free to use these "on top" features to redirect/request using SSL.

**Comment by SpiderMattX** [comment]
I'm aware and appreciate the fast feedback.

Unfortunately, many of us aren't deploying service clusters to a complexity that justifies the additional setup overhead and this would prove to be the much more ideal solution. I have a routing layer on top of my cluster, but I can't say it's the perfect solution to implement this. I don't think it's unreasonable to bring some of the traditional methods into the container ecosystem even though the mentality of design is quite different.

Wouldn't you agree?

**Comment by dotneft** [comment]
Unfortunately I do not agree with you. We provide images which are useful for wide range customers, including non-HTTP users in private networks. If you would like to use HTTPs and do not want to use heavy services, feel free to build your own images based on our images, or use proxy containers which can provide HTTPS. Like reverse proxy containers.

**Comment by fpaternot** [comment]
Well, i have to agree that when knowing you have https enabled, http should only redirect traffic to encrypted port. However, i believe most modern browsers are migrating to a ssl-first, once connecting so, you should be covered anyway. Or well, dont expose http port at all, once you are running a https instance :)

I personally don't care much about the webserver since i spawn a reverse proxy to enforce my own polices (ssl included), redirects and cache.

**Comment by dotneft** [comment]
It is up to you do not expose http, use only https with provided certs. We do not close such option. You are able to choose what you want, but, anyway, we are trying to provide the solution with *base* and *suitable* options for wide range users. To provide redirect we need to know the real URL you use for Zabbix web, but in case of load balancers, reverse proxies such information is hidden for final HTTP destination. More env variables make solution less intuitive, more complex.

**Comment by SpiderMattX** [comment]
Well I certainly appreciate the clarification on the team's stance about this. My first take on the early responses were leaving me feeling blown off but I can appreciate that last view point. By all means, I'm not complaining and we certainly appreciate this rather highly valuable and yet free product. Working for multiple companies in the fixed wireless industry, fiscal efficiency is absolutely key which makes Zabbix a perfect fit for most needs. I've spent my life in software engineering so rest assured, I understand the depth of even such a small ask, so please don't take it as entitlement or disapproval of the product.

I would however say that the original response to the post that started this thread should have probably been chosen better because it did come off looking like a major customer service issue (by defaulting to such a simple and inaccurate answer). I feel a more appropriate response would have been to more or less explain what you just explained to me while stressing the daunting list of priorities that I'm sure you have to juggle with such a large project.

Take it for what it's worth, but you are all appreciated none the less! I've been working with the Zabbix platform for 3 years now and haven't looked back!

**Comment by dotneft** [comment]
Thank you! I appreciate your observation. Will consider that in future.

**Comment by pandafy** [comment]
Hey! I would also like to have HTTP to HTTPS redirect supported by default. After reading the discourse, I understand the developer team's stance. 

I am leaving the solution (workaround) which I implemented to quickly redirect HTTP requests to HTTPS in the docker-compose in hope that it will useful for future users. 

**Step 1:** Create  `nginx.conf` file at `.zbx_env/etc/zabbix/nginx.conf` with the following content
```conf
server {
    listen 8080;
    listen [::]:8080;
    server_name zabbix;

    return 301 https://$host$request_uri;
}
```

**Step 2:** Update your docker-compose to mount this file at `/etc/zabbix/nginx.conf`. 

```yaml
version: '3.5'
services:
  zabbix-web-nginx-pgsql:
    build:
      context: ./Dockerfiles/web-nginx-pgsql/ubuntu
      cache_from:
        - ubuntu:jammy
      args:
        BUILD_BASE_IMAGE: zabbix-build-pgsql:ubuntu-local
      image: zabbix-web-nginx-pgsql:ubuntu-local
      ports:
        - "80:8080"
        - "443:8443"
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
        - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
        # Mount the nginx configuration created in Step 1 here
        - ./zbx_env/etc/nginx/conf.d/nginx.conf:/etc/zabbix/nginx.conf:ro
```

**Note:** The above docker-compose.yml example builds from the example docker-compose.yml provided in this repository.
