### ISSUE TITLE
Does zabbix-server must use real IP ？

### ISSUE THREAD

**Issue by mengxifl** [zabbix/zabbix-docker#465]
I run a zabbix server on a k8s cluster
this is my yaml file without web service

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix
  namespace: default
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: zabbix
  template: 
    metadata: 
      labels: 
        app: zabbix 
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql
        env:
        - name: DB_SERVER_HOST 
          value: "write-db-srv"
        - name: MYSQL_USER 
          value: "root"
        - name: MYSQL_PASSWORD 
          value: "passwore"
        ports:
          - name: zabbix-server
            containerPort: 10051
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-svc
  namespace: default
spec: 
  type: NodePort #??????? Is right?
  selector:
    app: zabbix
    creater: mengxi
  ports:
  - name: zabbix-svc
    nodePort: 10051
    port: 10051
    targetPort: 10051
```
I can access zabbix web page. so web yaml file is redundant.

I can telnet any k8s node Ip 10051 port use my notebook. 

logs:

158:20190523:040123.755 Message from 10.224.3.1 is missing header. Message ignored.

10.224.3.1 is a VIP

i set host on zabbix-web Point to this server.

then i install docker and use zabbix-agent image run as a container and give -p 0.0.0.0:10050:10050 it run but give me alots error like this

60:20190523:020419.820 active check configuration update from [myk8s:10051] started to fail (ZBX_TCP_READ() timed out)
60:20190523:020519.862 active check configuration update from [myk8s:10051] is working again  

i use exec -it in this service and ping myk8s . it work .

i use kubectl exec -it zabbix-server /bin/bash ping docker server . it work . 

I can telnet any k8s node Ip 10051 port use my notebook. 

I can telnet any docker Ip 10050 port use my notebook. 

then I setup a centos6 and install zabbix-agent .  and configure it notwork too.

so did i miss something? or zabbix-server must use k8s node ip?
