### ISSUE TITLE
Guidance with permissions issue snmptraps.log

### ISSUE THREAD

**Issue by nickadams675** [zabbix/zabbix-docker#503]
Docker logs from zabbix-snmptrap container:
``` bash
cannot stat SNMP trapper file "/var/lib/zabbix/snmptraps/snmptraps.log": [13] Permission denied
```
A directory listing on docker host:
``` bash
# ls -lah zbx_env/var/lib/zabbix/snmptraps/snmptraps.log 
-rwxrwxrwx. 1 root root 0 Oct  9 14:38 zbx_env/var/lib/zabbix/snmptraps/snmptraps.log
```
Docker-compose.yml:
``` yaml
version: "3.5"
services:
  zabbixagent:
    image: zabbix/zabbix-agent:centos-4.2.6
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    user: root
    privileged: true
    pid: "host"
    networks:
      cpcnet:
        ipv4_address: 172.20.0.19
    stop_grace_period: 5s

  zabbixproxy:
    image: zabbixproxy removed for privacy
    ports:
      - "10051:10051"
      - "161:161"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    depends_on:
      - snmptraps
    restart: always
    networks:
      cpcnet:
        ipv4_address: 172.20.0.16
    stop_grace_period: 30s

  snmptraps:
    image: zabbix/zabbix-snmptraps:centos-4.2.6
    ports:
      - "162:162/udp"
    volumes:
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    restart: always
    networks:
      cpcnet:
        ipv4_address: 172.20.0.18
    stop_grace_period: 5s
```
