### ISSUE TITLE
Trying to run zabbix-proxy "TLSConnect" value requires "TLSPSKFile", but it is not defined"

### ISSUE THREAD

**Issue by rpelletierrefocus** [zabbix/zabbix-docker#516]
I am trying to run a standalone zabbix-proxy using PSK, but I keep getting this error even though I do in fact have this defined in the .env file

docker-compose.yml
```
version: '3.5'
services:
 zabbix-proxy-sqlite3:
  container_name: zabbix-proxy
  image: zabbix-proxy
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./lib:/var/lib/zabbix
   - ./conf:/etc/zabbix
  env_file:
   - .env
  user: root
```

.env
```
ZBX_PROXYMODE=0
ZBX_SERVER_HOST=monitor.my.cloud
ZBX_HOSTNAME=fom-zabbix-proxy
ZBX_TLSCONNECT=psk
ZBX_TLSACCEPT=psk
ZBX_TLSPSKIDENTITY=FOM1
ZBX_TLSPSKFILE=/etc/zabbix/key.psk
```

zabbix_proxy [123]: ERROR: parameter "TLSConnect" value requires "TLSPSKFile", but it is not defined
