### ISSUE TITLE
container frontend cannot access to external database

### ISSUE THREAD

**Issue by sgaunet** [zabbix/zabbix-docker#538]
Hello all,

I would like to use some docker images but keep the postgresql server outside docker. 

I have created this docker-compose file :  
```
version: '3.1'
services:
  zabbix-web:    # The main Zabbix web UI or interface
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-4.4-latest
    restart: always
    environment:  # Postgre database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: "*******"
      POSTGRES_DB: zabbix_db
      DB_SERVER_HOST: 192.168.50.34
      DB_SERVER_PORT: 5432
      ZBX_SERVER_HOST: 192.168.50.34
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Paris"
      ZBX_MAXEXECUTIONTIME: 500
    ports:    # Port where Zabbix UI is available
      - 8080:80
    dns:
      - X.X.X.X
      - Y.Y.Y.Y
```

The logs are clear :  
```
**** PostgreSQL server is not available. Waiting 5 seconds...
```

But if I go inside the container, I have no difficulty to connect to the database. So I don't understand what's wrong ?

```
root@zabbix34-test:~/frontend# docker container ls
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS                           NAMES
c4ec94598bab        zabbix/zabbix-web-nginx-pgsql:ubuntu-4.4-latest   "docker-entrypoint.sh"   28 minutes ago      Up About a minute   443/tcp, 0.0.0.0:8080->80/tcp   frontend_zabbix-web_1
root@zabbix34-test:~/frontend# docker exec -ti frontend_zabbix-web_1 bash
root@c4ec94598bab:/usr/share/zabbix# PGPASSWORD="**********"
root@c4ec94598bab:/usr/share/zabbix# psql -h 192.168.50.34  zabbix_db -U zabbix
psql (10.10 (Ubuntu 10.10-0ubuntu0.18.04.1), server 11.6 (Ubuntu 11.6-1.pgdg18.04+1))
Type "help" for help.

zabbix_db=> \q
```

Thnks for your help
