### ISSUE TITLE
k8s zabbix-server pod memory issue

### ISSUE THREAD

**Issue by pavel-hladik** [zabbix/zabbix-docker#540]
Hi, we have a issue with zabbix/zabbix-server-mysql:centos-4.2-latest running on GCP k8s cluster. It doesn't matter how much we set memory requests and limits, zabbix-server always fill the maximum and pod is restarting. We have about one restart per day at random time. We have those requests and limits for now:
```
          resources:
           requests:
            cpu: "4"
            memory: 48Gi
           limits:
            cpu: "8"
            memory: 64Gi
```
We are monitoring use of memory (usageBytes) of every pod in k8s cluster and it seems like zabbix-server doesn't need so much memory, but sometimes it eats all of it. When I see the zabbix-server logs in time of restart I see it can't accept any TLS handshake from agents and can't run any script. Do you have any experience with it? Thank you.
