### ISSUE TITLE
Permission denied when setting ZBX_EXPORTFILESIZE in Zabbix docker containers

### ISSUE THREAD

**Issue by jadbaz** [zabbix/zabbix-docker#567]
### Error
```
zabbix-server_1  |      7:20200331:085115.501 cannot initialize export: Cannot access path "/var/lib/zabbix/export/": [13] Permission denied.
zabbix-export-issue_zabbix-server_1 exited with code 1
```

### Steps to reproduce:
- Copy this docker-compose.yml below
- docker-compose up

### docker-compose.yml (Minimal Working Example)
```
version: '3.1'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-4.4.7
    environment:
      - ZBX_EXPORTFILESIZE=1G
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - DB_SERVER_HOST=mysql-server
    networks:
      zabbix:
    depends_on:
      - mysql-server
  mysql-server:
    image: mariadb:10.4.12
    command: [--character-set-server=utf8, --collation-server=utf8_bin]
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
    networks:
      zabbix:
networks:
  zabbix:
    driver: bridge
```

### Notes
- Version numbers are pinned for immutability
- I did not mount the export directory. The failure happens even without anything being mounted

### Debugging:
It seems the /var/lib/zabbix/export directory has default root:root permissions without write permissions

```
[root@ip-172-31-32-132 zabbix-export-issue]# docker run zabbix/zabbix-server-mysql:alpine-4.4.7 ls -l /var/lib/zabbix
total 0
drwxr-sr-x    2 zabbix   root             6 Mar 24 00:51 enc
drwxr-xr-x    2 root     root             6 Mar 31 09:07 export
drwxr-sr-x    2 zabbix   root             6 Mar 24 00:51 mibs
drwxr-sr-x    2 zabbix   root             6 Mar 24 00:51 modules
drwxr-sr-x    2 zabbix   root             6 Mar 24 00:51 snmptraps
drwxr-sr-x    2 zabbix   root             6 Mar 24 00:51 ssh_keys
drwxr-sr-x    5 zabbix   root            45 Mar 24 00:51 ssl
```
