### ISSUE TITLE
permission error log entry with zabbix-web-nginx-mysql

### ISSUE THREAD

**Issue by cybermcm** [zabbix/zabbix-docker#589]
Hi,

using the latest zabbix-web-nginx-mysql image, I'm catching an error entry in the log:
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)

a permission problem caused by running the container as root? tried other users but then there are even more errors in the log

```
zabbix                  | ** Deploying Zabbix web-interface (Nginx) with MySQL database
zabbix                  | ** Preparing the system
zabbix                  | ** Preparing Zabbix web-interface
zabbix                  | ** Using MYSQL_USER variable from ENV
zabbix                  | ** Using MYSQL_PASSWORD variable from ENV
zabbix                  | ********************
zabbix                  | * DB_SERVER_HOST: sql
zabbix                  | * DB_SERVER_PORT: 3306
zabbix                  | * DB_SERVER_DBNAME: zabbix
zabbix                  | ********************
zabbix                  | ** Adding Zabbix virtual host (HTTP)
zabbix                  | **** Impossible to enable SSL support for Nginx. Certificates are missed.
zabbix                  | ln: /var/log/nginx/error.log: Permission denied
zabbix                  | ** Preparing Zabbix frontend configuration file
zabbix                  | ** Updating '/etc/php7/php-fpm.d/zabbix.conf' parameter "php_value[max_execution_time]": '600'... updated
zabbix                  | ** Updating '/etc/php7/php-fpm.d/zabbix.conf' parameter "php_value[memory_limit]": '128M'... updated
zabbix                  | ** Updating '/etc/php7/php-fpm.d/zabbix.conf' parameter "php_value[post_max_size]": '16M'... updated
zabbix                  | ** Updating '/etc/php7/php-fpm.d/zabbix.conf' parameter "php_value[upload_max_filesize]": '2M'... updated
zabbix                  | ** Updating '/etc/php7/php-fpm.d/zabbix.conf' parameter "php_value[max_input_time]": '300'... updated
zabbix                  | ** Updating '/etc/php7/php-fpm.d/zabbix.conf' parameter "php_value[date.timezone]": 'Europe/Vienna'... added
zabbix                  | sed: can't create temp file '/usr/share/zabbix/include/defines.inc.phpXXXXXX': Permission denied
zabbix                  | ** Cleaning the system
zabbix                  | ########################################################
zabbix                  | ** Executing supervisord
zabbix                  | 2020-05-01 05:41:45,106 INFO Included extra file "/etc/supervisor/conf.d/supervisord_zabbix.conf" during parsing
zabbix                  | 2020-05-01 05:41:45,106 INFO Included extra file "/etc/supervisor/conf.d/supervisord_zabbix.conf" during parsing
zabbix                  | 2020-05-01 05:41:45,120 INFO RPC interface 'supervisor' initialized
zabbix                  | 2020-05-01 05:41:45,120 INFO RPC interface 'supervisor' initialized
zabbix                  | 2020-05-01 05:41:45,122 INFO supervisord started with pid 1
zabbix                  | 2020-05-01 05:41:45,122 INFO supervisord started with pid 1
zabbix                  | 2020-05-01 05:41:46,126 INFO spawned: 'nginx' with pid 43
zabbix                  | 2020-05-01 05:41:46,126 INFO spawned: 'nginx' with pid 43
zabbix                  | 2020-05-01 05:41:46,130 INFO spawned: 'php-fpm7' with pid 44
zabbix                  | 2020-05-01 05:41:46,130 INFO spawned: 'php-fpm7' with pid 44
zabbix                  | nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
zabbix                  | [01-May-2020 05:41:46] NOTICE: fpm is running, pid 44
zabbix                  | [01-May-2020 05:41:46] NOTICE: ready to handle connections
zabbix                  | 2020-05-01 05:41:48,514 INFO success: nginx entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix                  | 2020-05-01 05:41:48,514 INFO success: nginx entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix                  | 2020-05-01 05:41:48,515 INFO success: php-fpm7 entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix                  | 2020-05-01 05:41:48,515 INFO success: php-fpm7 entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
```

```
zabbix:
  container_name: zabbix
  depends_on:
   - sql
   - zabbix-server
  environment:
   - DB_SERVER_HOST=${zabbix_DB_SERVER_HOST}
   - MYSQL_USER=${zabbix_MYSQL_USER}
   - MYSQL_PASSWORD=${zabbix_MYSQL_PASSWORD}
   - PHP_TZ=${TZ}
   - TZ=${TZ}
   - ZBX_SERVER_NAME=${zabbix_ZBX_SERVER_NAME}
   - ZBX_SESSION_NAME=${zabbix_ZBX_SESSION_NAME}
  hostname: zabbix
  image: zabbix/zabbix-web-nginx-mysql
  labels:
   - ${ouro_true}
   - traefik.enable=true
   - "traefik.http.routers.zabbix.rule=Host(`${hostname}`) && PathPrefix(`/zabbix`)"
   - traefik.http.routers.zabbix.entrypoints=web-secure
   - traefik.http.routers.zabbix.tls.certresolver=le
   - traefik.http.routers.zabbix.tls=true
   - traefik.http.routers.zabbix.priority=2
   - traefik.http.routers.zabbix.tls.options=default
   - traefik.http.routers.zabbix.middlewares=zabbix
   - traefik.http.middlewares.zabbix.stripprefix.prefixes=/zabbix
   - traefik.http.services.zabbix.loadbalancer.server.port=8080
  networks:
   - sql
   - web
  restart: always
  volumes:
   - ${timezone}
   - ${localtime}
```
