### ISSUE TITLE
exposed ports wrong order, healthcheck

### ISSUE THREAD

**Issue by gbouthenot** [zabbix/zabbix-docker#592]
In `docker-compose_v3_ubuntu_mysql_latest.yaml`, ports seem reversed.
Apache listen to port 80, not 8080, so this port must be exposed.
Also the healthcheck seem to query the wrong port.

So if this service is started alone, it reports as _unhealthy_.

```
  ports:
   - "80:8080"
   - "443:8443"
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
```

```
  ports:
   - "8080:80"
   - "8443:443"
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:80/"]
```
