### ISSUE TITLE
Correction kubernetes.yaml?

### ISSUE THREAD

**Issue by gilbertobr** [zabbix/zabbix-docker#596]
It would be possible to fix the kubernetes.yaml file
https://github.com/zabbix/zabbix-docker/blob/5.0/kubernetes.yaml ?

Errors found
1 - "extensions/v1beta1" mudar para "apps/v1"
2-  Image version

**Comment by dotneft** [comment]
Thank you! I will fix that soon. Is apps/v1 completely compatible with extensions/v1beta1?

**Comment by Tempo-Telecom** [comment]
Yes it is,
to work perfectly.
To work, you will need to leave it that way.

```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
    tier: agent
  namespace: zabbix
spec:
  selector:
    matchLabels:
      app: zabbix

...
```
