### ISSUE TITLE
connect() to unix:/tmp/php-fpm.sock failed

### ISSUE THREAD

**Issue by dkossako** [zabbix/zabbix-docker#638]
Hello,

I'm using officiaj zabbix-web-nginx-mysql image, after last update it stopped working. In logs I can see some php-fpm issues:

```
zabbix-web-nginx-mysql    | [09-Jun-2020 13:23:43] ALERT: [pool zabbix] user has not been defined
zabbix-web-nginx-mysql    | [09-Jun-2020 13:23:43] ALERT: [pool zabbix] user has not been defined
zabbix-web-nginx-mysql    | [09-Jun-2020 13:23:43] ERROR: failed to post process the configuration
zabbix-web-nginx-mysql    | [09-Jun-2020 13:23:43] ERROR: failed to post process the configuration
zabbix-web-nginx-mysql    | [09-Jun-2020 13:23:43] ERROR: FPM initialization failed
zabbix-web-nginx-mysql    | [09-Jun-2020 13:23:43] ERROR: FPM initialization failed
zabbix-web-nginx-mysql    | 2020-06-09 13:23:43,462 INFO exited: php-fpm7.2 (exit status 78; not expected)
zabbix-web-nginx-mysql    | 2020-06-09 13:23:43,462 INFO exited: php-fpm7.2 (exit status 78; not expected)
```

docker-compose.yml
```
version: '3.5'

services:
  zabbix-web-nginx-mysql:
    container_name: zabbix-web-nginx-mysql
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-4.4-latest
    user: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
```
