### ISSUE TITLE
zabbix/zabbix-web-nginx-mysql:centos-latest permission denied

### ISSUE THREAD

**Issue by ronivay** [zabbix/zabbix-docker#649]
web-nginx-mysql centos version has some weird permission issue against zabbix php-fpm configuration. My environment is nothing fancy, just alertscripts mounted from host machine and DB connection environment variables set.

`"Image": "zabbix/zabbix-web-nginx-mysql:centos-latest@sha256:a5672148da50fdac782f0947ed7de8326ed48039b7976a65f37a4975aa7af101"`

Just a simple swap from centos to ubuntu and no issues.

error from container logs during startup:

```
** Preparing Zabbix frontend configuration file
** Updating '/etc/php-fpm.d/zabbix.conf' parameter "php_value[max_execution_time]": '600'... updated
grep: /etc/php-fpm.d/zabbix.conf: Permission denied
grep: /etc/php-fpm.d/zabbix.conf: Permission denied
```

following with permission denied errors from each attempt to modify/read the said configuration file.

```
# docker exec -it 77341d9a4d5c bash

bash-4.4$ stat /etc/php-fpm.d/zabbix.conf
  File: /etc/php-fpm.d/zabbix.conf
  Size: 567         Blocks: 8          IO Block: 4096   regular file
Device: fd01h/64769d  Inode: 2434850     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1997/  zabbix)   Gid: (    0/    root)
Access: 2020-06-11 07:51:52.684318189 +0000
Modify: 2020-06-11 07:51:52.684318189 +0000
Change: 2020-06-11 07:51:52.684318189 +0000
 Birth: -

bash-4.4$ id
uid=1997(zabbix) gid=1995(zabbix) groups=1995(zabbix),0(root)
bash-4.4$ groups
zabbix root

bash-4.4$ cat /etc/php-fpm.d/zabbix.conf
cat: /etc/php-fpm.d/zabbix.conf: Permission denied
```

interestingly, after touching the file it works just fine

```
bash-4.4$ touch /etc/php-fpm.d/zabbix.conf
bash-4.4$ cat /etc/php-fpm.d/zabbix.conf
[zabbix]

listen = /tmp/php-fpm.sock

pm = dynamic
pm.max_children = 50
...
```

**Comment by dotneft** [comment]
I can not reproduce the problem. What user do you use to run container?

**Comment by ronivay** [comment]
seems that i'm not able to either. upgraded my docker hosts after creating this issue and continued to use ubuntu image, but have very little doubt that it had anything to do with the issue. container didn't have any additional user configuration in place, so default zabbix user.

probably can be closed then since the environment doesn't exist anymore where i encountered this. but all in all didn't have anything special there, YAML file used for docker swarm stack setup below:

```
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:centos-latest
    environment:
      - DB_SERVER_PORT=1234
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix
      - PHP_TZ = "time/zone"
      - ZBX_SERVER_NAME = "zabbix"
      - ZBX_SERVER_HOST = "zabbix"
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - zabbix-server
    networks:
      -  zabbix-net
```

simply swapped image from centos -> ubuntu here after encountering the permission denied issue and all worked as it's supposed to.
