### ISSUE TITLE
Zabbix server does not use env file

### ISSUE THREAD

**Issue by SanderDelden** [zabbix/zabbix-docker#671]
I'm trying to start zabbix-server using docker-compse, my docker-compose.yml is as follows:
```
version: '3.8'
services:
  zabbix-server:
    restart: always
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.0
    container_name: zabbix-server
    volumes:
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    env_file:
        - zabbix_server_env.list
```

Output of zabbix_server_env.list:
```
ZBX_SOURCEIP=10.10.17.110
ZBX_TIMEOUT=5
ZBX_PROXYCONFIGFREQUENCY=60
DB_SERVER_HOST=10.10.17.120
MYSQL_DATABASE=zabbix_db
MYSQL_USER=zabbix_user
MYSQL_PASSWORD=XXXXXXXX
ZBX_STARTPOLLERS=5
ZBX_STARTPOLLERSUNREACHABLE=1
ZBX_STARTPINGERS=1
ZBX_STARTDISCOVERERS=0
ZBX_STARTTRAPPERS=0
ZBX_STARTDISCOVERERS=1
ZBX_STARTHTTPPOLLERS=0
```

When starting the container the following is shown in the log out:
```
** Preparing Zabbix server
** Using MYSQL_USER variable from ENV
********************
* DB_SERVER_HOST: 10.10.17.120
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix_db
********************
```

However when checking `zabbix_server.conf` inside the container the configuration has not been updated accordingly with the env file.
