### ISSUE TITLE
zabbix-web show zabbix server is no running

### ISSUE THREAD

**Issue by zhou-mfk** [zabbix/zabbix-docker#673]
zabbix-web-nginx-mysql:centos-4.0.3

zabbix server version is 4.0.3

zabbix-server is source compilation and installation.

zabbix-web use docker-compose v3 started
docker-compose.yml:
```
version: '3.5'
services:
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:centos-4.0.3
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    network_mode: "host"
    extra_hosts:
        zabbix-server-v4: 10.206.32.33
    environment:
      - DEBUG_MODE=true
      - ZBX_SERVER_HOST=10.206.32.33
      - ZBX_SERVER_PORT=10051
      - ZBX_SERVER_NAME=zabbix-server-v4
      - DB_SERVER_HOST=10.206.32.34
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix@Mysql
      - MYSQL_DATABASE=zabbix
      - PHP_TZ="Asia/Shanghai"
      - ZBX_HISTORYSTORAGEURL=http://10.206.32.35:9200
      - ZBX_HISTORYSTORAGETYPES=['uint','text', 'dbl','str', 'log']
      - ZBX_MAXEXECUTIONTIME=1000
      - ZBX_MEMORYLIMIT=4G
```
zabbix-web show zabbix server is no running, but zabbix server is running .
And the data displayed is not up to date

![image](https://user-images.githubusercontent.com/15190461/87410797-56158180-c5f9-11ea-8037-87920f7c3f37.png)

In docker containerd  telnet zabbix_server:port is ok.

I started Nginx + PHP on the Zabbix Server machine and found that it worked.

I would like to ask what causes this?
