### ISSUE TITLE
server-mysql is not available

### ISSUE THREAD

**Issue by SanderDelden** [zabbix/zabbix-docker#674]
I'm running into a bit of an issue with server-mysql. I have currently set this up with pacemaker/coronsync, should a node go down pcs will move the VIP and start the Docker containers. My docker-compose.yml looks as follows:  
```
version: '3.8'
services:
  zabbix-server:
    restart: always
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.0
    container_name: zabbix-server
    volumes:
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "10051:10051"
    env_file:
      - zabbix_server_env.list
```

Contents of zabbix_server_env.list:
```
ZBX_SOURCEIP=10.10.17.110
ZBX_LISTENPORT=10051
ZBX_TIMEOUT=5
ZBX_PROXYCONFIGFREQUENCY=60
DB_SERVER_HOST=10.10.17.120
MYSQL_DATABASE=zabbix_db
MYSQL_USER=zabbix_user
MYSQL_PASSWORD=zabbix_userpass
ZBX_STARTPOLLERS=5
ZBX_STARTPOLLERSUNREACHABLE=1
ZBX_STARTPINGERS=1
ZBX_STARTDISCOVERERS=0
ZBX_STARTTRAPPERS=0
ZBX_STARTDISCOVERERS=1
ZBX_STARTHTTPPOLLERS=0
ZBX_CACHESIZE=4G
ZBX_HISTORYCACHESIZE=512M
ZBX_HISTORYINDEXCACHESIZE=512M
ZBX_TRENDCACHESIZE=512M
ZBX_VALUECACHESIZE=512M
```

I am able to connect to the DB without any issues, but when starting the container the Zabbix server is shown as not running in the webinterface. I am also not able to telnet to port 10051 on the host. When checking with netstat it seems that the port is currently not listening:
```
root@d8cf6c54bce1:/var/lib/zabbix# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:33957        0.0.0.0:*               LISTEN      -
udp        0      0 127.0.0.11:34275        0.0.0.0:*                           -
```

My network setup for the nodes is as follows:
VIP: 10.10.17.110
srv01: 10.10.17.111
srv02: 10.10.17.112

I've placed the debug logs on pastebin as this was 2000+ lines: https://pastebin.com/GBhmgeTE
Please let me know if any additional information is required.
