### ISSUE TITLE
Setup SAML with AD domain.

### ISSUE THREAD

**Issue by BramFr** [zabbix/zabbix-docker#677]
I`m trying to setup SAML with AD. 
But i have a few questions. 

Where can i find the metadata for saml? I`ll already created a file with this info: https://www.zabbix.com/forum/zabbix-help/402122-zabbix-saml-meatdata-url

docker-compose file for import sp,idp and metadata files.
```
  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0-latest
    restart: always
    volumes:
      - ./Utils.php:/usr/share/zabbix/vendor/php-saml/src/Saml2/Utils.php
      - ./data/zabbix-metadata.xml:/usr/share/zabbix/zabbix-metadata.xml:ro
      - ./cert/idp.crt:/usr/share/zabbix/conf/certs/idp.crt:ro
      - ./cert/sp.crt:/usr/share/zabbix/conf/certs/sp.crt:ro
      - ./cert/sp.key:/usr/share/zabbix/conf/certs/sp.key:ro
```

SAML settings:
![image](https://user-images.githubusercontent.com/16082279/88024794-92823980-cb33-11ea-9e94-802786923f30.png)

At the login page ill choose this option: `Sign in with Single Sign-On (SAML)` 
When i enable debug mode for php getting this error message:
```
zabbix-frontend_1  | [21-Jul-2020 07:24:08] WARNING: [pool zabbix] child 68 said into stderr: "[21-Jul-2020 09:24:08 Europe/Amsterdam] PHP Warning:  Use of undefined constant OPENSSL_PKCS1_PADDING - assumed 'OPENSSL_PKCS1_PADDING' (this will throw an Error in a future version of PHP) in /usr/share/zabbix/vendor/xmlseclibs/src/XMLSecurityKey.php on line 182"
zabbix-frontend_1  | [21-Jul-2020 07:24:08] WARNING: [pool zabbix] child 68 said into stderr: "[21-Jul-2020 09:24:08 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Call to undefined function RobRichards\XMLSecLibs\openssl_get_privatekey() in /usr/share/zabbix/vendor/xmlseclibs/src/XMLSecurityKey.php:345"
zabbix-frontend_1  | [21-Jul-2020 07:24:08] WARNING: [pool zabbix] child 68 said into stderr: "Stack trace:"
zabbix-frontend_1  | [21-Jul-2020 07:24:08] WARNING: [pool zabbix] child 68 said into stderr: "#0 /usr/share/zabbix/vendor/php-saml/src/Saml2/Auth.php(748): RobRichards\XMLSecLibs\XMLSecurityKey->loadKey('-----BEGIN PRIV...', false)"
zabbix-frontend_1  | [21-Jul-2020 07:24:08] WARNING: [pool zabbix] child 68 said into stderr: "#1 /usr/share/zabbix/vendor/php-saml/src/Saml2/Auth.php(701): OneLogin\Saml2\Auth->buildMessageSignature('fVNdb5tAEHz3r7B...', 'https://zabbix....', 'http://www.w3.o...', 'SAMLRequest')"
zabbix-frontend_1  | [21-Jul-2020 07:24:08] WARNING: [pool zabbix] child 68 said into stderr: "#2 /usr/share/zabbix/vendor/php-saml/src/Saml2/Auth.php(558): OneLogin\Saml2\Auth->buildRequestSignature('fVNdb5tAEHz3r7B...', 'https://zabbix....', 'http://www.w3.o...')"
zabbix-frontend_1  | [21-Jul-2020 07:24:08] WARNING: [pool zabbix] child 68 said into stderr: "#3 /usr/share/zabbix/index_sso.php(240): OneLogin\Saml2\Auth->login()"
zabbix-frontend_1  | [21-Jul-2020 07:24:08] WARNING: [pool zabbix] child 68 said into stderr: "#4 {main}"
zabbix-frontend_1  | [21-Jul-2020 07:24:08] WARNING: [pool zabbix] child 68 said into stderr: "  thrown in /usr/share/zabbix/vendor/xmlseclibs/src/XMLSecurityKey.php on line 345"
```
