### ISSUE TITLE
ZBX_SERVER_HOST ($ZBX_SERVER) seems to be ignored

### ISSUE THREAD

**Issue by Dem0n3D** [zabbix/zabbix-docker#683]
I am using compose config like this (for swarm):
```yaml
version: "3.3"
services:
  db:
    image: timescale/timescaledb:latest-pg11
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=${DBPASS}
    
  server:
    image: zabbix/zabbix-server-pgsql:alpine-5.0-latest
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=zabbix
      - ENABLE_TIMESCALEDB=true
  
  web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0-latest
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=zabbix
      - ENABLE_TIMESCALEDB=true
      - ZBX_SERVER_HOST=server
      - ZBX_SERVER_NAME=zabbix

volumes:
  db:
  mibs:
```

I can see that variable ZBX_SERVER_HOST is correctly interpolated inside 'web' container config:
`$ZBX_SERVER      = 'server';`
But container 'web' can't see zabbix server ('server').
![Screenshot_24 07 2020 16:40:%s](https://user-images.githubusercontent.com/393279/88387729-8e247d80-cdcc-11ea-9c12-c77648ec31ed.png)

If I change 'server' container name to 'zabbix-server' (default value for ZBX_SERVER_HOST) and comment variable ZBX_SERVER_HOST, it works:
```yaml
version: "3.3"
services:
  db:
    image: timescale/timescaledb:latest-pg11
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=${DBPASS}
    
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-5.0-latest
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=zabbix
      - ENABLE_TIMESCALEDB=true
  
  web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0-latest
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=zabbix
      - ENABLE_TIMESCALEDB=true
      #- ZBX_SERVER_HOST=server
      - ZBX_SERVER_NAME=zabbix

volumes:
  db:
  mibs:
```
![Screenshot_24 07 2020 16:46:%s](https://user-images.githubusercontent.com/393279/88388051-31759280-cdcd-11ea-83e4-13d4e86a0499.png)
