### ISSUE TITLE
Zabbix docker server doesn't ignore POSTGRES_DB environment variable

### ISSUE THREAD

**Issue by cojack** [zabbix/zabbix-docker#692]
Hi,
With this configuration:

```yaml

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - zabbix_netowrk

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-5.0-latest
    restart: on-failure
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
      - zabbix-agent
    networks:
      - zabbix_netowrk
```

Zabbix fails to start with logs as:

```yaml
db_1             | 2020-08-10 13:02:51.724 UTC [110] FATAL:  database "zabbix_user" does not exist
zabbix-server_1  | **** PostgreSQL server is not available. Waiting 5 seconds...
```

So, somehow Zabbix ignore environment variable `POSTGRES_DB` and read only from `POSTGRES_USER`.
