### ISSUE TITLE
Zabbix local Database error

### ISSUE THREAD

**Issue by ali-yahyaoui** [zabbix/zabbix-docker#708]
i  install zabbix with the following docker-compose file and local postgres database "none dockerized database", 
```
version: '3'
services:
 zabbix-server:
     image: zabbix/zabbix-server-pgsql:ubuntu-5.0-latest
     container_name: zabbix-server
     environment:
      DB_SERVER_HOST: **.**.**.**
      DB_SERVER_PORT: 5432
      DB_SERVER_DBNAME: zabbix
      DB_SERVER_SCHEMA: public
      DB_SERVER_USER: zabbix
      DB_SERVER_PASS: ******
      DB_SERVER_NAME: zabbix
     ports:
       - '10051:10051'
     links:
      - postgres-server:postgres-server
     depends_on:
       - postgres-server

 zabbix-web:
     image: zabbix/zabbix-web-nginx-pgsql:ubuntu-5.0-latest
     container_name: zabbix-web
     environment:
      DB_SERVER_HOST: **.**.**.**
      DB_SERVER_PORT: 5432
      DB_SERVER_DBNAME: zabbix
      DB_SERVER_SCHEMA: public
      DB_SERVER_USER: zabbix
      DB_SERVER_PASS: ******
      DB_SERVER_NAME: zabbix
      ZBX_SERVER_HOST: "zabbix-server"
      PHP_TZ: Africa/Tunis
     ports:
       - '8080:3000'
     links:
      - postgres-server:postgres-server
      - zabbix-server:zabbix-server
     depends_on:
       - zabbix-server
       - postgres-server
 postgres-server:
  image: postgres:latest
#  command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
  volumes:
   - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
   - ./.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
   - ./.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
   - ./.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
  environment:
      DB_SERVER_HOST: **.**.**.**
      DB_SERVER_PORT: 5432
      DB_SERVER_DBNAME: zabbix
      DB_SERVER_SCHEMA: public
      DB_SERVER_USER: zabbix
      DB_SERVER_PASS: ******
      DB_SERVER_NAME: zabbix
      POSTGRES_HOST_AUTH_METHOD: trust
  stop_grace_period: 1m
networks:
  default:
    external:
      name: zabbixnet
```
i got this error in container logs:
![image](https://user-images.githubusercontent.com/60253677/91728802-e6a52280-eba3-11ea-82c5-6245a13746dd.png)
when i verify postgres i find that zabbix database is available locally but the container can't connect to it !!
