### ISSUE TITLE
Using GKE variables for ZBX_SERVER_HOST inconsistant

### ISSUE THREAD

**Issue by rugenl** [zabbix/zabbix-docker#751]
In ZABBIX-WEB-APACHE-MYSQL, I was able to set ZBX_SERVER_HOST to a GKE provided service IP, like ${SOMESRV_ZABBIX_SERVICE} and the IP was passed into the config.  I tried the same thing in ZABBIX-AGENT and the literal ${SOMESRV_ZABBIX_SERVICE} was passed.  As best as I can tell, the environment variable is set on the container.  

Any ideas?

Thanks.

**Comment by dotneft** [comment]
Please provide more details about the issue.

**Comment by rugenl** [comment]
I 'm not able to reproduce, what was working in one container and not the other never works.  It's now a usability issue.  You don't know the zabbix server's cluster IP until you create it, then you have to code that IP into the web container as ZBX_SERVER_HOST. 

Environment variables are created by Kubernetes like:
```
ZABBIX_SERVER_SERVICE_PORT_10051_TCP_ADDR=10.4.11.170
ZABBIX_SERVER_SERVICE_SERVICE_HOST=10.4.11.170
ZABBIX_SERVER_PORT_10051_TCP_PORT=10051
```

I was hoping to use one of those to abstract the config something like:
```
       - name: zabbix-agent
          image: zabbix/zabbix-agent:centos-5.0-latest
          ports:
          - containerPort: 10050
            name: zabbix-agent
          env:
          - name: ZBX_SERVER_HOST
            value: ${ZABBIX_SERVER_SERVICE_SERVICE_HOST}
```

It may be that ZBX_SERVER_HOST is defined before ZABBIX_SERVER_SERVICE_SERVICE_HOST, because it's value is the string, not resolved to the IP address.
