### ISSUE TITLE
Agent 2 - Docker: Service is down

### ISSUE THREAD

**Issue by Glideh** [zabbix/zabbix-docker#756]
I'm trying to monitor docker services (containers) with Zabbix docker agent.
Zabbix interface claims "Service is down"/"Failed to fetch info data" when trying to ping the Docker daemon from the agent.
Here is how I composed my agent service:

```yml
version: "3.5"

services:
    agent:
        image: zabbix/zabbix-agent2:alpine-5.0-latest
        restart: unless-stopped
        ports:
            - "10050:10050"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
#            - ./zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - ZBX_SERVER_HOST=192.168.100.10,127.0.0.1
            - ZBX_HOSTNAME=my.monitored.host
        privileged: true
```

_BTW my conf in `./zabbix_agentd.d` seems not taken into account but that's another issue_

I guess `/var/run/docker.sock` is required by the agent to be able to communicate with Docker but did I mount it into the correct location ?

Trying to get the config from the agent:

```
docker-compose exec agent zabbix_get -s 127.0.0.1 -k docker.info
```
Gives
> ZBX_NOTSUPPORTED: Cannot fetch data.

On the host I'm able to see my running containers with `docker ps` just fine.
Is there something I'm understanding/doing wrong ? Why can't my agent communicate with Docker ?
