### ISSUE TITLE
Set host's hostname as ZBX_HOSTNAME

### ISSUE THREAD

**Issue by Glideh** [zabbix/zabbix-docker#761]
Doc claims about `ZBX_HOSTNAME`
> This variable is unique, case sensitive hostname. By default, value is hostname of the container. It is Hostname parameter in zabbix_agentd.conf

I could leave it empty but container's hostname does not mean anything useful by default.
And I'd rather not manually type the same value as `/etc/hostname` that really contains the value needed, since it can change and I need that for many hosts.

Is there a way to inject the hostname of the host as container's `ZBX_HOSTNAME` ?

**Comment by dotneft** [comment]
I think you can specify container host name. For example:
```
--hostname `hostname`
```

**Comment by Glideh** [comment]
That's interesting but I'm actually using a compose file.

```yml
version: "3.5"

services:
    agent:
        image: zabbix/zabbix-agent2:alpine-5.0-latest
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - ZBX_SERVER_HOST=192.168.100.10,127.0.0.1
            - ZBX_HOSTNAME=`hostname`
```

This would not work, would it ?

**Comment by fpaternot** [comment]
Do you mind testing my idea? Define `ZBX_HOSTNAME=$HOSTNAME`.

I don't think `hostname` will work, because its not documented to work.

You can include env variables inside compose (see https://docs.docker.com/compose/environment-variables/). Im not sure however if it will work with "environment" values.

```
It’s possible to use environment variables in your shell to populate values inside a Compose file:

web:
  image: "webapp:${TAG}"
```

**Comment by Glideh** [comment]
I tried that but it doesn't seems to work on docker environment variables.
Here is what I tried:

```yml
version: "3.5"

services:
    agent:
#       [...]
        environment:
#           [...]
            - ZBX_HOSTNAME="$HOSTNAME"
```

`ZBX_HOSTNAME` gets the value `""` in the container

**Comment by dotneft** [comment]
Please check official documentation: https://docs.docker.com/compose/compose-file/#variable-substitution

**Comment by Glideh** [comment]
Thank you but the variables are not substituted in `environment` values, as I was telling just before.

**Comment by dotneft** [comment]
Did you try the solution described in: https://stackoverflow.com/questions/29377853/how-to-use-environment-variables-in-docker-compose ?

**Comment by fpaternot** [comment]
It looks like you are using docker swarm, correct?

Do you need the agent to run inside a swarm network? Because if you don't, you could set it up to run on network mode = host and your container host would be the name of where it's running.

Running containers inside swarm with network mode is a bit hackish but i think it works as you wish:

```
version: "3.9"
services:
  agent:
    networks:
      hostnet: {}

networks:
  hostnet:
    external: true
    name: host
```

https://docs.docker.com/compose/compose-file/#network-configuration-reference

**Comment by Glideh** [comment]
Thank you for your answers, I'm not using swarm.
Both mentioned solutions seem interesting, I'll try them.

**Comment by Glideh** [comment]
This doesn't get substituted either
```yml
agent:
  # [...]
  hostname: $HOSTNAME
  # [...]
```

But this seems to work
```yml
agent:
  # [...]
  network_mode: host
  # [...]
```

I'll keep you posted after some more usage.

**Comment by vgdh** [comment]
what I've used

 ```
 zabbix-server:
  image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
  container_name: zabbix-server
  hostname: zabbix-server
```
