### ISSUE TITLE
Suggestion: Disable MySQL binary logs by default

### ISSUE THREAD

**Issue by marlonanjos** [zabbix/zabbix-docker#765]
MySQL binary logs consume some precious resources and I think that it could be disabled by default, and enabled if needed by the backup strategy.

To disable the binary logs we just need to add --skip-log-bin on the mysqld command.

example:
```
mysql-server:
  container_name: zabbix-mysql
  image: mysql:8.0
  command:
   - mysqld
   - --character-set-server=utf8
   - --collation-server=utf8_bin
   - --default-authentication-plugin=mysql_native_password
   - --skip-log-bin
``` 

TYIA
