### ISSUE TITLE
Can i use a remote database?

### ISSUE THREAD

**Issue by yule-sun** [zabbix/zabbix-docker#772]
I want to use a remote database（non-docker） to deploy the zabbix, but i got an error when i change the setting in the .env_db_pgsql. I modified # DB_SERVER_HOST=postgres-server Become DB_SERVER_HOST=10.x.x.x (my database address). And commented out the database part in file docker-compose_v3_centos_pgsql_latest.yaml, It doesn't work properly anymore.
Is the method of using a remote database supported?Looking forward to your reply.

**Comment by rockaut** [comment]
Remote database is supported and is working ... but you might have to manually initialize the database and tables. This depends on how your db instance is configured in terms of permissions. In an all container environment your users have god-rights. If you're using an managed db you might not have the needed permissions.

I suppose you're talking about a server installation? Have a look at the official zabbix docs and follow the steps for manual (package or source) installation.
https://www.zabbix.com/documentation/current/manual/concepts/server

Another way would be to start the db container instance on another host and connect to that then. This way you would achieve the split services but still have all permissions in the db container and initialization would run as expected.

**Comment by yule-sun** [comment]
> Remote database is supported and is working ... but you might have to manually initialize the database and tables. This depends on how your db instance is configured in terms of permissions. In an all container environment your users have god-rights. If you're using an managed db you might not have the needed permissions.
> 
> I suppose you're talking about a server installation (as I would separate a DB from the proxies!)? Have a look at the official zabbix docs and follow the steps for manual (package or source) installation.
> https://www.zabbix.com/documentation/current/manual/concepts/server
> 
> Another way would be to start the db container instance on another host and connect to that then. This way you would achieve the split services but still have all permissions in the db container and initialization would run as expected.

Thank you very much for your reply, and I have successfully deployed it use the remote database.
        But I started 8 containers，I am not sure if several of them are necessary, because I see errors in the logs all the time. Such likes zabbix-proxy-sqlite3_1 zabbix-proxy-mysql_1 zabbix-web-apache-pgsql_1.
        When I do not use docker-compose, but instead use commands (docker run) to start the containers one by one, there will always be the following error. I feel it is the problem of the container zabbix-agent, but I don’t know how to associate with zabbix-server. My zabbix server container named zabbix-server-mysql, and i uset his command to start the zabbix-agent container
![image](https://user-images.githubusercontent.com/37107125/102469731-0ea28e00-408e-11eb-9d89-917d7f4ad4d1.png)

Could you take a look and look forward to your reply.

![image](https://user-images.githubusercontent.com/37107125/102469043-41985200-408d-11eb-8d91-f79e79742248.png)

**Comment by rockaut** [comment]
No offense, please get me right, if you are new to zabbix I would go over to Dimitris YouTube Channel (https://www.youtube.com/c/ZabbixCookBook/videos) where he covers a whole lot of Zabbix content and also some Docker things.

The "problem" with the different services in all those compose files is present since the very beginnings - I suppose it's because they want easier updating of the file-contents. Anyway: basically even in those postgres compose files mysql in present. So chose you DB of choice and remove the other db as whole.

For starting things you can also remove all proxies there too or just settle with the proxy-sqlite and dump the mysql one.

Can you just post your edited compose file?

**Comment by rockaut** [comment]
For example with psql:

```yaml
version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-pgsql:ubuntu-5.2-latest
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  links:
   - postgres-server:postgres-server
   - zabbix-java-gateway:zabbix-java-gateway
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
  env_file:
   - .env_db_pgsql
   - .env_srv
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  depends_on:
   - postgres-server
   - zabbix-java-gateway
   - zabbix-snmptraps
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-pgsql
      - zabbix-server-ubuntu-pgsql
      - zabbix-server-pgsql-ubuntu
   zbx_net_frontend:
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with PostgreSQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "ubuntu"

 zabbix-proxy-sqlite3:
  image: zabbix/zabbix-proxy-sqlite3:ubuntu-5.2-latest
  ports:
   - "10061:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  links:
   - zabbix-server:zabbix-server
   - zabbix-java-gateway:zabbix-java-gateway
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.3'
      memory: 256M
  env_file:
   - .env_prx
   - .env_prx_sqlite3
  depends_on:
   - zabbix-java-gateway
   - zabbix-snmptraps
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-proxy-sqlite3
     - zabbix-proxy-ubuntu-sqlite3
     - zabbix-proxy-sqlite3-ubuntu
   zbx_net_frontend:
  stop_grace_period: 30s
  labels:
   com.zabbix.description: "Zabbix proxy with SQLite3 database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-proxy"
   com.zabbix.dbtype: "sqlite3"
   com.zabbix.os: "ubuntu"

 zabbix-web-nginx-pgsql:
  image: zabbix/zabbix-web-nginx-pgsql:ubuntu-5.2-latest
  ports:
   - "8081:8080"
   - "8443:8443"
  links:
   - postgres-server:postgres-server
   - zabbix-server:zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
   - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
#   - ./.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
#   - ./.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
#   - ./.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  env_file:
   - .env_db_pgsql
   - .env_web
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  depends_on:
   - postgres-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-nginx-pgsql
     - zabbix-web-nginx-ubuntu-pgsql
     - zabbix-web-nginx-pgsql-ubuntu
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with PostgreSQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "ubuntu"

 zabbix-agent:
  image: zabbix/zabbix-agent:ubuntu-5.2-latest
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  links:
   - zabbix-server:zabbix-server
  deploy:
   resources:
    limits:
      cpus: '0.2'
      memory: 128M
    reservations:
      cpus: '0.1'
      memory: 64M
   mode: global
  env_file:
   - .env_agent
  privileged: true
  pid: "host"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-ubuntu
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "ubuntu"

 zabbix-java-gateway:
  image: zabbix/zabbix-java-gateway:ubuntu-5.2-latest
  ports:
   - "10052:10052"
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 512M
    reservations:
      cpus: '0.25'
      memory: 256M
  env_file:
   - .env_java
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-java-gateway
     - zabbix-java-gateway-ubuntu
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix Java Gateway"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "java-gateway"
   com.zabbix.os: "ubuntu"

 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:ubuntu-5.2-latest
  ports:
   - "162:1162/udp"
  volumes:
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 256M
    reservations:
      cpus: '0.25'
      memory: 128M
  networks:
   zbx_net_frontend:
    aliases:
     - zabbix-snmptraps
   zbx_net_backend:
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "ubuntu"

 postgres-server:
  image: postgres:latest
#  command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
  volumes:
   - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
   - ./.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
   - ./.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
   - ./.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
  env_file:
   - .env_db_pgsql
  secrets:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - postgres-server
     - pgsql-server
     - pgsql-database

 db_data_pgsql:
  image: busybox
  volumes:
   - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  snmptraps:

secrets:
  POSTGRES_USER:
    file: ./.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./.POSTGRES_PASSWORD
```

I just removed the zabbix-proxy-mysql, zabbix-web-apache-pgsql and mysql-server services.
