### ISSUE TITLE
zabbix/zabbix-web-apache-pgsql:ubuntu-latest will not start

### ISSUE THREAD

**Issue by MrDiba** [zabbix/zabbix-docker#787]
Using the following docker-compose file I'm trying to start a Zabbix instance on my Raspberry Pi 4:
```
version: "3.8"
services:

  server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zabbix
    ports:
      - "10051:10051"
    depends_on: 
      - db
    restart: always

  web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    ports:
      - "85:8080"
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zabbix
      - ZBX_SERVER_HOST=server
      - PHP_TZ=Europe/Amsterdam
      - ZBX_SERVER_NAME=server
    depends_on:
      - db
      - server
    restart: always

  db:
    image: postgres
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zabbix
    restart: always
```
But the zabbix/zabbix-web-nginx-pgsql:ubuntu-latest container will constantly restart. The log in the container show's the following:
```
** Deploying Zabbix web-interface (Nginx) with PostgreSQL database
** Using POSTGRES_USER variable from ENV
** Using POSTGRES_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: db
* DB_SERVER_PORT: 5432
* DB_SERVER_DBNAME: zabbix
* DB_SERVER_SCHEMA: public
********************
** Adding Zabbix virtual host (HTTP)
ln: failed to create symbolic link '/etc/nginx/conf.d/nginx.conf': File exists
**** Impossible to enable SSL support for Nginx. Certificates are missed.
** Preparing Zabbix frontend configuration file
########################################################
** Executing supervisord
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f8b460 (most recent call first):
<no Python frame>
```
And this message keeps showing. Changing the docker tag to alpine-latest works with no problem. 

Is this a problem with my configuration or with the ubuntu-latest docker image?
