### ISSUE TITLE
Monitoring of host network interfaces and filesystems

### ISSUE THREAD

**Issue by binerf** [zabbix/zabbix-docker#801]
**Describe the bug**
When using `zabbix-agent2` container, host filesystems usage and network interfaces are not monitored (not discovered ?) by agent.
Only `eth0` is monitored but I guess that's agent container interface.
I'd like to monitor all network interfaces of host and its filesystems usage.

**Environment**
Extract of `docker-compose.yml`:
```
 zabbix-agent:
  image: zabbix/zabbix-agent2:alpine-latest
  ports:
   - "10050:10050"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - /srv/dev-disk-by-label-zabbix/zabbix/zabbix-agent/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - /srv/dev-disk-by-label-zabbix/zabbix/zabbix-agent/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - /srv/dev-disk-by-label-zabbix/zabbix/zabbix-agent/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - /srv/dev-disk-by-label-zabbix/zabbix/zabbix-agent/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - /sys:/sys
   - /sys/fs/cgroup:/sys/fs/cgroup
   - /var/run/docker.sock:/var/run/docker.sock
  deploy:
   resources:
    limits:
      cpus: '0.4'
      memory: 256M
    reservations:
      cpus: '0.1'
      memory: 64M
   mode: global
  env_file:
   - /srv/dev-disk-by-label-zabbix/zabbix/.env_agent
  user: 0:0
  pid: "host"
  networks:
   - default
  links:
   - zabbix-proxy:zabbix-proxy
  stop_grace_period: 5s
  privileged: true
```

**Used app version**
-   image: zabbix/zabbix-proxy-sqlite3:alpine-latest
-   image: zabbix/zabbix-snmptraps:alpine-latest
-   image: zabbix/zabbix-agent2:alpine-latest
