### ISSUE TITLE
Host network interfaces

### ISSUE THREAD

**Issue by DmitriiKuvshinov** [zabbix/zabbix-docker#840]
##### SUMMARY
Hey
I just run zabbix-agent2 in my gateway with Docker v 18.09.7

This my docker-compose file
```
...
  gateway:
    restart: unless-stopped
    container_name: gateway
    image: zabbix/zabbix-agent2:alpine-5.2.6
    environment:
      - ZBX_HOSTNAME={{ansible_hostname}}
      - ZBX_SERVER_HOST=zabbix-proxy
    stop_grace_period: 5s
    ulimits:
     nproc: 65535
     nofile:
      soft: 20000
      hard: 40000
    deploy:
     resources:
      limits:
        cpus: '0.70'
        memory: 512M
      reservations:
        cpus: '0.3'
        memory: 256M
    privileged: true
    pid: "host"
    networks:
      backend:
        aliases:
        - zabbix-agent
```

If i
```
cat /host/proc/net/dev
```
i will see only container interface, but other host OS information display in Zabbix Server

Mounting volume's, like:
```
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
      - /etc:/host/etc:ro
      - /var/run/docker.sock:/host/var/run/docker.sock
  ```
Don't work

How can i monitroing host interfaces?
