### ISSUE TITLE
Error: [1146] Table 'zabbix.users' doesn't exist

### ISSUE THREAD

**Issue by ysma500** [zabbix/zabbix-docker#842]
##### SUMMARY

When using dockerhub's zabbix/zabbix-server-mysql:alpine-5.4-latest image with an empty mariadb database named zabbix, I get exactly this error: https://catonrug.blogspot.com/2018/04/z3005-query-failed-table-zabbix-users-does-not-exist.html . Considering that I'm using the docker image I thought that database provisionning was handled by zabbix's server image (I might be wrong here). 

##### OS / ENVIRONMENT / Used docker-compose files

Here is my docker-compose script running on a Ubuntu 20.04 VM to give you an idea of my env's content: 
```yaml
version: "3.9"
services:
  # https://hub.docker.com/r/prom/prometheus/ for image
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      metrics_internal:
        ipv4_address: 192.168.6.10
    ports:
      - "10054:9090"
    volumes:
      - "./prometheus/config:/etc/prometheus:ro"
      - "./prometheus/appdata:/prometheus:rw"
    deploy:
      mode: host

  # https://hub.docker.com/r/zabbix/zabbix-server-mysql for image
  zabbix:
    image: zabbix/zabbix-server-mysql:alpine-5.4-latest
    container_name: zabbix
    environment:
      - DB_SERVER_HOST=192.168.6.11
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix-user
      - MYSQL_PASSWORD=zabbix-passwd
      - MYSQL_DATABASE=zabbix
      - ZBX_DEBUGLEVEL=5
    networks:
      metrics_internal:
        ipv4_address: 192.168.6.12
    ports:
      - "10051:10051"
    volumes:
      - "./zabbix/appdata:/usr/share:rw"
    depends_on:
      - mariadb

  # https://grafana.com/docs/grafana/latest/installation/docker/ for image data
  # https://github.com/alexanderzobnin/grafana-zabbix for zabbix datasource
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/alexanderzobnin/grafana-zabbix/releases/download/v4.1.4/alexanderzobnin-zabbix-app-4.1.4.zip;alexanderzobnin-zabbix-app
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/config/dashboards/base.json
    volumes:
      - ./grafana:/config
    networks:
      metrics_internal:
        ipv4_address: 192.168.6.13
    ports:
      - "10053:3000"
    depends_on:
      - prometheus
      - zabbix
  
  # https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql/ for image
  zabbix_viewer:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.4-latest
    container_name: zabbix-viewer
    environment:
      - ZBX_SERVER_HOST=192.168.6.12
      - ZBX_SERVER_PORT=10051
      - DB_SERVER_HOST=192.168.6.11
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix-user
      - MYSQL_PASSWORD=zabbix-passwd
      - PHP_TZ=America/Toronto
    networks:
      metrics_internal:
        ipv4_address: 192.168.6.14
    ports:
      - "10052:8080"
    depends_on:
      - zabbix

  # https://hub.docker.com/_/mariadb for image
  mariadb:
    image: mariadb:10
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
      - MARIADB_DATABASE=zabbix
      - MARIADB_USER=zabbix-user
      - MARIADB_PASSWORD=zabbix-passwd
    volumes:
      - ./mariadb/appdata:/var/lib/mysql
      - ./mariadb/config:/etc/mysql
    networks:
      metrics_internal:
        ipv4_address: 192.168.6.11
    ports:
      - "10055:3306"


networks:
  metrics_internal:
    ipam:
      driver: default
      config:
        - subnet: "192.168.6.0/24"
```
Also here is my mariadb "my.cnf" config file:
```cnf
[mysqld]
character-set-server = utf8
collation-server = utf8_unicode_ci
skip-character-set-client-handshake
```

##### STEPS TO REPRODUCE

To run it I just place the my.cnf file into ./mariadb/config/, and create ./mariadb/appdata/ , ./zabbix/appdata/snmp/ and then I just run:

```bash
docker-compose up &
```

##### EXPECTED RESULTS

I expected the DB to be provisionned and zabbix to run while trying to scrape for it's own agent

##### ACTUAL RESULTS

Here is my logs for zabbix server's launch:
```txt
** Preparing Zabbix server
** Using MYSQL_USER variable from ENV
** Using MYSQL_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: 192.168.6.11
* DB_SERVER_PORT: 3306
* DB_SERVER_DBNAME: zabbix
********************
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
**** MySQL server is not available. Waiting 5 seconds...
** Database 'zabbix' already exists. Please be careful with database COLLATE!
** Creating 'zabbix' schema in MySQL
zcat: /usr/share/doc/zabbix-server-mysql/create.sql.gz: No such file or directory
** Preparing Zabbix server configuration file
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ListenIP": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ListenPort": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SourceIP": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "LogType": 'console'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "LogFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "LogFileSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "PidFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DebugLevel": '5'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBHost": '192.168.6.11'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBName": 'zabbix'...updated
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBSchema": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBPort": '3306'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VaultDBPath": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VaultURL": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBUser": 'zabbix-user'...updated
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBPassword": '****'. Enable DEBUG_MODE to view value ...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartReportWriters": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "WebServiceURL": 'http://zabbix-web-service:10053/report'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HistoryStorageURL": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HistoryStorageTypes": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HistoryStorageDateIndex": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "DBSocket": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StatsAllowedIP": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartIPMIPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartPollersUnreachable": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartTrappers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartPingers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartDiscoverers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartHistoryPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartHTTPPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartPreprocessors": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartTimers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartEscalators": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartAlerters": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartTimers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartEscalators": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartLLDProcessors": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "JavaGateway": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "JavaGatewayPort": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartJavaPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartVMwareCollectors": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VMwareFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VMwarePerfFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VMwareCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "VMwareTimeout": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SNMPTrapperFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartSNMPTrapper": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HousekeepingFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "MaxHousekeeperDelete": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SenderFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "CacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "CacheUpdateFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartDBSyncers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HistoryCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "HistoryIndexCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TrendCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ValueCacheSize": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "Timeout": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TrapperTimeout": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "UnreachablePeriod": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "UnavailableDelay": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "UnreachableDelay": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "AlertScriptsPath": '/usr/lib/zabbix/alertscripts'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ExternalScripts": '/usr/lib/zabbix/externalscripts'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "FpingLocation": '/usr/sbin/fping'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "Fping6Location": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SSHKeyLocation": '/var/lib/zabbix/ssh_keys'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "LogSlowQueries": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "StartProxyPollers": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ProxyConfigFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "ProxyDataFrequency": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SSLCertLocation": '/var/lib/zabbix/ssl/certs/'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SSLKeyLocation": '/var/lib/zabbix/ssl/keys/'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "SSLCALocation": '/var/lib/zabbix/ssl/ssl_ca/'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "LoadModulePath": '/var/lib/zabbix/modules/'...added
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCAFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCRLFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCertFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherAll": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherAll13": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherCert": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherCert13": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherPSK": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSCipherPSK13": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSKeyFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSPSKIdentity": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "TLSPSKFile": ''...removed
** Updating '/etc/zabbix/zabbix_server.conf' parameter "User": 'zabbix'...added
Starting Zabbix Server. Zabbix 5.4.0 (revision 5059e20).
Press Ctrl+C to exit.

     7:20210526:164328.369 Starting Zabbix Server. Zabbix 5.4.0 (revision 5059e20).
     7:20210526:164328.369 ****** Enabled features ******
     7:20210526:164328.369 SNMP monitoring:           YES
     7:20210526:164328.369 IPMI monitoring:           YES
     7:20210526:164328.369 Web monitoring:            YES
     7:20210526:164328.369 VMware monitoring:         YES
     7:20210526:164328.369 SMTP authentication:       YES
     7:20210526:164328.369 ODBC:                      YES
     7:20210526:164328.369 SSH support:               YES
     7:20210526:164328.369 IPv6 support:              YES
     7:20210526:164328.369 TLS support:               YES
     7:20210526:164328.369 ******************************
     7:20210526:164328.369 using configuration file: /etc/zabbix/zabbix_server.conf
     7:20210526:164328.369 In zbx_load_modules()
     7:20210526:164328.369 End of zbx_load_modules():SUCCEED
     7:20210526:164328.369 In init_database_cache()
     7:20210526:164328.369 In zbx_mem_create() param:'HistoryCacheSize' size:16777216
     7:20210526:164328.369 valid user addresses: [0x7ffb110c2168, 0x7ffb120c1ff0] total size: 16776840
     7:20210526:164328.369 End of zbx_mem_create()
     7:20210526:164328.369 In zbx_mem_create() param:'HistoryIndexCacheSize' size:4194304
     7:20210526:164328.369 valid user addresses: [0x7ffb10cc2178, 0x7ffb110c1ff0] total size: 4193912
     7:20210526:164328.369 End of zbx_mem_create()
     7:20210526:164328.369 In init_trend_cache()
     7:20210526:164328.369 In zbx_mem_required_size() size:0 chunks_num:1 descr:'trend cache' param:'TrendCacheSize'
     7:20210526:164328.369 End of zbx_mem_required_size() size:414
     7:20210526:164328.369 In zbx_mem_create() param:'TrendCacheSize' size:4194304
     7:20210526:164328.369 valid user addresses: [0x7ffb108c2168, 0x7ffb10cc1ff0] total size: 4193928
     7:20210526:164328.369 End of zbx_mem_create()
     7:20210526:164328.369 End of init_trend_cache()
     7:20210526:164328.369 End of init_database_cache()
     7:20210526:164328.369 In init_configuration_cache() size:8388608
     7:20210526:164328.369 In zbx_mem_create() param:'CacheSize' size:8388608
     7:20210526:164328.369 valid user addresses: [0x7ffb100be168, 0x7ffb108bdff0] total size: 8388232
     7:20210526:164328.369 End of zbx_mem_create()
     7:20210526:164328.369 End of init_configuration_cache()
     7:20210526:164328.370 In init_selfmon_collector()
     7:20210526:164328.370 init_selfmon_collector() size:13384
     7:20210526:164328.370 End of init_selfmon_collector() collector:0x7ffb100ba000
     7:20210526:164328.370 In zbx_vc_init()
     7:20210526:164328.370 In zbx_mem_required_size() size:0 chunks_num:1 descr:'value cache size' param:'ValueCacheSize'
     7:20210526:164328.370 End of zbx_mem_required_size() size:419
     7:20210526:164328.370 In zbx_mem_create() param:'ValueCacheSize' size:8388608
     7:20210526:164328.370 valid user addresses: [0x7ffb0f8ba168, 0x7ffb100b9ff0] total size: 8388232
     7:20210526:164328.370 End of zbx_mem_create()
     7:20210526:164328.370 End of zbx_vc_init()
     7:20210526:164328.370 In zbx_tfc_init()
     7:20210526:164328.370 In zbx_mem_required_size() size:0 chunks_num:1 descr:'trend function cache size' param:'TrendFunctionCacheSize'
     7:20210526:164328.370 End of zbx_mem_required_size() size:436
     7:20210526:164328.370 In zbx_mem_create() param:'TrendFunctionCacheSize' size:4194304
     7:20210526:164328.370 valid user addresses: [0x7ffb0f4b8180, 0x7ffb0f8b7ff0] total size: 4193904
     7:20210526:164328.370 End of zbx_mem_create()
     7:20210526:164328.370 zbx_tfc_init(): slots:49925
     7:20210526:164328.370 End of zbx_tfc_init():
     7:20210526:164328.370 In zbx_db_get_database_type()
     7:20210526:164328.370 In DBconnect() flag:0
     7:20210526:164328.372 End of DBconnect():0
     7:20210526:164328.372 query [txnlev:0] [select userid from users limit 1]
     7:20210526:164328.373 [Z3005] query failed: [1146] Table 'zabbix.users' doesn't exist [select userid from users limit 1]
     7:20210526:164328.373 cannot select records from "users" table
     7:20210526:164328.373 End of zbx_db_get_database_type():ZBX_DB_UNKNOWN
     7:20210526:164328.373 cannot use database "zabbix": database is not a Zabbix database
```

```paste below

```
