### ISSUE TITLE
profiles setting on docker-compose file

### ISSUE THREAD

**Issue by David-COUDRAY** [zabbix/zabbix-docker#873]
##### SUMMARY
All container on docker-compose file doesn't pulling if they are profiles section setting.
I've remove profiles settings and work fine.

##### OS / ENVIRONMENT / Used docker-compose files
Debian 11
Last of docker and docker-compose version

##### STEPS TO REPRODUCE
That is the wrong code :
```
 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-5.4-latest
  profiles:
   - full
   - all
  ports:
   - "10050:10050"
```
This is a correct code :
```
 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-5.4-latest
  ports:
   - "10050:10050"
```
