### ISSUE TITLE
Make possible to define absolutely path for PSK files in zabbix-agent and zabbix-proxy images

### ISSUE THREAD

**Issue by heaveaxy** [zabbix/zabbix-docker#887]
##### SUMMARY

Hello there,
Location for PSK files hard-coded to zabbix home directory in docker-entrypoint.sh file: /var/lib/zabbix/enc/.
```bash
    # Use full path to a file for TLS related configuration parameters
    if [[ $var_name =~ ^TLS.*File$ ]]; then
        var_value=$ZABBIX_USER_HOME_DIR/enc/$var_value
    fi
```
So it make trouble with using docker-secret mechanism to provide PSK data to container, because docker mounts secrets to /run/secrets/ path.
Workaround is define PSK file path in following way: ../../../../run/secrets/filename
I see possible solution is to check defined path in ZBX_TLSPSKFILE environment variable: if it starts with "/" then it inserts to config as-is, else - inserts with "$ZABBIX_USER_HOME_DIR/enc" prefix.

##### OS / ENVIRONMENT / Used docker-compose files

Used OS for docker host: AlmaLinux 8.4
Container version: zabbix/zabbix-proxy-mysql:alpine-5.4-latest
Issue may be actual for any zabbix-proxy and zabbix-agent containers.

##### STEPS TO REPRODUCE

1. Create directory for docker-compose and related files.
2. Create file db-init-zabbix-proxy.sh with following content:
```bash
#!/usr/bin/sh
/usr/bin/mysql -uroot -proot_password -e \
"
CREATE DATABASE IF NOT EXISTS zabbix_proxy CHARACTER SET utf8 COLLATE utf8_bin;
CREATE USER IF NOT EXISTS zabbix_proxy IDENTIFIED BY 'proxy_password';
GRANT ALL PRIVILEGES ON zabbix_proxy.* TO zabbix_proxy;
"
```
3. Create file zabbix_proxy_psk with some valid psk-key.
4. Create docker-compose.yml with following content: 

```yaml
---
version: "3.5"
services:
  zabbix-proxy-db:
    image: 'mariadb:10.5.8'
    deploy:
      replicas: 1
    volumes:
      - "db-data:/var/lib/mysql/"
      - "db-conf:/etc/mysql"
      - "db-init-scripts:/docker-entrypoint-initdb.d/"
    networks:
      zabbix-proxy-net:
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
    configs:
      - source: zabbix-proxy-mysql-db-init
        target: /docker-entrypoint-initdb.d/zabbix-proxy-mysql-db-init.sh
        uid: "999"
        gid: "999"
        mode: 0700

  zabbix-proxy:
    image: zabbix/zabbix-proxy-mysql:alpine-5.4-latest
    deploy:
      replicas: 1
    networks:
      zabbix-proxy-net:
    ports:
      - target: 10051
        published: 10051
        protocol: tcp
        mode: ingress
    environment:
      DB_SERVER_HOST: "zabbix-proxy-db"
      MYSQL_DATABASE: "zabbix_proxy"
      MYSQL_USER: "zabbix_proxy"
      MYSQL_PASSWORD: "proxy_password"
      ZBX_PROXYMODE: "1"
      ZBX_HOSTNAME: "proxy.local"
      ZBX_SERVER_HOST: "::/0"
      ZBX_TLSCONNECT: "psk"
      ZBX_TLSACCEPT: "psk"
      ZBX_TLSPSKFILE: "/var/run/secrets/zabbix-proxy-psk"
      ZBX_TLSPSKIDENTITY: "proxy-psk"
    secrets:
      - zabbix-proxy-psk

volumes:
  db-data:
  db-conf:
  db-init-scripts:

networks:
  zabbix-proxy-net:

configs:
  zabbix-proxy-mysql-db-init:
    file: ./db-init-zabbix-proxy.sh

secrets:
  zabbix-proxy-psk:
    file: ./zabbix_proxy_psk
```
5. Run with: docker stack deploy --compose-file ./docker-compose.yml proxy

##### EXPECTED RESULTS

Zabbix proxy starts properly

##### ACTUAL RESULTS

Zabbix proxy fails with error:
```
   202:20211020:125810.980 cannot open file "/var/lib/zabbix/enc//var/run/secrets/zabbix-proxy-psk": [2] No such file or directory
     7:20211020:125810.980 One child process died (PID:202,exitcode/signal:1). Exiting ...
     7:20211020:125810.982 Zabbix Proxy stopped. Zabbix 5.4.6 (revision ed5eee8).
```

```paste below

```
