### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by Danielsups** [zabbix/zabbix-docker#888]
##### SUMMARY

Hey guys, i created a new compose file but I'm having some problems, first of all sometimes when i try to access localhost through the browser i get a "The connection was reset" error, but sometimes it goes through and i get a "Database error", when looking through the container log i get the message saying MySQL isn't answering, I'll put my docker-compose, .env files and prints down here, ir anything else is needed just let me know, thx everyone

##### OS / ENVIRONMENT / Used docker-compose files

docker-compose version: 1.29.2, build 5becea4c
OS: Ubuntu 20.04.3 LTS

### **docker-compose.yaml**
```

version: '3.7'

services:

  mysql:
    image: mysql:8.0
    init: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root#inter!@#
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix#inter!@#
    volumes:
     - /home/danielsps/Documents/git/zabbix/mysqldb-volume:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-5.4-latest
    init: true
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
      - zabbix-java-gateway
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix#inter!@#
      MYSQL_DATABASE: zabbix
      ZBX_JAVAGATEWAY_ENABLE: "true"
      ZBX_JAVAGATEWAY: zabbix-java-gateway
      ZBX_STARTJAVAPOLLERS: 5
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.4-latest
    init: true
    restart: always
    depends_on:
      - mysql
      - zabbix-server
    links:
      - mysql
      - zabbix-server
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix#inter!@#
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Recife
    ports:
      - "81:8080"

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-5.4-latest
    init: true
    restart: always
```
### **.env_zabbix**

`COMPOSE_PROJECT_NAME=zabbix
`

##### RESULTS

[Database error](https://prnt.sc/1xdve9d)
[Connection reset](https://prnt.sc/1xdvizt)
