### ISSUE TITLE
UBI8 / zabbix-web-mysql-54:5.4.9 : http error 500 / PHP Fatal error / Timezone database is corrupt

### ISSUE THREAD

**Issue by grunlab** [zabbix/zabbix-docker#909]
I have an issue with the ubi8 image zabbix-web-mysql-54:5.4.9 from redhat registry (registry.connect.redhat.com/zabbix/zabbix-web-mysql-54:5.4.9)

FYI, no issue with the previous version 5.4.7, it was working OK.

My deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: console
  name: console
  namespace: zabbix
  annotations:
    collectord.io/logs-replace.1-search: ^.+kube-probe.+$
    collectord.io/logs-replace.1-val: ""
spec:
  replicas: 2
  selector:
    matchLabels:
      run: console
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: console
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: run
                operator: In
                values:
                - console
            topologyKey: kubernetes.io/hostname
      containers:
        - name: console
          image: registry.connect.redhat.com/zabbix/zabbix-web-mysql-54:5.4.9
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: PHP_TZ
              value: "Europe/Paris"
            - name: ZBX_SERVER_NAME
              value: "2s59-v-k8s-zabbix-server"
            - name: ZBX_SERVER_HOST
              value: $(SERVER_SERVICE_HOST)
            - name: DB_SERVER_HOST
              value: "{{zabbix_database_host}}"
            - name: DB_SERVER_PORT
              value: "3300"
            - name: MYSQL_DATABASE
              value: "{{zabbix_database_name}}"
            - name: MYSQL_USER
              value: "{{zabbix_database_user}}"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-database-password
                  key: zabbix-database-password
            - name: ZBX_SSO_SETTINGS
              value: "{'use_proxy_headers':true}"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 128Mi
          volumeMounts:
            - name: airbus-internal-root
              mountPath: /etc/pki/ca-trust/extracted/pem
            - name: maintenance
              mountPath: /usr/share/zabbix/conf/maintenance.inc.php
              subPath: maintenance.inc.php
            - name: sso-cert
              mountPath: /etc/zabbix/web/certs
          livenessProbe:
            httpGet:
              path: /favicon.ico
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: airbus-internal-root
          configMap:
            name: airbus-internal-root
        - name: maintenance
          configMap:
            name: maintenance
        - name: sso-cert
          secret:
            secretName: console-sso-cert
```

OK, pod correctly deployed / container ready:
```
$ kubectl get pod
NAME                       READY   STATUS    RESTARTS   AGE
console-6c5bb9cbbc-7q4w5   1/1     Running   0          94m
```

Issue:
```
$ curl --head https://kraken.2s59-v.eu.airbus.corp/
HTTP/1.1 500 Internal Server Error
Cache-Control: no-store, no-cache, must-revalidate
Content-Type: text/html; charset=UTF-8
Date: Fri, 21 Jan 2022 16:49:41 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: nginx
Set-Cookie: zbx_session=eyJzZXNzaW9uaWQiOiIzZThmZjMyNGUwMzNjYTk3YmNlOWRhZDFiM2IzYjcxMyIsInNpZ24iOiI1ZTY5MzJiZWQxMzNiZjk1ODk4OTcyZGVhMzExMDMyZTNlMjY2NzE0NTVhMWE0MmZjZmFlMWFlYjQ1N2Y0YjAxIn0%3D; HttpOnly
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/7.4.19
X-Xss-Protection: 1; mode=block
```

Container logs:
```
$ kubectl logs console-6c5bb9cbbc-7q4w5
...
2022/01/21 16:49:41 [error] 20#0: *935 FastCGI sent in stderr: "PHP message: PHP Warning:  date(): Invalid date.timezone value 'Europe/Paris', we selected the timezone 'UTC' for now. in /usr/share/zabbix/include/page_header.php on line 156PHP message: PHP Fatal error:  date(): Timezone database is corrupt - this should *never* happen! in /usr/share/zabbix/include/page_header.php on line 156" while reading response header from upstream, client: 10.121.194.76, server: zabbix, request: "HEAD / HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "kraken.2s59-v.eu.airbus.corp"
...
```

I've tried with the centos8 image from dockerhub registry (docker.io/zabbix/zabbix-web-nginx-mysql:5.4.9-centos) using the same deployment  : no issue with this image, it is working OK.

So the issue looks specific to the ubi8 image.
