### ISSUE TITLE
Add Docker monitoring support into Agent2

### ISSUE THREAD

**Issue by theunreal89** [zabbix/zabbix-docker#917]
Can you please create and mantain a version of Zabbix Agent 2 able to monitor Docker enviroment? I am manually do this by building the image from the following simple Dockerfile
```
FROM zabbix/zabbix-agent2:alpine-latest
MAINTAINER "Me"
USER root
RUN apk update && apk add --no-cache docker
RUN addgroup zabbix docker
```
and then exposing volume /var/run/docker.sock:/var/run/docker.sock:ro. It is painful to do it manually as I have to build and push from 2 different arch for every base image update, but for you would be much simpler to do it. I think lot of people would need Docker monitoring feature from a Agent2 container.

Thanks!

**Comment by dotneft** [comment]
The final image is quite big with Docker package and all dependencies, for example docker-engine requires 76.63 MB (

**Comment by theunreal89** [comment]
I can understand, mine became 297 MB:
![image](https://user-images.githubusercontent.com/3491169/154049339-785b7cb1-54fe-40a9-8b06-29d711d5f7e0.png)
but I think could be acceptable in some cases and by the way you could use a separate tag (like docker-monitoring-latest) to make it optional for who is interested in it.
It is very common to have Docker environments nowadays and having a powerful tool like Zabbix monitoring it make it way easier to keep it under control.

**Comment by guilh22** [comment]
I understand the need for this, but like dotneft said it would take too much. Nothing prevent you to build your image from zabbix-agent2:alpine-latest and add the additionnal package. It is actually common to do this in some enterprise to add there own package requirements.

**Comment by theunreal89** [comment]
Yes sure, I understand. Thanks anyway!

**Comment by dsteinkopf** [comment]
May I ask why you need to add the package "docker"? I am monitoring my docker host by just running the agent created by this simple Dockerfile:
```
FROM zabbix/zabbix-agent2:alpine-5.4-latest
# needed because of user access rights on /var/run/docker.sock (+ other reasons?)
USER zabbix:998
```
This is compiled every night by running docker-compose pull, then build in this - and all my compose-directories.

And this snippet from my zabbix' docker-compose.yml:
```
  zabbix-agent:
    build: build-zabbix-agent
    environment:
      - ZBX_HOSTNAME=my-agent-on-docker,xxx
      - ZBX_SERVER_HOST=172.16.41.100
      - ...
    pid: "host" # access and manipulate other containers
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      zbxnet:
        ipv4_address: 172.16.41.101
```
Then, in Zabbix, I am using the official docker template.

What am I missing? What else could I do, having installed the "docker" package in the agent?
Thank you.
