### ISSUE TITLE
docker-entry.sh does not create the default user when MYSQL_ROOT_PASSWORD is supplied.

### ISSUE THREAD

**Issue by eb4x** [zabbix/zabbix-docker#924]
##### SUMMARY

`server-mysql` `docker-entry.sh` does not create the default `'zabbix'` when **only** `MYSQL_ROOT_PASSWORD` is supplied.

`web-*-mysql` does not create a user at all. `CREATE_ZBX_DB_USER` does nothing in `docker-entry.sh` for `web-*-mysql`,
so I suggest it should create a user if one gets specified. Or make it clear that it shouldn't create anything, and clean out references to `MYSQL_ROOT_PASSWORD`

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: zabbix
spec:
  containers:
  - name: mysql
    image: docker.io/mariadb:10.6.1
    env:
    - { name: MYSQL_ROOT_PASSWORD, value: changeme }
    ports:
    - { hostPort: 3306, containerPort: 3306, protocol: TCP }
    volumeMounts:
    - { name: zabbix-mysql-pvc, mountPath: "/var/lib/mysql" }

  - name: server
    image: docker.io/zabbix/zabbix-server-mysql:6.0.0-alpine
    env:
    - { name: MYSQL_ROOT_PASSWORD, value: changeme }
    #- { name: MYSQL_USER, value: server }
    ports:
    - { hostPort: 10051, containerPort: 10051, protocol: TCP }

  - name: web
    image: docker.io/zabbix/zabbix-web-nginx-mysql:6.0.0-alpine
    env:
    - { name: MYSQL_ROOT_PASSWORD, value: changeme }
    #- { name: MYSQL_USER, value: web }
    ports:
    - { hostPort: 8080, containerPort: 8080, protocol: TCP }
    - { hostPort: 8443, containerPort: 8443, protocol: TCP }

  hostAliases:
  - ip: 127.0.0.1
    hostnames:
    - mysql-server
    - zabbix-server
  volumes:
  - name: zabbix-mysql-pvc
    persistentVolumeClaim:
      claimName: zabbix-mysql-data
```

```paste below
podman play kube zabbix-mysql-pod.yaml
```

##### EXPECTED RESULTS

Create default 'zabbix' user OR specified user if MYSQL_ROOT_PASSWORD is supplied.

##### ACTUAL RESULTS

zabbix-server doesn't create a default user.
zabbix-web doesn't create a user at all.
