### ISSUE TITLE
Zabbix 6.0.4  PHP Fatal error: Uncaught Error: Class "CMessageHelper"

### ISSUE THREAD

**Issue by hzd2020** [zabbix/zabbix-docker#959]
##### SUMMARY
```
zabbix-web | 2022-05-20 11:04:29,145 INFO success: nginx entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web | 2022-05-20 11:04:29,145 INFO success: nginx entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web | 2022-05-20 11:04:29,145 INFO success: php-fpm8.1 entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web | 2022-05-20 11:04:29,145 INFO success: php-fpm8.1 entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
zabbix-web | 127.0.0.1 - - [20/May/2022:11:04:30 +0800] "GET / HTTP/1.1" 200 3942 "-" "curl/7.81.0" "-"
zabbix-web | 2022/05/20 11:04:41 [error] 18https://github.com/zabbix/zabbix-docker/pull/18: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Class "CMessageHelper" not found in /usr/share/zabbix/include/func.inc.php:2039
zabbix-web | Stack trace:
zabbix-web | #0 /usr/share/zabbix/include/func.inc.php(2298): error()
zabbix-web | #1 /usr/share/zabbix/include/classes/core/CAutoloader.php(77): zbx_err_handler()
zabbix-web | https://github.com/zabbix/zabbix-docker/pull/2 /usr/share/zabbix/include/classes/core/CAutoloader.php(77): require('...')
zabbix-web | https://github.com/zabbix/zabbix-docker/pull/3 /usr/share/zabbix/include/func.inc.php(2039): CAutoloader->loadClass()
zabbix-web | https://github.com/zabbix/zabbix-docker/pull/4 /usr/share/zabbix/include/classes/api/wrappers/CFrontendApiWrapper.php(80): error()
zabbix-web | https://github.com/zabbix/zabbix-docker/pull/5 /usr/share/zabbix/include/classes/api/wrappers/CApiWrapper.php(82): CFrontendApiWrapper->callMethod()
zabbix-web | https://github.com/zabbix/zabbix-docker/pull/6 /usr/share/zabbix/include/classes/user/CWebUser.php(99): CApiWrapper->__call()
zabbix-web | https://github.com/zabbix/zabbix-docker/pull/7 /usr/share/zabbix/include/classes/core/ZBase.php(464): CWebUser::checkAuthentication()
zabbix-web | https://github.com/zabbix/zabbix-docker/pull/8 /usr/share/zabbix/include/classes/core/ZBase.php(187): ZBase->authenticateUser()
zabbix-web | https://github.com/zabbix/zabbix-docker/pull/9 /usr/share/zabbix/include/config.inc.php(25): ZBase->run()
zabbix-web | https://github.com/zabbix/zabbix-docker/pull/10 /usr/share/zabbix/index.php(24): require_once('...')
zabbix-web | https://github.com/zabbix/zabbix-docker/pull/11 {main}
zabbix-web | th" while reading response header from upstream, client: 127.0.0.1, server: zabbix, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "localhost:8080"
zabbix-web | 127.0.0.1 - - [20/May/2022:11:04:41 +0800] "GET / HTTP/1.1" 500 5 "-" "curl/7.81.0" "-"
zabbix-web | 2022/05/20 11:04:51 [error] 18#18: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Class "CMessageHelper" not found in /usr/share/zabbix/include/func.inc.php:2039

```
Zabbix version is: 6.0.4

##### OS / ENVIRONMENT / Used docker-compose files

```
OS:ubuntu server 20.0.4, Docker 20.10.16,Docker Compose version v2.5.0
```
##### STEPS TO REPRODUCE

```
version: '3.8'
services:
 zabbix-server:
  build: .
  container_name: zabbix-server
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/alternatives/:/etc/alternatives/
   - /etc/ZabbixDokcer/alertscripts:/usr/lib/zabbix/alertscripts
   - /etc/ZabbixDokcer/externalscripts:/usr/lib/zabbix/externalscripts

  environment:
   DB_SERVER_HOST: mysql-server
   MYSQL_DATABASE: zabbix 
   MYSQL_USER: zabbix
   MYSQL_PASSWORD: Password
   MYSQL_ROOT_PASSWORD: Password
   LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu
   ZBX_CACHESIZE: 4G
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  depends_on:
   - mysql-server
  networks:
   zbx_net_backend:
     ipv4_address: 172.16.239.2 
     aliases:
      - zabbix-server
      - zabbix-server-mysql
      - zabbix-server-centos-mysql
      - zabbix-server-mysql-centos
   zbx_net_frontend:
     ipv4_address: 172.16.238.2 

  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0


 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:ubuntu-6.0-latest
  container_name: zabbix-web
  ports:
   - "8080:8080"
   - "443:8443"
  environment:
   DB_SERVER_HOST: "mysql-server"
   MYSQL_DATABASE: "zabbix" 
   MYSQL_USER: "zabbix"
   MYSQL_PASSWORD: Password
   MYSQL_ROOT_PASSWORD: Password
   ZBX_SERVER_NAME: "
```

```yaml

```

##### ACTUAL RESULTS

```paste below

```
