### ISSUE TITLE
How to upgrade zabbix 5 to 6 installed with docker packages

### ISSUE THREAD

**Issue by nicolasgoudard** [zabbix/zabbix-docker#967]
Hello

I have installed Zabbix alpine-5.4  docker packages on my Linux server (Ubuntu  20.04).
I used the following docker-compose and the .env files. Now the server is in production for 1 year or more, and the database is filled 
How to upgrade it to zabbix 6 without loosing datas ?

docker-compose.xml

```
version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:alpine-5.4-latest
  restart: always
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
  links:
   - mysql-server:mysql-server
  env_file:
   - .env_db_mysql
   - .env_srv
  depends_on:
   - mysql-server
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-mysql
      - zabbix-server-alpine-mysql
      - zabbix-server-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 mysql-server:
  image: mysql:8.0.25
  restart: always
  command:
   - mysqld
   - --character-set-server=utf8
   - --collation-server=utf8_bin
   - --default-authentication-plugin=mysql_native_password
  volumes:
   - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
  env_file:
   - .env_db_mysql
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - mysql-server
     - zabbix-database
     - mysql-database

 zabbix-web-apache-mysql:
  image: zabbix/zabbix-web-apache-mysql:alpine-5.4-latest
  restart: always
  ports:
   - "8080:8080"
   - "6443:8443"
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
   - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
   - ./zbx_env/etc/zabbix/apache_ssl.conf:/etc/zabbix/apache_ssl.conf:ro
  env_file:
   - .env_db_mysql
   - .env_web
  depends_on:
   - mysql-server
   - zabbix-server
 healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-apache-mysql
     - zabbix-web-apache-alpine-mysql
     - zabbix-web-apache-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Apache web-server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "apache2"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

networks:
  zbx_net_frontend:
    driver:  bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24


.env_agent
ZBX_ENABLEREMOTECOMMANDS=1
ZBX_SERVER_HOST=localhost
ZBX_ACTIVESERVERS=localhost
ZBX_HOSTNAME=
```

.env_db_mysql
```
MYSQL_USER=myzabbixuser
MYSQL_PASSWORD=MYPASSWORD
MYSQL_ROOT_PASSWORD= MYPASSWORDSQL
MYSQL_DATABASE=zabbixdbdb
```

.env_srv
```
ZBX_JAVAGATEWAY_ENABLE=true
ZBX_STARTJAVAPOLLERS=5
ZBX_ENABLE_SNMP_TRAPS=true
ZBX_CACHESIZE=256M
```

.env_web
```
ZBX_SERVER_NAME=MyComputeCluster
ZBX_POSTMAXSIZE=256M
PHP_TZ=Europe/Paris
```

Thanks in advance for your precious help

Best regards
