### ISSUE TITLE
Unable to connect to Postgres instance using SSL

### ISSUE THREAD

**Issue by joeldeteves** [zabbix/zabbix-docker#969]
##### SUMMARY
Using Docker, the zabbix-server container fails to connect to a Zabbix database using Digital Ocean Managed Postgres.

- DO has a hard requirement of SSL, which I had to enable for all my other apps on that database cluster.

- I tried setting `ZBX_DBTLSCONNECT` to **required** but the connection fails with the following:
```
**** PostgreSQL server is not available. Waiting 5 seconds...
```

- I also tried setting it to **require** which is what I would expect to use for postgres but it results in the following error in the container logs:
    ```
    zabbix_server [6]: ERROR: invalid "DBTLSConnect" configuration parameter: 'require'
    ```

- The zabbix-web container connects just fine and shows up in the Postgres logs.

- I am also able to exec into the zabbix-server container and connect to the Postgres instance from there.

- However, for some reason I don't see any connection attempts from the zabbix-server container showing up in the Postgres logs, even though I verified I can connect from inside the container running a manual command 

##### OS / ENVIRONMENT / Used docker-compose files

I am running Zabbix 5.4.4 official docker images on Ubuntu 18.04 / Docker CE 20.10.16

##### CONFIGURATION

I am using Ansible. Here's a sample of the config:
```
    - name: Setup Zabbix server container
      docker_container:
        name: zabbix-server
        image: zabbix/zabbix-server-pgsql:ubuntu-5.4.4
        restart_policy: unless-stopped
        env:
          TZ: "America/Vancouver"
          ZBX_SERVER_NAME: "Zabbix"
          ZBX_SERVER: "zabbix"
          ZBX_LISTENIP: 0.0.0.0
          ZBX_DBTLSCONNECT: required
          DB_SERVER_HOST: zabbix-db-host
          DB_SERVER_PORT: "25060"
          POSTGRES_USER: zabbix
          POSTGRES_DB: zabbix
          POSTGRES_PASSWORD: mysupersecretpassword
        ports:
          - 10051:10051
```

##### STEPS TO REPRODUCE

Try to connect zabbix-server pgsql container to a Digital Ocean Managed Postgres instance (or any other instance that has SSL hard requirement)

##### EXPECTED RESULTS

Zabbix should connect to the DB when the DB TLS option is specified

##### ACTUAL RESULTS

** Docker Logs:**
```
** Preparing Zabbix server
** Using POSTGRES_USER variable from ENV
** Using POSTGRES_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: zabbix-db-host
* DB_SERVER_PORT: 25060
* DB_SERVER_DBNAME: zabbix
* DB_SERVER_SCHEMA: public
********************
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...
```
