### ISSUE TITLE
help with fping default timeout

### ISSUE THREAD

**Issue by edwardchenchen** [zabbix/zabbix-docker#976]
##### SUMMARY
Timeout is experienced on fping

```
206:20220621:190330.553 Failed to execute command "/usr/bin/fping -c1 -t50 -i0 xxx.com": Timeout while executing a shell script.
   206:20220621:190330.553 Timeout while executing "/usr/bin/fping -c1 -t50 -i0 xxx.com"
```
I looked into fping official doc and zabbix doc
https://fping.org/fping.1.html
https://www.zabbix.com/documentation/current/en/manual/config/items/itemtypes/simple_checks#icmp_pings
<img width="760" alt="image" src="https://user-images.githubusercontent.com/6397192/174763078-e4192bae-ef9b-436a-b961-d57c49a35cad.png">
I don't understand is -t50 the default?
How can I change it? 50ms is too aggressive
##### CONFIGURATION
I am using 
```
Pi 4
Debian 11
Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
Docker version 20.10.17, build 100c701
zabbix/zabbix-server-mysql:ubuntu-6.0-latest
```
default image, no configuration or ENV changed
docker-compose small changes from
https://github.com/zabbix/zabbix-docker/blob/6.0/docker-compose_v3_ubuntu_mysql_latest.yaml

```yaml
version: '3.5'
services:
 zabbix-server:
  restart: always
  image: zabbix/zabbix-server-mysql:ubuntu-6.0-latest
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  environment:
   - DB_SERVER_HOST=mysql-server
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix
   - MYSQL_DATABASE=zabbix
  depends_on:
   - mysql-server
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
```

##### ACTUAL RESULTS
```
206:20220621:190330.553 Failed to execute command "/usr/bin/fping -c1 -t50 -i0 xxx.com": Timeout while executing a shell script.
   206:20220621:190330.553 Timeout while executing "/usr/bin/fping -c1 -t50 -i0 xxx.com"
```
