### ISSUE TITLE
password authentication failed for user "--dbname"

### ISSUE THREAD

**Issue by jooola** [zabbix/zabbix-docker#991]
##### SUMMARY

The web-nginx-pgsql/alpine/docker-entrypoint.sh file is referring to `DB_SERVER_ROOT_USER` to check for the database availability:

https://github.com/zabbix/zabbix-docker/blob/174bbc8c26b08c7e43b6e7102d43bc935fb2d035/Dockerfiles/web-nginx-pgsql/alpine/docker-entrypoint.sh#L101-L104

But the DB_SERVER_ROOT_USER is missing from the script and makes the check fail with:

```
pyzabbix-postgres-server-1  | 2022-07-23 15:39:53.661 UTC [93] FATAL:  password authentication failed for user "--dbname"
pyzabbix-postgres-server-1  | 2022-07-23 15:39:53.661 UTC [93] DETAIL:  Role "--dbname" does not exist.
pyzabbix-postgres-server-1  | 	Connection matched pg_hba.conf line 99: "host all all all md5"
pyzabbix-zabbix-web-1       | **** PostgreSQL server is not available. Waiting 5 seconds...

```

##### OS / ENVIRONMENT / Used docker-compose files

Zabbix 4.0

```yml
---
# For development purpose only
version: "3.8"

services:
  postgres-server:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-4.0-latest
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    depends_on:
      - postgres-server

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-4.0-latest
    ports:
      - 8888:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    depends_on:
      - postgres-server
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

```
